// BEGIN -- PAGE -- read-access.adoc
// BEGIN PAGE DEFINITION
//  LOCATION modules/ROOT/pages/
//  PURPOSE:
//    This is a standard content presentations page.
//    Its name/title identify the content/topic
//  PARAMETERS:
//    None
//  INCLUSION USAGE --
//    This module uses attributes from:
//    - /modules/ROOT/pages/_partials/_page-index.adoc -- xref page links
//
//    This module uses these inclusions:
//    - /modules/ROOT/pages/_partials/_std-hdr-sgw.adoc -- std attribute environment
//    - /modules/ROOT/pages/_partials/block-abstract.adoc --  std text block for page header content
//    - /modules/ROOT/pages/_partials/block-related-content-deploy.adoc --  std text block for page footer content
//    - modules/ROOT/assets/images -- .png/.jpeg images
//  INCLUSION USAGE
// END PAGE DEFINITION
= Access Grants
:description: How to implement Sync Gateway access controls in the Sync Function using access grants, users, roles and channels

include::partial$_std-hdr-sgw.adoc[]

:param-topic-group: access-control
:param-abstract: pass:q[The sync function API provides several methods that you can use to validate and control user access to databases and documents.]
include::partial$block-abstract.adoc[]


== Introduction

In the Couchbase Mobile ecosystem, every {user--xref} and {role--xref} is granted access to zero, one or more {channels--xref}.
It is this channels list that determines the documents users can access.

A user can only read documents that are in at least one of their assigned channels; whether directly or as part of an assigned role.

NOTE: All users can implicitly access any document in the {channels--xref-public-channel}

Once a user is granted access to a new channel, the {changes-feed--xref} will include all existing documents in that channel, even those from earlier sequences than the current request's `since` parameter.
So, the next replication pull request, will retrieve all documents to which the user now has access.


[#lbl-access-grants]
== Access Grants

Make user or role access grants in one of the following ways:

* Directly through the Admin REST API -- see: <<lbl-admin-rest-api>>
// * Statically, by inclusion in the configuration file -- see: <<lbl-configuration-file>>
* Dynamically, in the <<lbl-sync-function>> when a document is accessed:

The {sync-function--xref} is the preferred method for granting access to channels programmatically.
Here the document access and routing requirements are derived from document properties or, more securely, from a designated extended attribute (XATTR) -- see: {using-xattr-access-grants--xref} for how to define the XATTR.

Note that access grants do not confer, nor constrain, the type of access.
You can explicitly implement write access controls within your Sync Function; perhaps restricting updates to specific users or roles -- for more on this see <<lbl-control-write-access>>:


[#lbl-sync-function]
== Sync Function

Calling {sync-function--xref-access-cmd} grants a user access to a channel.

So, for example, this would allow a document to act as a membership, or access-control, list.

A typical example is a document that represents a shared resource (like a chat room or photo gallery) -- see: <<ex-helper>>.


[#ex-helper]
.Using the Access helper function
====
[source,javascript]
----
function (doc, olddoc, meta) {
  if (doc.type == "chatroom") {  // <.>
    access(doc.members, // <.>
      meta.xattrs.channelXattr);  // <.>
  }
}
----
In this example:

<.> A chat room is represented by a document with a `type` property set to `chatroom`.
<.> Here the chatroom document's `members` property contains the names of all valid chatroom users.
These users need to be granted access to the chat channel
<.> Here the chat message channel is picked up from the XATTR key `channelXattr` and the 'access()' function grants all members access to that channel.

====

The `access()` function can also operate on roles.
If a user name string begins with `role:` then the remainder of the string is interpreted as a role name.
There's no ambiguity here, because ":" is an illegal character in a user or role name.

Because anonymous requests are authenticated as the user "GUEST", you can make a channel and its documents public by calling `access` with a username of `GUEST`.


// [#lbl-configuration-file]
// == Configuration File

// A user can be granted access to a channel through the {legacy-configuration-properties--pfx}#databases-this_db-users-this_user-admin_channels[admin_channels] property in the configuration file.


[#lbl-admin-rest-api]
== Admin REST API

A user can be granted access to a channel through the `admin_channels` property on the {rest-api-admin--pfx}#/user/put\__db___user__name_[/+\{db}+/user/+{name}+] admin REST API endpoint.


[#lbl-revoke-access]
== Revoke Access

Revoking access to a channel can cause a user to lose access to documents, if s/he no longer has access to any channels those documents are in.

However, the replicator does _not_ currently delete such documents that have already been synced to a user's device (although future changes to those documents will not be replicated.)
This is a design limitation of Sync Gateway that may be resolved in the future.

* A GET request to a document not assigned to one or more of the user's available channels fails with a 403 error.
* The `_all_docs` property is filtered to return only documents that are visible to the user.
* The `_changes` property ignores requests (via the `channels` parameter) for channels not visible to the user.


[#lbl-inspect-access]
== Inspect Access

You can use the admin REST API to see what channels a user has access to.
Issue an {rest-api-admin--pfx}#/database/get
\__db___all_docs[+/\{tkn-db}/_user/\{name}+] request.
Here's an example of the response.
The output shows that the user `pupshaw` has access to channels `all` and `hoopy`.

[source,json]
----
{
    "admin_channels": [
        "all"
    ],
    "admin_roles": [
        "froods"
    ],
    "all_channels": [
        "all",
        "hoopy"
    ],
    "name": "pupshaw",
    "roles": [
        "froods"
    ]
}
----

The `all_channels` property of a user account determines the channels a user can access.
Its value is derived from the union of:

* The user's `admin_channels` property, which is set using the Admin REST API.
* The channels the user has been granted access to by `access()` calls from sync functions invoked for current revisions of documents.
* The `all_channels` properties of any roles the user belongs to. These are themselves computed using the above rules.


// tag::write-access[]
[#lbl-control-write-access]
== Control Write Access

Use the Sync Function's helper functions to control who or what can make document updates.

So can require that the user making the change has a specific name, role or channel access -- as shown in <<ex-check-write-access>> -- by using any combination  of:

* {sync-function--xref-require-user}
* {sync-function--xref-require-role}
* {sync-function--xref-require-channel}



[#ex-check-write-access]
.Control Write Access
====
Here the simple Sync Function validates whether the user modifying a document is a valid owner by checking if they are recorded as an owner of the old document:

[source, javascript]
----
function (doc, oldDoc, meta) {
  if (oldDoc) {
    requireUser(oldDoc.owner); // <.>
  }
  if (meta.xattr.channelxattr) {
    requireAccess(meta.xattr.channelxattr); // <.>
  } else
    {
      throw("No channel access granted")
    }
}
----
<.> If the user making the change is not an owner of the pre-change document, an exception is thrown and the update is rejected with an error.
<.> Here we check the designated xattr for the document channel(s) and require the user making the change to have access to on or more of the channels.
If the xattr is not set we throw an exception.


====

See <<ex-helpers>> for more helper function examples.

NOTE: When sending a change to Sync Gateway through the {rest-api-admin--xref}, the Sync Function executes with _admin privileges_. Calls to `requireUser`, `requireAccess` and `requireRole` will be no-ops, and will always appear successful.


[#ex-helpers]
.Helper Function examples
====
This example shows how to use some of the helper functions:

[source,javascript]
----

requireUser("snej") // <.>

requireUser(["snej", "jchris", "tleyden"]) // <.>

requireRole("admin") // <.>

requireRole(["admin", "old-timer"]) // <.>

requireAccess("events") // <.>

requireAccess(["events", "messages"]) // <.>
----
<.> throw an error if username is not "snej"
<.> throw if username is not in the list
<.> throw an error unless the user has the "admin" role
<.> throw an error unless the user has one of those roles
<.> throw an error unless the user has access to read the "events" channel
<.> throw an error unless the can read one of these channels
====


TIP: To create and manage user accounts, refer to {users--xref}.

// end::write-access[]


[#lbl-replication]
== Replication

By default, Couchbase Lite gets all the channels to which the configured user account has access.
This behavior is suitable for most apps that rely on {authentication-users--xref} and the {sync-function--xref} to specify which data to pull for each user.

Optionally, a Couchbase Lite "pull" replication can also specify a comma-separated list of channel names to receive documents from.
In this case, the replication from Sync Gateway will only pull documents tagged with those channels.
Client apps can use this ability to intelligently sync with a subset of the available documents from the database.

:param-bookmark: channels
include::partial$blocklinks-cbl.adoc[]


include::partial$block-related-content-sync.adoc[]

// END -- PAGE -- read-access.adoc
