= Audit Logging
:page-edition: {enterprise}
:description: Audit Logging provides tools for administrators to track operational irregularities and to support regulatory and security compliance standards, such as link:https://www.hhs.gov/hipaa/index.html[HIPAA] and link:https://soc2.co.uk/soc2[SOC-2].

[abstract]
{description}

== About Audit Logging

Key concepts, use cases and sign posting
Explain audit log files, only one active at a time that they’re written etc

IMPORTANT: Sg_collect does NOT collect audit log information


== Security Considerations

Viewing and managing Audit Logs permissions are enforced through Capella RBAC controls. 
Logs are encrypted both in transit to prevent unauthorized access or tampering, all communication supports TLS.
Logs are immutable and only accessible via read-only APIs, thus ensuring logs cannot be altered once recorded.

== Audit Log Configuration



=== Activity Logging

Audit Logging activities such as enabling/disabling, export requests and streaming state changes are captured in the Capella Activity Logs.

=== Audit Events

Database level audit events are segregated into per SGW database specific audit logs
Tagged at a database level to distinguish between events coming from different databases
The fields the event was called with are also added if applicable to the optional context property of the event
For more information, see xref:audit-log-events.adoc[audit events reference page].

== See Also

* xref:manage-audit-logs.adoc[]

* xref:audit-log-events.adoc[]

* xref:sgcollect-info.adoc[]