= Audit Logging
:page-edition: Enterprise
:description: Audit Logging provides tools for administrators to track operational irregularities and to support regulatory and security compliance standards, such as link:https://www.hhs.gov/hipaa/index.html[HIPAA] and link:https://soc2.co.uk/soc2[SOC-2].

[abstract]
{description}

== About Audit Logging

Audit Logging provides tools for administrators to track operational irregularities and to support regulatory and security compliance standards, such as link:https://www.hhs.gov/hipaa/index.html[HIPAA] and link:https://soc2.co.uk/soc2[SOC-2].

There is only one audit log file active at a time, which is periodically rotated based on the following properties:

* `logging.audit.rotation.max_age` - The maximum number of days to retain old log files.

* `logging.audit.rotation.max_size` - The maximum size in MB of the log file before it gets rotated.

* `logging.audit.rotation.rotated_logs_size_limit` - The maximum size in MB of log files before deletion.

* `logging.audit.rotation.rotation_interval` - If set, the interval at which log files are rotated, even if max_size is not reached.

For more information about log file properties, see xref:rest-admin-api.adoc#api-explorer[the Admin REST API explorer].

Logs are immutable and cannot be altered once recorded.
Viewing and managing audit logs permissions are enforced through Sync Gateway RBAC controls. 
Logs are written locally on each Sync Gateway node.

IMPORTANT: Rotated audit logs are automatically pruned at a default value of six days.
Administrators must ensure the rotated logs are picked up before they are deleted.

== Audit Events

Audit logging is an opt-in feature that allows you to track events associated with administrative, management, and end-user operations made in Sync Gateway.
These logs are presented as a https://jsonlines.org/[JSON-lines formatted series of events].

Audit events are tagged at a database level to distinguish between events coming from different databases.
The fields the event was called with are also added if applicable to the optional context property of the event.

For more information, see xref:audit-log-events.adoc[audit events reference page].

NOTE: Event auditing occurs per Sync Gateway node, capturing its own events only.
If you require a cluster-wide record, the records must be manually consolidated by an adminstrator.

=== Audit Event Types

Audit Events can be one of the following types:

* `Admin` - Events that track administrative and configuration changes.

* `Data` - Events that track attempts to access and change data.

* `User` - Events that track end-user operations.

=== Audit Event Scopes

Audit events have scope, this affects how they can be configured.
The audit events scopes are:

* `Database` - These events are specific to a database such as `AuditIDDocumentUpdate 55002`, and can only be enabled/disabled at the database configuration level. 
Database level audit events are segregated into per Sync Gateway database specific audit logs.

*  `Global` - These events are considered global such as `AuditIDSyncGatewayStartup 53260`, and have to be enabled/disabled in the bootstrap/startup config.

IMPORTANT: Sg_collect does NOT collect audit log information as audit logs contain sensitive, unredacted data.

== See Also

* xref:manage-audit-logs.adoc[]

* xref:audit-log-events.adoc[]

* xref:sgcollect-info.adoc[]

* xref:rest-api-admin.adoc[]

* xref:rest_api_admin_static.adoc[]
