= Auto-Purge on Channel Access Revocation
:page-aliases: anchor-auto-purge-channel-access-revocation
:page-edition: 3.0
:description: pass:q[Auto-purge behavior on loss of access to document channels]
:keywords: access control, document routing, sync, auto-purge

include::partial$_std-hdr-sgw.adoc[]


// BEGIN -- Page Attributes
:SGW: pass:q[_Sync Gateway_]
// END -- Page Attributes


//  BEGIN -- Page Heading
:param-topic-group: access-control
:param-abstract!:
:param-related!:
include::partial$block-abstract.adoc[]
//  END -- Page Heading

CAUTION: This is a breaking change. +
In {Sgw-te} 2.x these documents remain in the local database on channel access loss.

== Overview

// If the document was previously routed to a channel, but the current call to the sync function (for an updated revision) doesn't route it to that channel, the document is removed from the channel.

// This may cause users to lose access to that document -- see <<lbl-access-revocation>> for the revocation behavior.


// :param-page: replication
// :param-bookmark: replication-events
// include::partial$blocklinks-cbl.adoc[]


// [#lbl-access-revocation]
// == Access Revocation

Whenever a user loses access to a channel (or channels) all documents in the channel(s) are auto-purged from local Couchbase Lite databases. +


Users may lose access to changes for many reasons, including:

* The User loses direct access to channel
* The User is removed from a role
* A role the user belongs to is revoked access to channel


=== Sync Gateway - Couchbase Lite
Document auto-purge behavior in Sync Gateway replications with Couchbase LIte applications following channel access revocation.

By default, when a user loses access to a channel, the next Couchbase Lite Pull replication auto-purges all documents in the channel from local Couchbase Lite databases (on devices belonging to the user) *unless* they belong to any of the user’s other channels -- see: {cbl-replication--xref--autopurge}.


.{sgw-t} behavior following access revocation
[#tbl-sgw-behavior, cols="^1h,2a,2a", options="header"]
|===

2+|System State
^|Impact on Sync

.>h|Replication Type
^.>h|Access Control on Sync Gateway
^.>h|Expected behavior (`enable_auto_purge=true`)

|Pull only
|User revoked access to channel.

Sync Function includes `requireAccess(revokedChannel)`
|Previously synced documents are auto purged on local

|Push only
|User revoked access to channel. Sync Function includes `requireAccess(revokedChannel)`
|No impact of auto-purge
+
Documents get pushed but are rejected by Sync Gateway

|Push-pull
|User revoked access to channel
+
Sync Function includes 'requireAccess(revokedChannel)'
|Previously synced documents are auto purged on Couchbase Lite.
+
Local changes continue to be  pushed to remote but are rejected by Sync Gateway

|===

Clients may specify pull-filters to override the auto-purge behavior -- see: <<tbl-pull-filters>>.
This ensures backwards compatible with 2.8 clients that use pull filters to prevent auto purge of removed docs.

.Impact of Pull-Filters
[#tbl-pull-filters,cols="^1,2,2"]
|===

.2+.^h|purge_on_removal setting

2+^h|Pull Filter

^h|Not Defined
^h|Defined to filter removals/revoked docs

|disabled
2+a|Doc remains in local database

App notified of “accessRemoved” if a _Documentlistener_ is registered

|enabled (DEFAULT)
a|Doc is auto purged

App notified of “accessRemoved” if _Documentlistener_ registered
a|Doc remains in local database

App notified of “Rejected Rev(403)” if _Documentlistener_ registered

|===

== Inter-Sync Gateway

Document auto-purge behavior in inter-Sync Gateway replications following channel access revocation.

NOTE: Access control policies are only enforced at the remote cluster.

Documents are not auto purged on the active sync gateway even if the user on the passive sync gateway loses channel access.

You can over-ride this behavior using the replicator level option to `purge_on_removal` in REST API.
This causes documents to be auto-purged on the active Sync Gateway if they do not belong to *any* of the replicating user’s footnote:[pass:q,a[The _replicating user_ is the user on the _passive_ sync gateway cluster; the user specified in the replication definition.]] channels.

NOTE: The behavior of the config flag is the *reverse* of that in Couchbase Lite.

If a user subsequently regains access to a lost channel then any previously auto-purged documents still assigned to any of their channels are automatically pulled down by the active Sync Gateway.

If you want to control whether to sync previous auto purged versions of documents (rather than pull down purged documents) then you must also move the documents out of all of the users' channels so they are not synced down again.


.Access Revocation behavior
[#tbl-isgr-pull-behaviors,cols="^1,^1,1,1"]
|===

.2+^.^h|Direction
2+^h|System State
^h|Impact on Sync

h|Active Sync Gateway (Local -- Running as admin user)
h|Passive Sync Gateway (Remote)
^h|Expected behavior when `purge_on_removal=true`

|Pull
|N/A
|User revoked access to channel
|Previously synced documents are auto purged on local

|PUSH
|N/A
|User revoked access to channel
|Previously synced documents are auto purged on local


|PushAndPull
|N/A
|User revoked access to channel +
Sync Function includes `requireAccess(“channel”)`
|When access is revoked on remote, the previously synced documents for User2 are auto-purged on local.

Local changes continue to  be pushed to remote but rejected by remote

|===


// BEGIN -- Page Footer
include::partial$block-related-content-sync.adoc[]
// END -- Page Footer

