= Configuration Overview
:page-layout: article
:page-content: conceptual
:description: How to configure Sync Gateway for secure cloud-to-edge data sync
:keywords: sync, data replication, cloud-to-edge, configuration

include::partial$_std-hdr-sgw.adoc[]

:param-abstract!:
:param-topic-group: configuration
:param-related!:
include::partial$block-abstract.adoc[]


== Introduction

In addition to the established, static configuration method, Sync Gateway 3.x provides for a dynamic, modular, and persistent approach to configuring Sync Gateways.
This approach makes configuration, maintenance and propagation simpler and safer in multi-node, multi-cluster deployments.



== Static Configuration

Sync Gateway's established method of configuration is to use a centralized JSON configuration file to hold all configuration settings -- see: {configuration-schema-static--xref}.

Changes can be made using the {rest-api-admin--xref} but these are not persistent beyond a Sync Gateway restart.

Persistent changes require edits to the central configuration file.


== Dynamic Persistent Configuration

Sync Gateway's dynamic persistent configuration approach
relies on a small bootstrap configuration with dynamic configuration of databases, replications and users being done using the REST API.

In the dynamic persistent configuration approach you will provide:

* A bootstrap configuration file, which contains a core amount of configuration in JSON form.
This defines Sync Gateways run time behavior and static settings.

* A database configuration for each replicated database.
The {configuration-schema-database--xref} defines the required database settings. It is provisioned using the {rest-api-admin-database--xref}.
Changes persist across Sync Gateway restarts.

* An access-control configuration using the {configuration-schema-access-control--xref}, which defines the settings provisioned using the {rest-api-admin-access-control--xref}.
Changes persist across Sync Gateway restarts.

* An inter-Sync Gateway Replication configuration using the {configuration-schema-isgr--xref}, which defines the settings provisioned using the {rest-api-admin-isgr--xref}.
Changes persist across Sync Gateway restarts.




include::partial$block-related-content-api.adoc[]
