= Configuration Overview
:page-layout: article
:page-content: conceptual
:description: How to configure Sync Gateway for secure cloud-to-edge data sync
:keywords: sync, data replication, cloud-to-edge, configuration

include::partial$_std-hdr-sgw.adoc[]

:param-abstract!:
:param-topic-group: configuration
:param-related!:
include::partial$block-abstract.adoc[]

[NOTE]
--
For information on 2.x-style Sync Gateway configuration -- see: {legacy-configuration-properties--xref}.
--


== Introduction

Sync Gateway 3.x provides for a modular and persistent approach to configuring Sync Gateways.
This makes configuration maintenance and propagation simpler and safer in multi-node, multi-cluster deployments.

For information on configuration prior to 3.x -- see: {legacy-configuration-properties--xref}.

Sync Gateway configuration data is held in:

* A JSON configuration file, which defines Sync Gateways run time behavior and static parameter settings

* Specified Couchbase Server buckets, which define dynamic data, including databases and replications.
This configuration is maintained using the REST API.




include::partial$block-related-content-api.adoc[]
