= Import Filter Configuration
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:description: Using Sync Gateway's Admin REST API and the Import Filter function to configure access

:ouroffsetlevel: +1

include::partial$_set_page_context.adoc[]

include::partial$block-caveats.adoc[tags="legacy-config-equivalents"]

== Introduction

Using an import filter will significantly improve efficiency if you're working with large datasets:

* Import filters are defined at the collection level and allow you to retrieve only the relevant documents you need rather than the entire dataset. 
The import filter helps determine which documents can be copied by Sync Gateway. 
It looks at the application's needs and applies these criteria to all future changes.

* By reducing the amount of data that needs to be processed, an import filter will improve the performance of your queries and analysis. 
It's worth noting that Sync Gateway imports all documents by default, so it's generally a good idea to use an import filter unless you have a strong reason not to.


== Function Provision

Use the {rest-api-admin--xref--database-configuration} Admin Rest API endpoint xref:rest_api_admin_static.adoc#post_db-_config[POST /{db}/_config] to provision an import filter for a database using the `application/javascript` mime type.

If you are using legacy configuration then, you need to include it in your configuration file, see: {configuration-properties-legacy--xref--databases-import-filter}.


== Configuration

NOTE: You need Couchbase Lite 3.1+ and Sync Gateway 3.1+ to use `custom` Scopes and Collections. +
If you’re using Capella App Services or Sync Gateway releases that are older than version 3.1, you won’t be able to access `custom` Scopes and Collections. 
To use Couchbase Lite 3.1+ with these older versions, you can use the `default` Collection as a backup option.

[source,JSON]
----
{
  scopes: {
      {scopename...}: {
         collections: {
            {collectionname...}: {
               import_filter: "function(doc) { if (doc.type != 'mobile') { return false; } return true; }",
            }
         }
      }
   },
   // other configuration
}
----

For more information, see xref:configuration-schema-database.adoc#_database[Sync Gateway Configuration Schema].

[cols="2", options="header"]
|===
| Property | Description

| scopename 
| Represents the name of each scope

| collections
| Contains different collections within each scope

| collectionname
| Represents the name of each collection within a scope.

|import_filter
|Used to decide if a document should be imported. It checks the type property of the document. If it is not 'mobile', the function returns false, otherwise, it returns true.

|===

[source,bash]
----
include::{example-cfg}[tag="import-filter-config"]
----

--

+
Legacy::
+
--
[source,json]
----
include::{example-cfg}[tag="import-filter-config-legacy"]
----

--
=====
====

== Upsert Import Filter Function

----

https:://{sgw-uri}/{db}/_config/import_filter

----

include::partial$static_restapi/admin/index.adoc[tags=put_keyspace-_config-import_filter-description,leveloffset=-2]

See: {import-filter--xref} for more.


== Parameters
include::partial$static_restapi/admin/index.adoc[tags=put_keyspace-_config-import_filter-parameters,leveloffset=-2]


== Responses
include::partial$static_restapi/admin/index.adoc[tags=put_keyspace-_config-import_filter-responses,leveloffset=-2]


[#_Import_filter]
== Schema

This section shows Sync Gateway's import control configuration settings in schema format for convenience in constructing JSON models for use in the Admin REST API.

The configuration settings described here are provisioned through {rest-api-admin--xref--access-control} endpoints.

include::partial$static_restapi/admin/definitions.adoc[tags=Import_filter_model]

// BEGIN -- DO NOT EDIT
include::partial$block-related-content-api.adoc[]

// END -- DO NOT EDIT
