= Configuration File
:idprefix:
:idseparator: -

A configuration file determines the runtime behavior of Sync Gateway, including server configuration and the database or set of databases with which a Sync Gateway instance can interact.

Using a configuration file is the recommended approach for configuring Sync Gateway, because you can provide values for all configuration properties and you can define configurations for multiple Couchbase Server databases.

When specifying a configuration file, the format to run Sync Gateway is:

[source]
----
$ sync_gateway sync-gateway-config.json
----

Configuration files have one syntactic feature that is not standard JSON: any text between back ticks (`) is treated as a string, even if it spans multiple lines or contains double-quotes.
This makes it easy to embed JavaScript code, such as the sync and filter functions.

== Configuration Reference

[subs="attributes+"]
++++
<link rel="stylesheet" type="text/css" href="https://couchbase-docs.s3.amazonaws.com/assets/json-config-ui/json-config-ui-vnext.css">

<div id="swagger-ui"></div>
<div id="json-config-ui"></div>
<script src="https://couchbase-docs.s3.amazonaws.com/assets/json-config-ui/json-config-ui-bundle-vnext.js"></script>
<script>
	const ui = JSONConfigUIBundle({
		dom_id: '#json-config-ui',
		specs: [{version: {version}, url: "https://couchbase-docs.s3.amazonaws.com/mobile/{version}/configs/sg.json?v=1"}],
		current: {version}
	});
	window.ui = ui
</script>
++++
