= Data Model
:description: Couchbase Sync Gateway - data model for synchronization

:xref-sdk-nodejs-pg-start: xref:nodejs-sdk:hello-world:start-using-sdk.adoc[Node.js Server SDK]
:xref-sdk-java-encryption: xref:java-sdk:concept-docs:encryption.adoc#format[field encryption format]

include::partial$_std-hdr-sgw.adoc[]

:param-attributes!:
:param-related:  {revisions--xref} | {what-are-tombstones--xref}
include::partial$block-abstract.adoc[]

== Introduction
The guidance and constraints documented here relate to the design of data buckets and documents that you require, or may potentially require, to replicate using sync gateway functionality.
They do not necessarily align with constraints on the local storage and use of such documents.

== Property Naming

What to avoid::
You should avoid designing user property names prefixed with an underscore character (`+_+`, ASCII `&#095`).

Why it's an issue::
The underscore character (`+_+`) is a *reserved prefix* for _Document_ system properties, for example: the document's identifier (`+_id+`) and revision property (`+_rev+`).
+
Any document which does contain user properties with a leading underscore will be rejected by Sync Gateway -- see <<error-code>> for the error details.
+
[#error-code]
.Property prefix error message
====
[source,text]
----
"{"error":"Bad Request","reason":"user defined top level properties beginning with '_' are not allowed in document body"}"
----
====

Where it applies::
This rule applies to writes performed through:
+
* Couchbase Lite SDKs
* Sync Gateway REST APIs
* Couchbase Server SDKs when {sgw--xref}{sgw-pg-shared-bucket-access}[shared bucket access] is enabled.

When you might encounter the error::
You are especially likely to encounter the error in the following deployment situations:

* In Mobile-to-Web Data Sync with Field-level Encryption enabled, because the rule conflicts with the default {xref-sdk-java-encryption}
* In Mobile-to-Web Data Sync with {xref-sdk-nodejs-pg-start} and http://ottomanjs.com/[Ottoman.js] (the Node.js ODM for Couchbase), where the rule conflicts with the `+_type+` property that is automatically added by _Ottoman.js_.
+
A suggested workaround in this scenario is to fork the _Ottoman.js_ library, perform a search-replace for the `+_type+` property and replace it without a leading underscore.

How to avoid the error::
You should change any top-level user properties that have a key with a leading underscore , by either:

* Renaming them to remove the underscore, or,
* Wrapping them inside another object with a key that doesn't have a leading underscore.


// == Buckets and Databases



== Document Structure

Couchbase's unit of data is a document, this is the NOSQL equivalent of a row or record.

Documents are stored as a key-value pair, which comprises a unique and immutable key, the _Id_, and a value representing the users' data (a JSON-object or binary blob).

=== Key

The document key, the _Id_, is:

* A UTF-8 string with no spaces, although it may contain special characters, such as (, %, /, ", and _
* No longer than 250 bytes
* Unique within the bucket
* Automatically generated (as a UUID) or be set by the user or application when saved
* Immutable; that is, once saved the _Id_ cannot be changed.

=== Value
The document value is either:

* A JSON value, termed a _Document_.
+
This JSON object is itself collection of key/value pairs, where the values may be numbers, strings, arrays or even nested objects themselves.
As a result documents can represent highly-complex data structures in a readily parsable and self-organizing manner.
* a binary object (also known as a _blob_ or _attachment_)
+
These attachments provide a means to store large media files or any other non-textual data.
Couchbase Lite supports attachments of unlimited size, although the Sync Gateway currently imposes a 20MB limit for attachments synced to it.

== Document Attributes
Each _Document_ has the following attributes:

* A document ID
* A current revision ID (which changes every time the document is updated)
* A history of past revision IDs (usually linear, but will form a branching tree if the document has or has had conflicts)
* A body in the form of a JSON object, i.e. a set of key/value pairs
* Zero or more named binary attachments

//For more on document and data basics see: xref:server:learn:data/data.adoc[]

== Document Change History

{cbl} tracks the change history of every document as a series of revisions, like version control systems such as Git or Subversion.
Its main purpose being to enable the replicator to determine the data to sync and any conflicts arising.

Each document change is assigned a unique revision ID. The IDs of past revisions are available. The content of past revisions may be available if the revision was created locally and the database has not yet been compacted.




include::partial$block-related-content-data.adoc[]