= Data Modeling
:description: Couchbase Sync Gateway - data modeling guidelines for synchronization

:xref-sdk-nodejs-pg-start: xref:nodejs-sdk:hello-world:start-using-sdk.adoc[Node.js Server SDK]
:xref-sdk-java-encryption: xref:java-sdk:concept-docs:encryption.adoc#format[field encryption format]

include::partial$_std-hdr-sgw.adoc[]

:param-attributes!:
:param-related: {xref-sgw-pg-concept-fundamentals-data} | {xref-sgw-pg-concept-fundamentals-data-tombstones}
include::partial$block-abstract.adoc[]

== Introduction
The guidance and constraints documented here relate to the design of data buckets and documents that you require, or may potentially require, to replicate using sync gateway functionality.
They do not necessarily align with constraints on the local storage and use of such documents.

== Property Prefixes
What to avoid::
You should avoid designing user properties with names that begin with the underscore character (`+_+`, ASCII `&#095`).

Why it's an isssue::
The underscore character (`+_+`) is a *reserved prefix* for _Document_ system properties, for example: the document's identifier (`+_id+`) and revision property (`+_rev+`).
+
Any document which does contain user properties with a leading underscore will be rejected by Sync Gateway -- see <<error-code>> for the error details.
+
[#error-code]
.Property prefix error message
====
[source,text]
----
"{"error":"Bad Request","reason":"user defined top level properties beginning with '_' are not allowed in document body"}"
----
====

Where it applies::
This rule applies to writes performed through:
+
* Couchbase Lite SDKs
* Sync Gateway REST APIs
* Couchbase Server SDKs when {xref-pfx-sgw}{sgw-pg-shared-bucket-access}[shared bucket access] is enabled.

When you might encounter the error::
You are especially likely to encounter the error in the following deployment situations:

* In Mobile-to-Web Data Sync with Field-level Encryption enabled, because the rule conflicts with the default {xref-sdk-java-encryption}
* In Mobile-to-Web Data Sync with {xref-sdk-nodejs-pg-start} and http://ottomanjs.com/[Ottoman.js] (the Node.js ODM for Couchbase), where the rule conflicts with the `+_type+` property that is automatically added by _Ottoman.js_.
+
A suggested workaround in this scenario is to fork the _Ottoman.js_ library, perform a search-replace for the `+_type+` property and replace it without a leading underscore.

How to avoid the error::
You should change any top-level user properties that have a key with a leading underscore , by either:

* Renaming them to remove the underscore, or,
* Wrapping them inside another object with a key that doesn't have a leading underscore.

include::partial$block-related-content-data.adoc[]