= Deployment Considerations
:url-curl: https://curl.haxx.se/
:url-httpie: https://github.com/jakubroztocil/httpie

The following guide describes a set of recommended best practices for a production deployment of Couchbase Mobile.

== Sync Gateway Security

*Authentication*

In a Couchbase Mobile production deployment, administrators typically perform operations on the Admin REST API.
If Sync Gateway is deployed on an internal network, you can bind the xref:config-properties.adoc#server[adminInterface] of Sync Gateway to the internal network.
In this case, the firewall should also be configured to allow external connections to the public xref:config-properties.adoc#server[interface] port.

To access the Admin REST API from an entirely different network or from a remote desktop we recommend to use https://whatbox.ca/wiki/SSH_Tunneling[SSH tunneling].

*Authorization*

In addition to the Admin REST API, a user can be assigned to a role with additional privileges.
The role and the user assigned to it can be created in the configuration file.
Then, the Sync Function's xref:sync-function-api.adoc#requirerole-rolename[requireRole()] method can be used to allow certain operations only if the user has that role.

*Data Model Validation*

In a NoSQL database, it is the application's responsibility to ensure that the documents are created in accordance with the data model adopted throughout the system.
As an additional check, the Sync Function's xref:sync-function-api.adoc#throw[throw()] method can be used to reject documents that do not follow the pre-defined data model.

*HTTPS*

You can run Sync Gateway behind a reverse proxy, such as NGINX, which supports HTTPS connections and route internal traffic to Sync Gateway over HTTP.
The advantage of this approach is that NGINX can proxy both HTTP and HTTPS connections to a single Sync Gateway instance.

Alternatively, Sync Gateway can be xref:configuring-ssl.adoc[configured] to only allow secure HTTPS connections, if you want to support both HTTP and HTTPS connections you will need to run two separate instances of Sync Gateway.

== Couchbase Server Auth

There are two methods to securely connect a Sync Gateway instance to a Couchbase Server cluster.
Each method is discussed below in more detail.

=== Username and Password

The username and password of the RBAC user are specified in the Sync Gateway configuration file.
This method is used in the getting started xref:getting-started.adoc#start-sync-gateway[section].

=== X.509 Certificates

Sync Gateway 2.1 adds the ability to use X.509 certificates to authenticate against Couchbase Server 5.5 or higher.
This functionality can be used instead or in addition to the existing authentication method which is to specify a username and password in the configuration file.

To use x.509 authentication with Sync Gateway, you must first run through the following steps.

. Create x.509 certificates for Couchbase Server.
See xref:server:manage:manage-security/configure-server-certificates.adoc#generating-a-certificate[Generating a Certificate].
. Configure each Couchbase Server node in the cluster.
 See xref:server:manage:manage-security/configure-server-certificates.adoc#installing-a-certificate[Installing a Certificate].
. Enable Client Certificate Authentication.
See xref:server:manage:manage-security/configure-server-certificates.adoc#configuring-a-certificate[Configuring a Certificate].

After completing step 3, you will have multiple files generated in the current directory.
From the generated files, you must copy `ca.pem`, `chain.pem` and `pkey.key` to the machine where Sync Gateway is running.

To connect successfully, you must also ensure the following:

. A bucket named *travel-sample* exists.
See xref:getting-started.adoc#configure-couchbase-server[instructions].
. The RBAC user with the name *travel-sample* exists has access permissions to the bucket.
See xref:getting-started.adoc#configure-couchbase-server[instructions].

Then, x.509 can be enabled on Sync Gateway by specifying the absolute or relative path to each of those files in the configuration file.

[source,json]
----
include::{examplesdir}/x509-config.json[]
----

If the connection is successful, you should see the following in the logs.

[source,text]
----
[INF] Starting admin server on 127.0.0.1:4985
[INF] Starting server on :4984 ...
[INF] Establishing TLS connection for DCP to destination 192.168.33.14:11207
[INF] Establishing TLS connection for DCP to destination 192.168.33.10:11207
----

If Sync Gateway cannot connect, you may refer to the xref:server:manage:manage-security/handle-certificate-errors.adoc#cluster-certificate-errors[Cluster Certificate Errors] table.

More detail on the configuration properties for x.509 authentication can be found below.

* xref:config-properties.adoc#databases-foo_db-certpath[databases.$db.certpath]
* xref:config-properties.adoc#databases-foo_db-keypath[databases.$db.keypath]
* xref:config-properties.adoc#databases-foo_db-cacertpath[databases.$db.cacertpath]

If the **username**/**password** properties are also specified in the configuration file then Sync Gateway will use password-based authentication and also include the client certificate in the TLS handshake.

== Log Rotation

=== Built-in log rotation

By default, Sync Gateway outputs the logs to standard out with the "HTTP" log key and can also output logs to a file.
Prior to 1.4, the two main configuration options were `log` and `logFilePath` at the root of the configuration file.

[source,javascript]
----
{
    "log": ["*"],
    "logFilePath": "/var/log/sync_gateway/sglogfile.log"
}
----

In Couchbase Mobile 1.4, Sync Gateway can now be configured to perform log rotation in order to minimize disk space usage.

==== Log rotation configuration

The log rotation configuration is specified under the `logging` key.
The following example demonstrates where the log rotation properties reside in the configuration file.

[source,javascript]
----
{
  "logging": {
    "default": {
      "logFilePath": "/var/log/sync_gateway/sglogfile.log",
      "logKeys": ["*"],
      "logLevel": "debug",
      "rotation": {
        "maxsize": 1,
        "maxage": 30,
        "maxbackups": 2,
        "localtime": true
      }
    }
  },
  "databases": {
    "db": {
      "server": "walrus:data",
      "bucket": "default",
      "users": {"GUEST": {"disabled": false,"admin_channels": ["*"]}}
    }
  }
}
----

As shown above, the `logging` property must contain a single named logging appender called `default`.
Note that if the "logging" property is specified, it will override the top level `log` and `logFilePath` properties.

The descriptions and default values for each logging property can be found on the xref:config-properties.adoc[Sync Gateway configuration] page.

==== Example Output

If Sync Gateway is running with the configuration shown above, after a total of 3.5 MB of log data, the contents of the `/var/log/sync_gateway` directory would have 3 files because `maxsize` is set to 1 MB.

[source,bash]
----
/var/log/sync_gateway
├── sglogfile.log
├── sglogfile-2017-01-25T23-35-23.671.log
└── sglogfile-2017-01-25T22-25-39.662.log
----

==== Windows Configuration

On MS Windows `logFilePath` supports the following path formats.

[source,javascript]
----
"C:/var/tmp/sglogfile.log"
`C:\var\tmp\sglogfile.log`
`/var/tmp/sglogfile.log`
"/var/tmp/sglogfile.log"
----

Log rotation will not work if `logFilePath` is set to the path below as it is reserved for use by the Sync Gateway Windows service wrapper.

[source,bash]
----
C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs\sync_gateway_error.log
----

==== Deprecation notice

The current proposal is to remove the top level `log` and `logFilePath` properties in Sync Gateway 2.0.
For users that want to migrate to the new logging config to write to a log file but do not need log rotation they should use a default logger similar to the following:

[source,javascript]
----
{
    "logging": {
        "default": {
            "logFilePath": "/var/log/sync_gateway/sglogfile.log",
            "logKeys": ["*"],
            "logLevel": "debug"
        }
    }
}
----

=== OS log rotation

In production environments it is common to rotate log files to prevent them from taking too much disk space, and to support log file archival.

By default Sync gateway will write log statements to stderr, normally stderr is redirected to a log file by starting Sync Gateway with a command similar to the following:

[source,bash]
----
sync_gateway sync_gateway.json 2>> sg_error.log
----

On Linux the logrotate tool can be used to monitor log files and rotate them at fixed time intervals or when they reach a certain size.
Below is an example of a logrotate configuration that will rotate the Sync Gateway log file once a day or if it reaches 10M in size.

[source]
----
/home/sync_gateway/logs/*.log {
    daily
    rotate 1
    size 10M
    delaycompress
    compress
    notifempty
    missingok
----

The log rotation is achieved by renaming the log file with an appended timestamp.
The idea is that Sync Gateway should recreate the default log file and start writing to it again.
The problem is Sync Gateway will follow the renamed file and keep writing to it until Sync gateway is restarted.
By adding the copy truncate option to the logrotate configuration, the log file will be rotated by making a copy of the log file, and then truncating the original log file to zero bytes.

[source]
----
/home/sync_gateway/logs/*.log {
    daily
    rotate 1
    size 10M
    copytruncate
    delaycompress
    compress
    notifempty
    missingok
}
----

Using this approach there is a possibility of loosing log entries between the copy and the truncate, on a busy Sync Gateway instance or when verbose logging is configured the number of lost entries could be large.

In Sync Gateway 1.1.0 a new configuration option has been added that gives Sync Gateway control over the log file rather than relying on *stderr*.
To use this option call Sync Gateway as follows:

[source,bash]
----
sync_gateway -logFilePath=sg_error.log sync_gateway.json
----

The *logFilePath* property can also be set in the configuration file at the xref:config-properties.adoc#server-configuration[server level].

If the option is not used then Sync Gateway uses the existing stderr logging behavior.
When the option is passed Sync Gateway will attempt to open and write to a log file at the path provided.
If a Sync Gateway process is sent the `SIGHUP` signal it will close the open log file and then reopen it, on Linux the `SIGHUP` signal can be manually sent using the following command:

[source,bash]
----
pkill -HUP sync_gateway
----

This command can be added to the logrotate configuration using the 'postrotate' option:

[source]
----
/home/sync_gateway/logs/*.log {
    daily
    rotate 1
    size 10M
    delaycompress
    compress
    notifempty
    missingok
    postrotate
        /usr/bin/pkill -HUP sync_gateway > /dev/null
    endscript
}
----

After renaming the log file logrotate will send the `SIGHUP` signal to the `sync_gateway` process, Sync Gateway will close the existing log file and open a new file at the original path, no log entries will be lost.