= Deployment Considerations
:url-curl: https://curl.haxx.se/
:url-httpie: https://github.com/jakubroztocil/httpie

The following guide describes a set of recommended best practices for a production deployment of Couchbase Mobile.

== Sync Gateway Security

*Authentication*

In a Couchbase Mobile production deployment, administrators typically perform operations on the Admin REST API.
If Sync Gateway is deployed on an internal network, you can bind the xref:config-properties.adoc#server[adminInterface] of Sync Gateway to the internal network.
In this case, the firewall should also be configured to allow external connections to the public xref:config-properties.adoc#server[interface] port.

To access the Admin REST API from an entirely different network or from a remote desktop we recommend to use https://whatbox.ca/wiki/SSH_Tunneling[SSH tunneling].

*Authorization*

In addition to the Admin REST API, a user can be assigned to a role with additional privileges.
The role and the user assigned to it can be created in the configuration file.
Then, the Sync Function's xref:sync-function-api.adoc#requirerole-rolename[requireRole()] method can be used to allow certain operations only if the user has that role.

*Data Model Validation*

In a NoSQL database, it is the application's responsibility to ensure that the documents are created in accordance with the data model adopted throughout the system.
As an additional check, the Sync Function's xref:sync-function-api.adoc#throw[throw()] method can be used to reject documents that do not follow the pre-defined data model.

*HTTPS*

You can run Sync Gateway behind a reverse proxy, such as NGINX, which supports HTTPS connections and route internal traffic to Sync Gateway over HTTP.
The advantage of this approach is that NGINX can proxy both HTTP and HTTPS connections to a single Sync Gateway instance.

Alternatively, Sync Gateway can be xref:configuring-ssl.adoc[configured] to only allow secure HTTPS connections, if you want to support both HTTP and HTTPS connections you will need to run two separate instances of Sync Gateway.

== Couchbase Server Auth

There are two methods to securely connect a Sync Gateway instance to a Couchbase Server cluster.
Each method is discussed below in more detail.

=== Username and Password

The username and password of the RBAC user are specified in the Sync Gateway configuration file.
This method is used in the getting started xref:getting-started.adoc#start-sync-gateway[section].

=== X.509 Certificates

Sync Gateway 2.1 adds the ability to use X.509 certificates to authenticate against Couchbase Server 5.5 or higher.
This functionality can be used instead or in addition to the existing authentication method which is to specify a username and password in the configuration file.

To use x.509 authentication with Sync Gateway, you must first run through the following steps.

. Create x.509 certificates for Couchbase Server.
See xref:server:manage:manage-security/configure-server-certificates.adoc#configure-server-side-certificates[instructions steps 1 - 10].
. Configure each Couchbase Server node in the cluster.
 See xref:server:manage:manage-security/configure-server-certificates.adoc#configure-server-side-certificates[instructions steps 11 - 12].
. Enable Client Certificate Authentication.
See xref:server:manage:manage-security/configure-server-certificates.adoc#configure-server-side-certificates[instructions step 13].

After completing step 3, you will have multiple files generated in the current directory.
From the generated files, you must copy `ca.pem`, `chain.pem` and `pkey.key` to the machine where Sync Gateway is running.

To connect successfully, you must also ensure the following:

. A bucket named *travel-sample* exists.
See xref:getting-started.adoc#configure-couchbase-server[instructions].
. The RBAC user with the name *travel-sample* exists has access permissions to the bucket.
See xref:getting-started.adoc#configure-couchbase-server[instructions].

Then, x.509 can be enabled on Sync Gateway by specifying the absolute or relative path to each of those files in the configuration file.

[source,json]
----
include::{examplesdir}/x509-config.json[]
----

More detail on the configuration properties for x.509 authentication can be found below.

* xref:config-properties.adoc#databases-foo_db-certpath[databases.$db.certpath]
* xref:config-properties.adoc#databases-foo_db-keypath[databases.$db.keypath]
* xref:config-properties.adoc#databases-foo_db-cacertpath[databases.$db.cacertpath]

If the **username**/**password** properties are also specified in the configuration file then Sync Gateway will use password-based authentication and also include the client certificate in the TLS handshake.