= REST API Access
:page-aliases: start/get-started-access-rest-api.adoc
:page-layout: article
:page-content: Reference
:description: Sync Gateway REST API Access

include::partial$_std-hdr-sgw.adoc[]

:param-abstract: Shows how to access Sync Gateway APIs
:param-related: {rest-api--xref}  |  {rest-api-admin--xref}  |  {rest-api-metrics--xref}  |  {rest-api-client-app--xref}
:topic-group: REST API
include::partial$block-abstract.adoc[]

:xref--pfx: {sgw--xref}:

Sync Gateway REST APIs are accessed on different TCP ports.
This makes it easy to expose the Public REST API and Metrics REST API (if activated) to endpoints while keeping the Admin REST API secure behind your firewall.

If you want to change the ports, you can do that in the configuration file, so:

* To change the Public REST API port, set the `interface` property in the configuration file.
* To change the Metric REST API port, set the `metricsInterface` property in the configuration file.
* To change the Admin REST API port, set the `adminInterface` property in the configuration file.

The value of the property is a string consisting of a colon followed by a port number (for example, `:4985`).
You can also include a host name or numeric IP address before the colon to bind only to that network interface.

As a useful special case, the IP address 127.0.0.1 binds to the loopback interface, making the port unreachable from any other host.
This is the default setting for the admin interface.

.Network Port Requirements
include::partial$sgw-network-port-reqs.adoc[]

include::partial$block-related-content-api.adoc[]