= Verify a Sync Gateway Install
:page-aliases: start/get-started-verify-install.adoc
:Description: Configure and verify your Sync Gateway installation and securely sync enterprise data from cloud to edge
:page-type: procedural

include::partial$_std-hdr-sgw.adoc[]
:xref--pfx: {sgw--xref}:
:xref-sgw-bmk-logging-console: xref:{sgw-pg-logging}#lbl-console-logs[Console Logs]
:xref-sgw-bmk-logging-console-redirect: xref:{sgw-pg-logging}#lbl-log-redirect[Redirect Console Logs]
:xref-sgw-bmk-logging-continuous: xref:{sgw-pg-logging}#lbl-continuous-logs[Continuous Logging]

:topic-group: Start Here!
:param-related: {get-started-prepare--xref}  |  {get-started-install--xref}
:param-abstract: Here we will check that you can connect to your Sync Gateway
include::partial$block-abstract.adoc[]

.Preparatory Steps
NOTE: Before following the steps in this topic you must have read, and acted-upon, the information and steps in {get-started-prepare--xref} and {get-started-install--xref}.

== Step 1: Create a configuration file

To configure Sync Gateway to connect to a Couchbase Server instance, create a new file called *sync-gateway-config.json* and add the content shown in <<sample-cfg>>.

[#sample-cfg]
.Sample Config
====
[source,json]
----
include::{example-cfg}[tag="getting-started-config"]
----

Configuration Properties::
<.> The username of the RBAC user that you created on the Couchbase Server Admin Console -- see xref:{sgw-pg-get-started-prepare}#configure-server[Configure Server for Sync Gateway]
<.> The password of the user that you created on the Couchbase Server Admin Console.
<.> The xref:{sgw-pg-shared-bucket-access}[enable_shared_bucket_access] feature allows Couchbase Server SDKs to also perform operations on this bucket.
<.> `num_index_replicas` is the number of index replicas stored in Couchbase Server -- see {xref-sgw-pg-indexing}. +
*NOTE:* If you're running a single Couchbase Server node for development purposes the `num_index_replicas` must be set to `0`.
<.> Define your logging requirements. +
Here we set general diagnostic console logs on.
====

== Step 2: Start Sync Gateway

Start Sync Gateway from the command line -- see {command-line-options--xref}, or if Sync Gateway is running in a service replace the configuration file and restart the service.

[#start-sgw]
.Use Command Line to Start Sync Gateway
====
[source,bash]
----
~/Downloads/couchbase-sync-gateway/bin/sync_gateway ~/path/to/sync-gateway-config.json // <.>
----

<.> If you are using a Couchbase Lite application, then run this command where that is installed.

====

== Step 3: Connect to Sync Gateway
TIP: You can use {xref-sgw-bmk-logging-console} to aid diagnosis of connection issues

. With Sync Gateway started (see: <<start-sgw>>), point your browser to the Sync Gateway url, typically on port 4984, but this can be changed -- see: {get-started-access-rest-api--xref}.
+
So, for example:
+
[source, console]
----
http://localhost:4984
----

. Check that you receive a response similar to this:
+
[source, console]
----
{"couchdb":"Welcome","vendor":{"name":"Couchbase Sync Gateway","version":"2.8"},"version":"Couchbase Sync Gateway/2.8.0(376;e2e7d42) EE"}
----
+
If there are issues then check the {xref-sgw-bmk-logging-console} for more information.
Where necessary you can redirect console output to a file -- see: {xref-sgw-bmk-logging-console-redirect}.

TIP: If Sync Gateway is behind a load balancer then check the websockets configuration -- see {xref-sgw-pg-load-balancer}.

== Step 4: Sync Changes
To verify that documents have been replicated, you can:

* Monitor the Sync Gateway sequence number returned by the database endpoint (xref:{rest-api--page}#/database/get\__db__[GET /{tkn-db}/]).
The sequence number increments for every change that happens on the Sync Gateway database.
* Query a document by ID on the Sync Gateway REST API (xref:{rest-api--page}#/document/get\__db___doc_[GET /{tkn-db}/{id}]) -- see: {get-started-access-rest-api--xref}
* Query a document from the Query Workbench on the Couchbase Server Console.

include::partial$block-related-content-deploy.adoc[]
