= Glossary

Automatic conflict resolution::
The process by which conflicts are automatically resolved by the system.
Optional feature in xref:couchbase-lite::swift.adoc#handling-conflicts[Couchbase Lite 2.0 and above].

No conflicts mode::
The process by which write operations that would result in a conflict are rejected by the system.
Optional feature in xref:couchbase-lite::swift.adoc#handling-conflicts[Couchbase Lite 2.0 and above] and xref:config-properties.adoc#databases-foo_db-allow_conflicts[Sync Gateway 2.0 and above].

Mobile Tombstone::
A tombstone is the record of a deleted item.
Tombstones are created to allow all devices to see that a document has been deleted - particularly in the case of devices that may not be online continuously and therefore not syncing regularly.
The `_deleted: true` property is used internally to identify tombstones.
+
[source,json]
----
{
  "_deleted": true,
  "_id": "foobar",
  "_rev": "3-db962c6d93c3f1720cc7d3b6e50ac9df"
}
----
Mentioned in:
* xref:managing-tombstones.adoc[Managing Tombstones]
* xref:shared-bucket-access.adoc#metadata-purge-interval[Metadata Purge Interval]
* xref:config-properties.adoc#databases-foo_db-enable_shared_bucket_access[$dbname.enable_shared_bucket_access]
* xref:server:learn:buckets-memory-and-storage/storage.adoc#tombstones[Server Tombstones]
