= Glossary
:page-aliases: sgw-glossary, refer/refer-sgw-glossary.adoc
:page-partial:
:page-layout: article
:page-status:
:page-edition:
:page-role: -toc
:description: Sync Gateway Glossary of Terms
:keywords: edge nosql api synchronization replication
:page-content-type: reference
// End of Page Definition Statements

include::partial$_std-hdr-sgw.adoc[]
include::partial$block-authors-notes.adoc[tag=wip]
:topic-group: {tg-ref-info}
include::partial$block-abstract.adoc[]

// Glosary entry name tag format:
//  {component} = sgw-
//  {namespace} = eg. access-control (acc) replication (repl), api, conflicts (conf), indexing (ndx) etc
//  {sub-space} = eg. user, document, role, channel, sync
//  {name} = free-from

:goto-index: Back to <<index>>


[[index]]
== Index
[.pane__frame--blue]
<<A>>  |  <<B>>  |  <<C>>  |  <<D>>  |  <<E>>  |  <<F>>  |  <<G>>  |  <<H>>  |  <<I>>  |  <<J>>  |  <<K>>  |  <<L>>  |  <<M>>  |  <<N>>  |  <<O>>  |  <<P>>  |  <<Q>>  |  <<R>>  |  <<S>>  |  <<T>>  |  <<U>>  |  <<V>>  |  <<W>>  |  <<X>>  |  <<Y>>  |  <<Z>>

== A

[[active-replicator]]Active replicator::
// tag::sgw-icr-active-replicator-full[]
// tag::sgw-icr-active-replicator[]
The term _active replicator_, refers to the Sync Gateway endpoint that initiates the replication connection.
That is, it s the Sync Gateway where the replicators are configured and from which the changes are pushed.
// end::sgw-icr-active-replicator[]
+
* _Synonym(s)_: active sync gateway
* _SGW Component_: Replication
* _Related Term(s)_: <<passive-replicator, Passive replicator>>
* _Read More_: {xref-sgw-pg-icr-overview}
// end::sgw-icr-active-replicator-full[]

// tag::sgw-icr-active-sgnode-full[]
// tag::sgw-icr-active-sgnode[]
[[active-sgnode]]Active Sync Gateway node::
The term _active Sync Gateway node_, refers to Sync Gateway nodes with incoming writes; these may be from Couchbase Lite clients, the REST API, or through the Couchbase Server.
// end::sgw-icr-active-sgnode[]
+
* _SGW Component_: Replication
// * _Related Term(s)_:
// * _Read More_:
// end::sgw-icr-active-sgnode-full[]


[[adhoc-replication]]Adhoc Replication::
+
--
// tag::sgw-icr-adhoc-replication-full[]
// tag::sgw-icr-adhoc-replication-def[]
// tag::sgw-icr-adhoc-replication[]
The term _adhoc replication_ refers to transient, one-shot, replications that run once and are removed when they stop.
They are initialized using the Admin REST API.
They do not survive Sync Gateway restarts.
// end::sgw-icr-adhoc-replication[]

Ad hoc replications are useful when it is necessary to do one off replication or for troubleshooting.

Other useful use cases include:

* Starting a replication on-demand, for instance a replication that needs to be scheduled to be run at midnight every Thursday. +
In this case, it is likely that there is an automation script that schedules the adhoc replication on a predefined schedule.
* Deploying an emergency one-time update that needs to be pushed out to all edge clusters from primary data clusters.
// end::sgw-icr-adhoc-replication-def[]

Context:

* _Synonym(s)_: transient replication
* _Related Term(s)_:
** <<persistent-replication, Persistent replication>>
** <<continuous-replication, Continuous replication>>
* _SGW Component_: Inter-Sync Gateway Replication
* _Read More_: {xref-sgw-pg-icr-overview}
* _Related Config Elements_: {legacy-configuration-properties--xref--db-rep-adhoc}  |  {legacy-configuration-properties--xref--db-rep-continuous}
// end::sgw-icr-adhoc-replication-full[]
--

[[auto-conflict-resolution]]Automatic conflict resolution::
+
--
include::{concepts}rep-auto-conflict-resolution.adoc[]
--

[[auto-conflict-resolution-policy]]Automatic conflict resolution policy::
+
--
include::{concepts}rep-auto-conflict-resolution-policy.adoc[]
--

{goto-index}

== C

// tag::replication-checkpoint-full[]
[[checkpoint]]Checkpoint::
// tag::replication-checkpoint-summary[]
A _Checkpoint_, in _Couchbase Mobile_ terms, is a “save state” on a replicator, used to enable a restart at the last success-point in the event of a failure during a replication.
+

// end::replication-checkpoint-summary[]
The checkpoint itself is a (meta)document that describes how far in the replication process a given replicator has progressed.
+
Note that two {glos-term-checkpoints} are saved for every replication; one local and one remote.
+
The checkpoint documents are compared at the beginning of every replication.
If they do not agree, then it indicates a severe error during the last run, and the replication is forced to restart from the beginning.
// end::replication-checkpoint-full[]


// tag::conflict-resolver-policies-full[]
[[conflict-resolver-policies]]Conflict Resolver Policies::
// tag::conflict-resolver-policies-summary[]
Inter-Sync Gateway replication provides several predefined conflict resolver policies, which you can choose to apply.
These include: `default; `localWins`, `remoteWins`; and `custom`.
// end::conflict-resolver-policies-summary[]
+
--
// tag::conflict-resolver-policies-body[]
Each conflict resolver policy applies a different strategy:

Default::
* Always applies Sync Gateway's <<auto-conflict-resolution-policy>>

* Configured using: `"conflict_resolution_type": "default"`

Local Wins::
* Always considers the local change the winner.
* Configured using: `"conflict_resolution_type": "localWins"`

Remote Wins::
* Always considers the remote change the winner.
* Configured using: `"conflict_resolution_type": "remoteWins"`

Custom::
+
NOTE: {enterprise} Only

+
Applies the policy defined in the function provided by the `custom_conflict_resolver` parameter.
+
See: <<custom-conflict-resolver>>

--
// end::conflict-resolver-policies-body[]
// end::conflict-resolver-policies-full[]


// tag::custom-conflict-resolver[]
[[custom-conflict-resolver]]Custom conflict resolver::
+
--
The custom_conflict_resolver property specifies a Javascript function used to resolve conflicting changes.

This is an {enterprise} only feature and is configured like this:

[source: json]
----
"conflict_resolution_type": "custom",
"custom_conflict_resolver":`
  function(conflict) {
    // Always resolve in favor of remote
    console.log("full remoteDoc doc: "+JSON.stringify(conflict.RemoteDocument));
    return conflict.RemoteDocument;
  }`
----

Configuration property: {legacy-configuration-properties--xref--db-rep-resolver}
--
// end::custom-conflict-resolver[]


[[continuous]][[rep-continuous]]Continuous replication mode::
// tag::glos-term-rep-continuous[]
A _continuous_ replication will sit in running state awaiting document changes to process in accordance to its _replication definition_.
// end::glos-term-rep-continuous[]

[[cloud-to-edge]]Cloud-to-Edge Sync::
// tag::sgw-cloud-to-edge-full[]
// tag::sgw-cloud-to-edge-def[]
// tag::sgw-cloud-to-edge[]
The term _cloud-to-edge_ refers to the multi-cloud deployment mode commonly know as _ship-to-shore_ or _hub-and-spoke_.
These typically involve a large number of edge clusters (mobiles,, tablets IoT) connected to one or more cloud data centers.
// end::sgw-cloud-to-edge[]
+
Each edge can operate autonomously without network connectivity to the cloud data centers.
The _edge_ could be, for example a group of retail stores, ships at sea or distribution hubs.
The number of edges can range from a few hundred to several thousand.
// end::sgw-cloud-to-edge-def[]
+
* _Synonym(s)_: ship-to-shore sync, hub-and-spoke sync
* _SGW Component_: Inter-Sync{nbsp}Gateway Replication
* _Related Term(s)_:
* _Read More_: {xref-sgw-pg-icr-overview}
// end::sgw-cloud-to-edge-full[]

[[cloud-to-edge]][[cloud-to-edge-synchronization]][[cloud-to-edge-sync]]Cloud-to-Edge synchronization::
// tag::sgw-cloud-to-edge-sync-full[]
// tag::sgw-cloud-to-edge-sync-def[]
// tag::sgw-cloud-to-edge-sync[]
The term _cloud-to-edge synchronization_ refers to  scenarios typically involving a hierarchy of couchbase mobile clusters, within which a large number of edge clusters must synchronize data changes with each other and with one or more clusters in cloud data centers.
// end::sgw-cloud-to-edge-sync-sync[]
+
Each edge can operate autonomously without network connectivity to the cloud data centers.
The _edge_ could be, for example a group of retail stores, ships at sea or distribution hubs.
The number of edges can range from a few hundred to several thousand.
// end::sgw-cloud-to-edge-def-sync[]
+
* _Synonym(s)_: ship-to-shore sync, hub-and-spoke sync
* _SGW Component_: Inter-Syn{nbsp}Gateway Replication
* _Related Term(s)_:
* _Read More_: {xref-sgw-pg-icr-overview}
// end::sgw-cloud-to-edge-full-sync[]

{goto-index}

// == D

// [[document]]

== G

// tag::grafana[]
[[grafana]]Grafana::
Grafana is an open source data visualization and alerting platform. It supports Prometheus as a data source and can be used to build comprehensive dashboards.

// end::grafana[]

{goto-index}

== I

[inter-sync-gateway-replication]
[[inter-sync-gateway-replication]]Inter-Sync Gateway Replication::
// tag::sgw-inter-sync-gateway-replication-full[]
// tag::sgw-inter-sync-gateway-replication-def[]
// tag::sgw-inter-sync-gateway-replication[]
The term _inter-Sync Gateway replication_ refers to replication between
two Sync Gateway clusters and-or between active mobile clusters.
// tag::sgw-inter-sync-gateway-replication[]
+
From 2.8+ inter-Sync Gateway replication within Sync Gateway is delivered by a completely redesigned and re-engineered websocket-base protocol, which enables a Sync Gateway replicator to act as the _{glos-term-active-replicator}_, pulling changes from a data source and pushing them to a target.
Pre-2.8 inter-Sync Gateway replication used the SG Replicate protocol over https.
// tag::sgw-inter-sync-gateway-replication-def[]
// tag::sgw-inter-sync-gateway-replication-full[]

{goto-index}

== L

[[leaf-revision]]Leaf revision::
// tag::sgw-conf-res-leaf-revision[]
A Leaf revision is the last Document Revision in a series of changes.
Documents may have multiple Leaf Revisions (aka Conflict Revisions) due to concurrent updates.
// end::sgw-conf-res-leaf-revision[]

{goto-index}

== N

[[no-conflicts-mode]]No conflicts mode::
// tag::sgw-conf-res-no-conflicts[]
No conflicts mode is the process by which write operations that would result in a conflict are rejected by the system.
It is an optional feature in Couchbase Lite 2.0 and {legacy-configuration-properties-pfx}#databases-this_db-allow_conflicts[Sync Gateway 2.0 and above].

.Couchbase Lite Conflict Resolution Links
====

* xref:couchbase-lite:swift:learn/swift-conflict.adoc[Swift]
* xref:couchbase-lite:java:learn/java-conflict.adoc[Java]
* xref:couchbase-lite:android:learn/java-android-conflict.adoc[Java (Android)]
* xref:couchbase-lite:csharp:learn/csharp-conflict.adoc[C#]
* xref:couchbase-lite:objc:learn/objc-conflict.adoc[Objective-C]

====

// end::sgw-conf-res-no-conflicts[]

[[no-op-updates]]No op updates::
+
--
// tag::sgw-conf-no-op-update-full[]
// tag::sgw-conf-no-op-update[]
The term _no-op update_ refers to a change made to the document body that does not impact application logic but does trigger a replication by the Sync Gateway.
// end::sgw-conf-no-op-update[]

For example, you may include an otherwise redundant _counter_ property, that you increment in response to conflict resolver errors.
// tag::sgw-conf-no-op-update-context[]
// end::sgw-conf-no-op-update-full-context[]
// end::sgw-conf-no-op-update-full[]
--

{goto-index}

== O

[[rep-oneshot]]One-shot replication mode::
// tag::glos-term-rep-oneshot[]
A _one-shot_ replication will start, process all existing document changes in accordance to its _replication definition_ and then stop.

Once finished, persistent _one-shot_ replications return to a 'stopped' state, but _adhoc_ _one-shot_ replications are removed.

// end::glos-term-rep-oneshot[]

{goto-index}

== P

[[passive-replicator]]Passive replicator::
+
--
// tag::sgw-icr-passive-replicator-full[]
// tag::sgw-icr-passive-replicator[]
The term _passive replicator_, refers to the Sync Gateway endpoint that receives an incoming replication connection.
// end::sgw-icr-passive-replicator[]

// tag::sgw-icr-passive-replicator-context[]

Context

* _Synonym(s)_: passive sync gateway
* _Related Term(s)_: <<active-replicator, Active replicator>>
* _SGW Component_: Inter-Sync Gateway Replication
* _Read More_: {xref-sgw-pg-icr-overview}
// end::sgw-icr-passive-replicator-context[]
// end::sgw-icr-passive-replicator-full[]
--


[[persistent-exponential-backoff]]Persistent Exponential Backoff::
The wait time between retry attempts is exponentially increased at each attempt, until it reaches a predetermined maximum limit.
Subsequent retries may be made after the maximum limit time period has elapsed.


[[persistent-replication]]Persistent Replication::
// tag::sgw-icr-persistent-replication-full[]
// tag::sgw-icr-persistent-replication-def[]
// tag::sgw-icr-persistent-replication[]
The term _Persistent replication_ refers to replications that survive Sync Gateway restarts.
All replications are persisted by default unless explicitly flagged as not.
// end::sgw-icr-persistent-replication[]
Persistent replication is defined in the configuration file sync-gateway.json -- see {xref-sgw-pg-cofig-properties}.
It is started automatically and survives restarts.
The recommended method of defining a persistent replication is by using the configuration file.
With Inter-Sync Gateway replication you can configure all nodes with the replicators.
// end::sgw-icr-persistent-replication-def[]
+
* _Synonym(s)_: continuous replication
* _Related Term(s)_:
** <<transient-replication, Transient replication>>
** <<transient-replication, Adhoc replication>>
* _SGW Component_: Inter-Sync Gateway Replication
* _Read More_: {xref-sgw-pg-icr-overview}
// end::sgw-icr-persistent-replication-full[]

[[prometheus]]Prometheus::
// tag::prometheus[]
Prometheus is an open source systems monitoring and alerting platform and hosted by Cloud Native Computing Foundation.
At the core of it is the Prometheus Server that is responsible for polling “Prometheus targets” for stats and storing it as time series data. Prometheus targets are statically configured or can be discovered by Prometheus.

// end::prometheus[]


{goto-index}

== R

[[replication-definition]]Replication definition::
+
--
// tag::glos-term-replication-definition-full[]
// tag::glos-term-replication-definition[]
The term _Replication definition_ refers to that set of elements (parameters or properties) that define a replication, dictating what will be replicated and how the replication will be conducted.
// end::glos-term-replication-definition[]

Replication definitions are provided to Sync Gateway in 'JSON' format through either:

* The Sync Gateway configuration file  (`sync-gateway-config.json`)
* The Admin REST API's `_replication` endpoint, using a utility such as `curl`, or an application such as _Postman_.

_Replication definitions_ comprise the same elements in both the JSON configuration file and the Admin REST API; except configured replications cannot use `adhoc` or  `cancel`.


// end::glos-term-replication-definition-full[]
--

[[revision-pruning]]Revision pruning::
// tag::sgw-conf-res-revision-pruning[]
Revision Pruning is the process that deletes the metadata and/or JSON bodies associated with old non-leaf revisions.
Leaf revisions are not impacted.
// end::sgw-conf-res-revision-pruning[]

{goto-index}

== S

[[synchronized]]
[[sync]]
[[synchronizing]]
[[synchronization]]Synchronization::
+
--
// tag::sgw-icr-sync-function-def[]
// tag::sgw-icr-sync-function[]
The term, _Synchronization_, refers to the process of replicating the changes made to documents on one database to the same documents in a second instance of that database.
// end::sgw-icr-sync-function[]

* Synonyms: _replication_, _sync_
* _Related Term(s)_:
** <<sync-function, Sync function>>
** <<persistent-replication, Persistent replication>>
** <<transient-replication, Adhoc replication>>
* _SGW Component_: Inter-Sync Gateway Replication
* _Read More_: {xref-sgw-pg-icr-overview}
// end::sgw-icr-sync-function-def[]
--


[[sync-function]]Sync Function::
// tag::sgw-icr-sync-function-full[]
// tag::sgw-icr-sync-function[]
// tag::sgw-icr-sync-function-def[]
The Sync Function is a JavaScript function whose source code is stored in the Sync Gateway’s database configuration file. It is in charge of data validation, and of authorizing both read and write access to documents.
// end::sgw-icr-sync-function-def[]

// tag::sgw-icr-sync-function-rel[]
 {legacy-configuration-properties--xref--databases}  |  {legacy-configuration-properties--xref--databases-sync}
// end::sgw-icr-sync-function-rel[]
// end::sgw-icr-sync-function[]
// end::sgw-icr-sync-function-full[]

[[sync-gateway-database]]Sync Gateway Database::
// tag::sgw-icr-sync-gateway-database[]
The term _Sync Gateway database_ refers to what you may consider a namespace for documents. It provides Sync Gateway with access to documents that are stored in Couchbase Server.
// end::sgw-icr-sync-gateway-database[]

== T

[[tombstone-revision]]Tombstone revision::
// tag::sgw-conf-res-tombstone[]
A tombstone revision is essentially a marker indicating that a document has been deleted.

Each Tombstone Revision comprises: document ID, revision ID and a _deleted flag (value=true).
They are created to allow all devices to see that a document has been deleted - particularly in the case of devices that may not be online continuously and therefore not syncing regularly.

Every update -- including deletes -- creates a document revision.
Deleted revisions are also known as _Tombstone_ revisions.
They have the '“_deleted”: true' property, are replicated, but are not returned if you do a query using, for example, Couchbase Lite.
+
[source,json]
----
{
  "_deleted": true,
  "_id": "foobar",
  "_rev": "3-db962c6d93c3f1720cc7d3b6e50ac9df"
}
----
Mentioned in:
* xref:managing-tombstones.adoc[Managing Tombstones]
* xref:shared-bucket-access.adoc#metadata-purge-interval[Metadata Purge Interval]
* {legacy-configuration-properties-pfx}#databases-this_db-enable_shared_bucket_access[$dbname.enable_shared_bucket_access]
* xref:server:learn:buckets-memory-and-storage/storage.adoc#tombstones[Server Tombstones]
// end::sgw-conf-res-tombstone[]

[[transient-replication]]Transient Replication::
// tag::sgw-icr-transient-replication[]
The term _transient replication_ refers to ad hoc replications -- see:  <<adhoc-replication, Adhoc Replication>>
// end::sgw-icr-transient-replication[]

{goto-index}
