= Glossary

Automatic conflict resolution::
The process by which conflicts are automatically resolved by the system.

:param-bookmark: handling-conflicts
include::partial$blocklinks-cbl.adoc[]

Leaf revision::
The last Document Revision in a series of changes.
Documents may have multiple Leaf Revisions (aka Conflict Revisions) due to concurrent updates.

Revision pruning::
Pruning is the process that deletes the metadata and/or JSON bodies associated with old non-leaf revisions.
Leaf revisions are not impacted.

No conflicts mode::
The process by which write operations that would result in a conflict are rejected by the system -- see xref:config-properties.adoc#databases-foo_db-allow_conflicts[Sync Gateway 2.0 and above].

:param-bookmark: handling-conflicts
include::partial$blocklinks-cbl.adoc[]

Tombstone revision::
A document revision that contains only the document ID, a revision ID and the `_deleted: true` key value pair.
A tombstone revision acts as the record of a deleted item.
Tombstone revisions are created to allow all devices to see that a document has been deleted - particularly in the case of devices that may not be online continuously and therefore not syncing regularly.
+
[source,json]
----
{
  "_deleted": true,
  "_id": "foobar",
  "_rev": "3-db962c6d93c3f1720cc7d3b6e50ac9df"
}
----
Mentioned in:
* xref:managing-tombstones.adoc[Managing Tombstones]
* xref:shared-bucket-access.adoc#metadata-purge-interval[Metadata Purge Interval]
* xref:config-properties.adoc#databases-foo_db-enable_shared_bucket_access[$dbname.enable_shared_bucket_access]
* xref:server:learn:buckets-memory-and-storage/storage.adoc#tombstones[Server Tombstones]
