= Install and Sync
:page-layout: article
:page-role: panes
:page-status: {releaseStatus} -- {releaseComments}
:page-content: conceptual
include::partial$_attributesLocal.adoc[]


ifeval::["{releaseStatus}" == "beta"]
[.pane__frame--orange]
.Author's Notes
--
Document the installation and synchroization process

Provide a better way of linking the CBL and SGW  (for instance link to getting started or replicator config section on CBL" .

Provide a Further Reading block to "REST API" reference since the tests discuss that
--
endif::[]

[abstract]
Cover the configuration process and properties

== Overview

Reprehenderit pariatur magna eiusmod tempor est commodo aliqua elit proident irure. Velit cupidatat eiusmod sit enim pariatur exercitation tempor anim veniam ad in incididunt. Exercitation enim quis dolor irure irure nulla excepteur nisi duis nulla proident tempor.

Ea nulla occaecat sit nostrud cillum. Eiusmod fugiat adipisicing magna nisi eiusmod ad exercitation laboris sunt. Nostrud cupidatat pariatur non velit in sit ea magna. Cillum irure amet elit pariatur fugiat officia id voluptate irure. Tempor aute mollit in aliqua.


== Related Content

[.pane__frames]

* *How-to*
+
--
xref:sync-gateway::gs-configure-sgw.adoc[Configure]

xref:sync-gateway::gs-before.adoc[Before You Start]

xref:sync-gateway::getting-started[Installing Server]
--

* *Learn more*
+
--
xref:sync-gateway::shared-bucket-access.adoc[Introducing Data Sync]

xref:sync-gateway::rest-api-client.adoc[Introducing REST API]

include tutorial links as relevant

include blog links as relevant
--

* *Reference material*
+
--
xref:sync-gateway::config-properties.adoc[Configuration Schema]

(eg config file or api)
--
