= Configure SGW
:page-type: procedural
include::partial$_attributes-local.adoc[]
:xref-pfx: {xref-pfx-sgw}:

[abstract]
Provides an example configuration suitable for the Getting Started activity

The following steps explain how to configure Sync Gateway to connect to a Couchbase Server instance.

. Create a new file called *sync-gateway-config.json* with the following content:
+
--
[source,javascript]
----
include::example$getting-started/sync-gateway-config.json[]
----

.Configuration properties:

<1> The user's username that you created on the Couchbase Server Admin Console.
<2> The user's password that you created on the Couchbase Server Admin Console.
<3> The {xref-pfx}shared-bucket-access.adoc[shared bucket access] feature allows Couchbase Server SDKs to also perform operations on this bucket.
<4> `num_index_replicas` is the number of index replicas stored in Couchbase Server, introduced with {xref-pfx}indexing.adoc[GSI/N1QL indexing].
If you're running a single Couchbase Server node for development purposes the `num_index_replicas` must be set to `0`.

--

. Start Sync Gateway
+
--
Start Sync Gateway from the command line, or if Sync Gateway is running in a service replace the configuration file and restart the service.

[source,bash]
----
~/Downloads/couchbase-sync-gateway/bin/sync_gateway ~/path/to/sync-gateway-config.json
----

Run the application where Couchbase Lite is installed.
--
. To verify that documents have been replicated, you can:
** Monitor the Sync Gateway sequence number returned by the database endpoint ({xref-pfx}rest-api.adoc#/database/get\__db__[`+GET /{db}/+`]).
The sequence number increments for every change that happens on the Sync Gateway database.
** Query a document by ID on the Sync Gateway REST API ({xref-pfx}rest-api.adoc#/document/get\__db___doc_[`+GET /{db}/{id}+`]).
** Query a document from the Query Workbench on the Couchbase Server Console.

== Related Information

.Next Steps:
* {xref-pfx}gs-sgw-api-access.adoc[Access the APIs]

.Learn more:
* {xref-pfx}admin-rest-api.adoc[About the Admin API]
* {xref-pfx}rest-api.adoc[About the Public API]
* {xref-pfx}config-properties.adoc[Config Schema Reference]

.Do more:
** _Rest API Client_: {xref-pfx}rest-api-client.adoc[Build a simple api client]
