= Running and Managing Replications
:page-aliases: running-replications
:page-layout: article
:page-status: {releaseStatus} -- {releaseComments}
:page-role: panes
:page-content: procedural
include::partial$_attributesLocal.adoc[]

ifeval::["{releaseStatus}" == "beta"]
[.pane__frame--orange]
.Author's Notes
--
Document relevant aspects of _Running and Managing Replications_
Information sources include:

* Existing content from xref:2.7@sync-gateway.running-replications.adoc[Running Replications] as below
* https://issues.couchbase.com/browse/DOC-6465
* https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e77c903#heading=h.nsn5wnqrbttx

--
endif::[]

[abstract]
Adhoc replications are run using the xref:{component-sgw}::rest-api-client.adoc[Admin Rest API].

== Running replications via the REST API

A replication is run by sending a POST request to the server endpoint `_replicate`, with a JSON object defining the replication parameters.
Both one-shot and continuous replications can be run.
Each replication is one-way between two local or remote Sync Gateway databases.
Multiple replications can run simultaneously, supporting bi-directional replications and different replication topologies.
Be aware that both databases being synchronized should have the same sync function, otherwise it could lead to unexpected behavior.

These parameters start a one-shot replication between two databases on the local Sync Gateway instance.
The request will block until the replication has completed.

[source,javascript]
----
{
    "source": "db",
    "target": "db-copy"
}
----

These parameters start a one-shot replication between one database on the local Sync Gateway instance and one on a remote Sync Gateway instance, with user credentials.
The request will return immediately and the replication will run asynchronously.

[source,javascript]
----
{
    "source": "db",
    "target": "http://user:password@example.com:4985/db-copy",
    "async":true
}
----

These parameters start a continuous replication between one database on the local Sync Gateway instance and one on a remote Sync Gateway instance with the user provided `replication_id`.
The request will return immediately and the replication will run asynchronously.

[source,javascript]
----
{
    "replication_id":"my-named-replication",
    "source": "db",
    "target": "http://user:password@example.com:4985/db-copy",
    "continuous":true
}
----

These parameters start a continuous replication between one database on the local Sync Gateway instance and one on a remote Sync Gateway instance.
The replicator will batch up to 1000 revisions at a time, this will improve replication performance but will use more memory resources.
Source database documents will be filtered so that only those tagged with the channel names "channel1" or "channel2" are replicated.

[source,javascript]
----
{
    "source": "db",
    "target": "http://user:password@example.com:4985/db-copy",
    "continuous":true,
    "changes_feed_limit":1000,
    "filter":"sync_gateway/bychannel",
    "query_params":["channel1","channel2"]
}
----

== Configuration Properties

The `_replicate` JSON Object supports the following properties.

[cols="1,1,3,1"]
|===
|Name |Type |Description |Default

|`source`
|URL
|_Required._ A URL pointing to the source database for the replication, the URL may be relative i.e. just the name of a local database on the Sync Gateway instance.
The URL may point to the Admin REST API which will replicate all documents in the DB, or it may point to the public REST API which will only copy documents in the users assigned channels.
When specifying credentials, the URL must be of the form `user:password@host`.
|none

|`target`
|URL
|_Required._ A URL pointing to the target database for the replication, the URL may be relative i.e. just the name of a local database on the Sync Gateway instance.
The URL may point to the Admin REST API or it may point to the public REST API, this will impact the behavior of the target database sync function.
When specifying credentials, the URL must be of the form `user:password@host`.
|none

|`continuous`
|Boolean
|_Optional._ Indicates whether the replication should be a one-shot or continuous replication.
|false

|`filter`
|String
|_Optional._ Passes the name of filter to apply to the source documents, currently the only supported filter is "sync_gateway/bychannel", this will replicate documents only from the set of named channels.
|none

|`query_params`
|Object
|_Optional._ Passes parameters to the filter, for the "sync_gateway/bychannel" filter the value should be an array or channel names (JSON strings).
|none

|`cancel`
|Boolean
|_Optional._ Indicates that a running replication task should be canceled, the running task is identified by passing its `replication_id` or by passing the original source and target values.
|false

|`replication_id`
|String
|_Optional._ If the cancel parameter is true then this is the id of the active replication task to be canceled, otherwise this is the `replication_id` to be used for the new replication.
If no replication_id is given for a new replication it will be assigned a random UUID.
|false

|`async`
|Boolean
|_Optional._ Indicates that a one-shot replication should be run asynchronously and the request should return immediately.
Replication progress can be monitored by using the `_active_tasks` resource.
|false

|`changes_feed_limit`
|Number
|_Optional._ The maximum number of change entries to pull in each loop of a continuous changes feed.
|50
|===

== Running replication on startup

If you want to run replications as soon as Sync Gateway starts, you can define replications in the top level "replications" property of the Sync Gateway configuration, the "replications" value is an array of objects, each object defines a single replication, the object properties are the same as those for the `_replicate` end-point on the Admin REST API.

One-shot replications are always run asynchronously even if the `async` property is not set to true.

A One-shot replication that references a local database for either source or target, will be run after a short delay (5 seconds) in order to allow the local REST API's to come up.
Replications may be given a user defined `replication_id` otherwise Sync Gateway will generate a random UUID.
Replications defined in config may not contain the `cancel` property.

[source,javascript]
----
{
    "log":["*"],
    "replications":[
        {
            "source": "db",
            "target": "db-copy"
        },
        {
            "source": "db",
            "target": "http://user:password@example.com:4985/db-copy"
        },
        {
            "replication_id":"continuous-remote-local",
            "source": "http://user:password@example.com:4985/db-backup",
            "target": "db"
            "continuous":true
        },
        {
            "replication_id":"continuous-filtered",
            "source": "db",
            "target": "http://user:password@example.com:4985/db-copy"
            "continuous":true,
            "changes_feed_limit":1000,
            "filter":"sync_gateway/bychannel",
            "query_params":["channel1","channel2"]
        }
    ],
    "databases": {
        "db": {
            "server": "http://localhost:8091",
            "bucket": "db",
            "users": {
                "GUEST": {"disabled": false, "admin_channels": ["*"]}
            }
        },
        "db-copy": {
            "server": "http://localhost:8091",
            "bucket": "db-copy",
            "users": {
                "GUEST": {"disabled": false, "admin_channels": ["*"]}
            }
        }
    }
}
----

== Monitoring replications

By default a simple one-shot replication blocks until it is complete and returns the stats for the completed task.
Async one-shot and continuous replications return immediately with the in flight task stats.

You can get a list of active replication tasks by sending a GET request to the `_active_tasks` endpoint, this will return a list of all running one-shot and continuous replications for the current Sync Gateway instance.

The response is a JSON array of active task objects, each object contains the original request parameters for the replication, a unique `replication_id` and some stats for the replication instance.
The list of returned stats and their meaning can be found on the API reference of the xref:admin-rest-api.adoc#/server/get\__active_tasks[`_active_tasks`] endpoint.

[source,javascript]
----
[
    {
        "type":"replication",
        "replication_id":"6a4924c24424b635a80f50cd660fb192",
        "continuous":true,
        "source":"http://example.com:4985/source",
        "target":"http://example.com:4985/target",
        "docs_read":0,
        "docs_written":0,
        "doc_write_failures":0,
        "end_last_seq":null
    },
    {
        "type":"replication",
        "replication_id":"active-to-backup",
        "continuous":true,
        "source":"http://example2.com:4985/active",
        "target":"http://example2.com:4985/backup",
        "docs_read":1000,
        "docs_written":850,
        "doc_write_failures":10,
        "end_last_seq":25680
    }
]
----

== Canceling replications

An active replication task is canceled by sending a POST request to the server endpoint `_replicate`, with a JSON object.
The JSON object must contain the `cancel` property set to true and either a valid `replication_id` or the identical source, target and continuous values used to start the replication.

This will cancel an active replication with a `replication_id` of "my-one-shot-replication", the `replication_id` value can be obtained by sending a request to `_active_tasks`.

[source,javascript]
----
{
    "cancel": true,
    "replication_id": "my-one-shot-replication"
}
----

This will cancel a replication that was started with same "source" and "target" values as those in the cancel request.
By omitting the "continuous" property it's value will default to *false*, a replication must also have been started as a one-shot to match.

[source,javascript]
----
{
    "cancel":true,
    "source": "db",
    "target": "db-copy"
}
----

When an active task is canceled, the response returns the stats of the replication up to the point when it was stopped.

[source,javascript]
----
{
    "type":"replication",
    "replication_id":"3791d562153505408e0b2730603ed7c1",
    "continuous":true,
    "source":"http://0.0.0.0:4985/source",
    "target":"http://0.0.0.0:4985/target",
    "docs_read":12,
    "docs_written":12,
    "doc_write_failures":0,
    "start_last_seq":0,
    "end_last_seq":"28"
}
----

== Related Content

[.pane__frames]

* *How-to*
+
--
include how-to links as relevant,

include how-to links as relevant,
--

* *Learn more*
+
--
include any related concept links

include tutorial links as relevant

include blog links as relevant
--

* *Reference material*
+
--
include any reference docs

(eg config file or api)
--
