= Inter-Cluster Replication Types
:page-layout: article
:page-status: {releaseStatus} -- {releaseComments}
:page-role: panes
include::partial$_attributesLocal.adoc[]

ifeval::["{releaseStatus}" == "beta"]
[.pane__frame--orange]
.Author's Notes
--
Document relevant aspects of _Replication Types_.

Information sources include:

* https://issues.couchbase.com/browse/DOC-6494
* https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.dee3943zlt52

--
endif::[]

[abstract]
Sync Gateway inter-cluster replication supports two replication types: _Persistent_ and _Transient_ (or _Adhoc_). Persistent replication survives restarts, whilst adhoc replications run once only, on creation.

== Overview
Nostrud magna aliqua eiusmod ullamco ipsum cupidatat cillum aliquip deserunt aliqua. Minim adipisicing ullamco id officia. Nisi ex sunt eu mollit minim dolor nisi elit proident et ex incididunt dolore. Velit mollit proident minim officia sit nulla. Occaecat ex pariatur incididunt anim. Irure cillum voluptate laborum reprehenderit culpa non ad labore mollit ullamco ut do nisi. Aliqua pariatur ut proident ut do commodo ea eu fugiat labore magna occaecat in consectetur.

Aliquip incididunt ea excepteur consectetur qui. Incididunt ex consequat consectetur ipsum aliquip veniam quis irure ipsum occaecat laboris irure. Pariatur esse mollit laborum consectetur officia occaecat non et nisi cillum non do nulla aliquip. Esse occaecat sunt dolore minim consectetur anim commodo dolor eiusmod deserunt velit veniam laboris consectetur. Eu cupidatat ea do culpa dolor aliquip do pariatur esse ullamco duis sit. Occaecat veniam ullamco ad eiusmod voluptate exercitation dolore enim sit enim exercitation ex consectetur. Ut excepteur id velit enim.

== Persistent Replication

// tag::glos-persistent-replication[]
Persistent replication is defined in the configuration file `sync-gateway.json` (see  xref:sync-gateway::config-properties.adoc[Sync Gateway configuration properties]).
It is started automatically and survives restarts.

// end::glos-persistent-replication[]

NOTE: Recommended method is to define a persistent replication using the _Configuration_ file.
With _SG Replicate 2.0_ you can configure all nodes with the replicators.

== Transient Replication

Started dynamically using the xref:sync-gateway::rest-api-client.adoc[Admin Rest API].


== Related Content

[.pane__frames]

* *How-to*
+
--
include how-to links as relevant,

include how-to links as relevant,
--

* *Learn more*
+
--
include any related concept links

include tutorial links as relevant

include blog links as relevant
--

* *Reference material*
+
--
include any reference docs

(eg config file or api)
--