= High-Availability Replication
:page-layout: article
:page-status: {releaseStatus} -- {releaseComments}
:page-role: panes
:page-content: conceptual
include::partial$_attributesLocal.adoc[]

ifeval::["{releaseStatus}" == "beta"]
[.pane__frame--orange]
.Author's Notes
--
Document relevant aspects of _High-Availability Replication_.

Information sources include:

* https://issues.couchbase.com/browse/DOC-6494
* https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.dee3943zlt52

--
endif::[]

[abstract]
Covers the topic of high-availability replication.

== Overview

Occaecat fugiat deserunt incididunt nostrud ipsum qui est ipsum est dolor do. Aliqua laboris proident dolore consequat laboris commodo cupidatat non proident incididunt consequat incididunt et. Esse veniam commodo qui do.

Enim id labore Lorem ex deserunt et aliqua pariatur dolore aliquip incididunt exercitation excepteur dolor. Anim nulla id pariatur officia dolor consequat occaecat do consectetur aliquip magna. Veniam reprehenderit ex aliqua sunt consequat in. Lorem consequat id commodo velit sit ad tempor eu. Id reprehenderit qui adipisicing minim. Sunt enim labore quis non consectetur.

Officia esse pariatur anim consequat laboris ex ut elit ullamco anim nulla aliqua. Deserunt voluptate consequat minim ullamco ullamco ipsum exercitation. Est cillum ad aliquip esse sunt labore magna ipsum est ullamco enim et voluptate quis. Tempor do sunt occaecat exercitation dolor cupidatat veniam labore mollit est ex non mollit cupidatat. Voluptate nulla labore culpa Lorem enim voluptate dolor sint reprehenderit.

== Related Content

[.pane__frames]

* *How-to*
+
--
include how-to links as relevant,

include how-to links as relevant,
--

* *Learn more*
+
--
include any related concept links

include tutorial links as relevant

include blog links as relevant
--

* *Reference material*
+
--
include any reference docs

(eg config file or api)
--