= High-Availability Replication
:page-layout: article
:page-status: {releaseStatus} -- {releaseComments}
:page-role: panes
:page-content: conceptual
include::partial$_attributesLocal.adoc[]

ifeval::["{releaseStatus}" == "beta"]
[.pane__frame--orange]
.Author's Notes
--
Document relevant aspects of _High-Availability Replication_.

Information sources include:

* Ticket: https://issues.couchbase.com/browse/DOC-6494[DOC-6494]
* https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.dee3943zlt52


--
endif::[]

[abstract]
Covers the topic of high-availability replication.

== Overview

.Points to cover include:

* {empty}
+
--
Sync Gateway by default must support  High Availability of a replication.
While a  given replication will only run on one node at any given time but when that node fails, the system will automatically elect another node for replication.

Recommendation : To get HA, Users must be configure at least two nodes to run a given replication.

This will apply to SG-Replicate 2


Impl note: Based on set of replications defined, system will have a node election process/ heartbeat process to detect if a node is up or not)

Note : This requirement is true only for EE. In case of CE, Sync Gateway will behave as it does today. The replicator will run on the nodes that the users designate in their configuration.
--
* {empty}
+
--
In case of multiple  replications, Sync Gateway by default must distribute the set of replications across all available sync gateway nodes (on which the replications are configured). Even if a replication is configured on multiple nodes, a given replication will only run on one node at any given time.


This will apply to SG-Replicate 2

This will provide the following -
Improved throughput by distributing the replications
By ensuring that a replicator only runs on one node even if configured to run on multiple nodes, the system  redundant exchange of data as a result of redundant replications. This will reduce the processing load on the sync gateway and reduce bandwidth usage
This will allow us to deploy a truly homogenous cluster even in SG-replicate based environment where every SGW node in cluster has an identical configuration. This will enable future platform architectural enhancements around mobile manageability .

Impl note: Based on set of replications defined, system will have a node election process/ heartbeat process

Note : This requirement is true only for EE. In case of CE, Sync Gateway will behave as it does today. The replicator will run on the nodes that the users designate in their configuration. This implies that in case of a homogeneous cluster with every node having identical configuration , the replication will run on all nodes.
--
* {empty}
+
--
In EE, replications will get automatically get redistributed as more Sync Gateways are added to the cluster or removed from cluster
--
* {empty}
+
--
Expected behavior
https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit#heading=h.vwjngb7h5lpm
--



== Related Content

[.pane__frames]

* *How-to*
+
--
include how-to links as relevant,

include how-to links as relevant,
--

* *Learn more*
+
--
include any related concept links

include tutorial links as relevant

include blog links as relevant
--

* *Reference material*
+
--
include any reference docs

(eg config file or api)
--