= Managing Replications
:page-layout: article
:page-status: {releaseStatus} -- {releaseComments}
:page-role: panes
:page-content: conceptual
include::partial$_attributesLocal.adoc[]

ifeval::["{releaseStatus}" == "beta"]
[.pane__frame--orange]
.Author's Notes
--
Document relevant aspects of _Managing Replications_, maybe incorporate this with xref:{component-sgw}::.

Information sources include:

* https://issues.couchbase.com/browse/DOC-6465
* https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e77c903#heading=h.nsn5wnqrbttx

--
endif::[]

[abstract]
Cover inter-cluster replication mamagement

== Overview
Sunt id ut anim aute. Deserunt consequat est excepteur laborum minim ad elit ut mollit. Ex sit duis laborum anim id magna.

Pariatur fugiat proident officia exercitation exercitation sunt ipsum. Cillum amet ipsum sit amet non duis laboris aliquip. Magna deserunt quis laborum nulla. Et excepteur Lorem quis aliquip quis laborum aliqua deserunt tempor. Sunt sit esse qui amet cillum mollit nostrud ullamco eu cillum ad Lorem et id.


== Related Content

[.pane__frames]

* *How-to*
+
--
include how-to links as relevant,

include how-to links as relevant,
--

* *Learn more*
+
--
include any related concept links

include tutorial links as relevant

include blog links as relevant
--

* *Reference material*
+
--
include any reference docs

(eg config file or api)
--
