= Replication Stats and Monitoring
:page-layout: article
:page-role: panes
:page-status: {releaseStatus} -- {releaseComments}
:page-content: conceptual
include::partial_attributesLocal.adoc[]


ifeval::["{releaseStatus}" == "beta"]
[.pane__frame--orange]
.Author's Notes
--
Document relevant aspects of _Monitoring Replication Metrics_, maybe incorporate this with xref:2.7@sync-gateway::stats-monitoring.adoc[Stats Monitoring].

Information sources include:

* https://issues.couchbase.com/browse/DOC-6465
* https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e77c903#heading=h.k97tmr4fpwci

--
endif::[]


[abstract]
Cover inter-cluster replication Resolution Stats and Monitoring

== Overview

Reprehenderit pariatur magna eiusmod tempor est commodo aliqua elit proident irure. Velit cupidatat eiusmod sit enim pariatur exercitation tempor anim veniam ad in incididunt. Exercitation enim quis dolor irure irure nulla excepteur nisi duis nulla proident tempor.

Ea nulla occaecat sit nostrud cillum. Eiusmod fugiat adipisicing magna nisi eiusmod ad exercitation laboris sunt. Nostrud cupidatat pariatur non velit in sit ea magna. Cillum irure amet elit pariatur fugiat officia id voluptate irure. Tempor aute mollit in aliqua.


== Related Content

[.pane__frames]

* *How-to*
+
--
include how-to links as relevant,

include how-to links as relevant,
--

* *Learn more*
+
--
include any related concept links

include tutorial links as relevant

include blog links as relevant
--

* *Reference material*
+
--
include any reference docs

(eg config file or api)
--