= Conflict Resolution
:page-layout: article
:page-role: panes
:page-status: {releaseStatus} -- {releaseComments}
:page-content:
include::partial_attributesLocal.adoc[]

ifeval::["{releaseStatus}" == "beta"]
[.pane__frame--orange]
.Author's Notes
--
Document relevant aspects of _replication conflict resolution.

Information sources include:

* https://issues.couchbase.com/browse/DOC-6465
* https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.ho0j9x72yi1l

--
endif::[]

[abstract]
Cover conflict resolution in respect of inter-cluster replication.

== Overview

Qui do qui velit Lorem amet esse id labore sint mollit officia. Ad esse culpa ex reprehenderit eiusmod deserunt ex velit. Sunt sit amet Lorem veniam irure enim ea deserunt cillum ex culpa amet sit culpa. Proident adipisicing cupidatat sit sit enim anim mollit non. Do nostrud officia deserunt amet ex labore mollit velit exercitation laboris culpa sit proident incididunt. Tempor minim laborum enim amet. Voluptate occaecat duis dolor do elit mollit.

Sunt excepteur exercitation reprehenderit est qui. Labore est pariatur excepteur nostrud cillum. Mollit aliquip incididunt anim veniam sit ipsum sit.

== Related Content

[.pane__frames]

* *How-to*
+
--
include how-to links as relevant,

include how-to links as relevant,
--

* *Learn more*
+
--
include any related concept links

include tutorial links as relevant

include blog links as relevant
--

* *Reference material*
+
--
include any reference docs

(eg config file or api)
--
