// BEGIN -- PAGE -- import-filter.adoc
// BEGIN PAGE DEFINITION
//  LOCATION modules/ROOT/pages/
//  PURPOSE:
//    This is a standard content presentations page.
//    Its name/title identify the content/topic
//  PARAMETERS:
//    None
//  INCLUSION USAGE --
//    This module uses attributes from:
//    - /modules/ROOT/pages/_partials/_page-index.adoc -- xref page links
//
//    This module uses these inclusions:
//    - /modules/ROOT/pages/_partials/_std-hdr-sgw.adoc -- std attribute environment
//    - /modules/ROOT/pages/_partials/block-abstract.adoc --  std text block for page header content
//    - /modules/ROOT/pages/_partials/block-related-content-deploy.adoc --  std text block for page footer content
//    - modules/ROOT/assets/images -- .png/.jpeg images
//  INCLUSION USAGE
// END PAGE DEFINITION
= Import Filter
:page-aliases: advance/adv-sgw-cfg-import-filter.adoc, import-filters
:page-type: procedural
:page-status:
:page-edition:
:page-role:
:description: Introducing sync functions and how to use them
:idprefix:
:idseparator: -
// End of page attributes

include::partial$_std-hdr-sgw.adoc[]
:xref--pfx: {sgw--xref}:

:param-related: {legacy-configuration-properties--xref}  |  {rest-api-admin--xref}
:param-abstract: Provides an example configuration suitable for beginning to use Import Filters
include::partial$block-abstract.adoc[]

== Introduction
For clusters with a large amount of data, the initial import process can take considerable time to complete.
Therefore, to get started with a cluster which contains a large number of pre-existing documents, we recommend to use an `import_filter` to reduce the initial import processing time.

== Function Provision

include::partial$common-cfg-ext-javascript.adoc[tag=intro]

You can learn more about this property ($db.sync) in the Configuration Schema Reference -- see: {legacy-configuration-properties--xref--databases-import-filter}.

include::partial$common-cfg-ext-javascript.adoc[tag=config-full]


== Configuration

[source,json]
----
include::{example-cfg}[tag="import-filter-config"]
----

Configuration properties:

<1> The user's username that you created on the Couchbase Server Admin Console.
<2> The user's password that you created on the Couchbase Server Admin Console.
<3> The {xref-sgw-pg-shared-bucket-access} feature allows Couchbase Server SDKs to also perform operations on this bucket.
<4> `num_index_replicas` is the number of index replicas stored in Couchbase Server, introduced with GSI/N1QL indexing -- see {xref-sgw-pg-indexing}.
If you're running a single Couchbase Server node for development purposes the `num_index_replicas` must be set to `0`.
<5> Only import documents which have a `type` property equal to `mobile`.



include::partial$block-related-content-data.adoc[]

// END -- PAGE -- import-filter.adoc
