// BEGIN -- PAGE -- import-filter.adoc
// BEGIN PAGE DEFINITION
//  LOCATION modules/ROOT/pages/
//  PURPOSE:
//    This is a standard content presentations page.
//    Its name/title identify the content/topic
//  PARAMETERS:
//    None
//  INCLUSION USAGE --
//    This module uses attributes from:
//    - /modules/ROOT/pages/_partials/_define_page_index.adoc -- xref page links
//
//    This module uses these inclusions:
//    - /modules/ROOT/pages/_partials/_set_page_context.adoc -- std attribute environment
//    - /modules/ROOT/pages/_partials/_show_page_header_block.adoc --  std text block for page header content
//    - /modules/ROOT/pages/_partials/block-related-content-deploy.adoc --  std text block for page footer content
//    - modules/ROOT/assets/images -- .png/.jpeg images
//  INCLUSION USAGE
// END PAGE DEFINITION
= Import Filter
:page-aliases: advance/adv-sgw-cfg-import-filter.adoc, import-filters
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:page-type: procedural
:description: pass:q[Introducing _import filters_ and how to use them to speed-up the initial import process.]
:idprefix:
:idseparator: -


include::partial$_set_page_context.adoc[]


// Begin -- page attributes
:xref--pfx: {sgw--xref}:
// End of page attributes


// BEGIN -- Page Heading
:topic-group: sync
include::partial$_show_page_header_block.adoc[]
// END -- Page Heading


== Introduction


The purpose of the import filter is to identify the subset of documents eligible to be replicated by Sync Gateway.
This subset is based on application requirements, and is applied to all future mutations.

Without a filter (the default), Sync Gateway imports all documents and so we recommend use of this import filter unless there is a compelling use-case against it.


== Function Provision

Use the {rest-api-admin--xref--database-configuration} Admin Rest API endpoint xref:clusters:modules/Admin REST API[/{db}/_config/import_filter] to provision an import filter for a database using the `application/javascript` mime type.

If you are using legacy configuration then, you need to include it in your configuration file, see: {configuration-properties-legacy--xref--databases-import-filter}.


== Configuration


[#ex-config]
.Using an Import Filter
====

[{tabs}]
=====

API::
+
--

[source,bash]
----
include::{example-cfg}[tag="import-filter-config"]
----

<.> You will need to provide authentication in the call; unless it is disabled (not recommended in production environment).

--

+
Legacy::
+
--
[source,json]
----
include::{example-cfg}[tag="import-filter-config-legacy"]
----

Configuration properties:

<1> The user's username that you created on the Couchbase Server Admin Console.
<2> The user's password that you created on the Couchbase Server Admin Console.
<3> The {sync-with-couchbase-server--xref} feature allows Couchbase Server SDKs to also perform operations on this bucket.
<4> `num_index_replicas` is the number of index replicas stored in Couchbase Server, introduced with GSI/N1QL indexing -- see {indexing--xref}.
If you're running a single Couchbase Server node for development purposes the `num_index_replicas` must be set to `0`.
<5> Only import documents which have a `type` property equal to `mobile`.

--
=====
====


// BEGIN -- Page Footer
include::partial$block-related-content-sync.adoc[]
// END -- Page Footer

// END -- PAGE -- import-filter.adoc
