= What's New
:idprefix:
:idseparator: -

== Guaranteed Availability

Prior to 2.1, Sync Gateway used system views for a variety of internal operations, including authentication and replication.
Starting in 2.1, Sync Gateway will use GSI and N1QL to perform those tasks.

xref:indexing.adoc[Read more]

== X.509 Authentication against Couchbase Server

Sync Gateway adds the ability to use X.509 certificates to authenticate against Couchbase Server 5.5 or higher.
This functionality can be used instead or in addition to the existing authentication method which is to specify a username and password in the configuration file.

xref:security.adoc#x-509-certificates[Read more]

== Continuous Logging

Continuous logging is a new feature in Sync Gateway 2.1 that provides more flexibility in how logs are generated and retained, whilst maintaining the level of logging required by Couchbase Support for investigation of issues.

The previous logging configuration (`logging.default`) is being deprecated, and Sync Gateway 2.1 will display warnings on startup of what is required to update your configuration.

xref:logging.adoc#continuous-logging[Read more]

== Log Redaction

All log outputs can be redacted, this means that user-data, considered to be private, is removed.
This feature is optional and can be enabled in the configuration with the xref:config-properties.adoc#logging-redaction_level[`logging.redaction_level`] property.

SGCollect Info now supports xref:sgcollect-info.adoc#log-redaction[log redaction] post-processing.

== Bucket operation timeout

The xref:config-properties.adoc#databases-foo_db-bucket_op_timeout_ms[`databases.$db.bucket_op_timeout_ms`] property to override the default timeout used by Sync Gateway to query Couchbase Server.
It's generally not necessary to change this property unless there is a particularly heavy load on Couchbase Server which would increase the response time.

== Support for IPv6

Sync Gateway now officially supports IPv6.

== Release Notes

This release contains a number of bug fixes and enhancements for Sync Gateway.
Find out more in the release notes.

xref:release-notes.adoc[Release Notes]
