= What's New
:page-aliases: index
:page-status: {releaseStatus}
:page-role: -toc panes
:page-content: contextual
include::partial$_attributes-local.adoc[]

== Release 2.8
Sync Gateway 2.7 introduces significant performance and resilience enhancements which provide Enterprise-customers with:

[.pane__frames]

* *Inter Cluster Replication*
+
--
Adipisicing fugiat Lorem duis et non nulla nisi ad commodo fugiat ea. Eiusmod Lorem incididunt occaecat commodo qui fugiat ut eu consequat. Laborum incididunt amet adipisicing duis voluptate qui quis aliqua nulla eu laboris amet ex aliquip.

Anim elit consectetur ex aute mollit deserunt esse aute nulla nostrud qui nulla ex. Exercitation sit ut ullamco esse irure eiusmod eiusmod. Minim sit quis reprehenderit qui commodo incididunt tempor.

Voluptate reprehenderit duis nulla labore dolor.
--

* *GSI*
+
--
Cillum nostrud nisi elit veniam commodo nulla. Non veniam velit non labore commodo nisi qui sit enim officia. Nostrud in cupidatat sit ullamco. Ad amet eiusmod non nisi ipsum adipisicing aliquip esse. Magna pariatur aute pariatur adipisicing ipsum. Laboris proident id aliqua veniam veniam incididunt laboris enim ullamco commodo magna. Magna duis velit incididunt exercitation non sit enim Lorem.

Eu exercitation do anim velit voluptate magna veniam officia reprehenderit ut. Occaecat eu aliqua irure aliqua. Laboris laboris proident occaecat enim laborum quis ex nisi fugiat. Duis ea aliquip veniam cillum ut occaecat dolor. Labore fugiat excepteur voluptate duis. Mollit et laboris voluptate aute qui amet commodo reprehenderit. Eu nulla qui tempor velit.
--

* *Fixes and enhancements*
+
[.pane__cards]
** This release also contains a number of bug fixes and enhancements for Sync Gateway.
+
Find out more in the xref:release-notes.adoc[Release Notes]
** *Further information:*
+
See the xref:release-notes.adoc[Release Notes], which also include details of the current maintenance release (SGW: {version-full}).

