= What's New
:page-layout: article
:page-role: tiles -toc
include::partial$_attributes-local.adoc[]

NOTE: See the xref:release-notes.adoc[Release Notes], which also include details of the current maintenance release (SGW: {version-full}).

Sync Gateway 2.7 introduces significant performance and resilience enhancements which provide Enterprise-customers with:

== Built-in High Availability of Import Processing
Enterprise Customers can now designate multiple Sync Gateway nodes as _Import Processing_ nodes (to handle Couchbase Server writes)
This provides added resiliency. The workload of any lost node will be shared across the remaining Sync-gateway nodes.

== Linear Scaling of Import Processing
In addition to significant performance enhancements to per-node import throughput, Enterprise Customers can also take advantage of the multi-node import processing capability to linearly scale import throughput. Adjusting the number of dedicated nodes to meet changing workload and throughput requirements.

== Enhanced Write Scaling
A series of read and write processing optimizations in the Sync Gateway that includes efficient handling of of Json document marshalling/unmarshalling means Enterprise-customers can see improvements in per-node write throughput during replication and can more efficiently handle the demands of large-scale concurrent writes ... xref:shared-bucket-access.adoc[Read more]

== Fixes and enhancements
This release also contains a number of bug fixes and enhancements for Sync Gateway.
Find out more in the xref:release-notes.adoc[Release Notes]
