= What's New

== No Conflicts Mode

Sync Gateway 2.0 can be run in "no conflicts mode".
When running in this mode, Sync Gateway will reject any updates that would otherwise create a conflict.
When using Couchbase Lite 2.0, these conflicts can be automatically detected and resolved by the client.

Details on how to configure this mode, along with additional information, is included at (xref:config-properties.adoc#databases-foo_db-allow_conflicts[databases.$db.allow_conflicts]).

== Data Lifecycle Management

An expiry value can now be set for Couchbase Lite replication checkpoints (and local documents more generally), allowing users to configure how long these are retained.
By default they will be retained for 90 days, but this can be customized using (xref:config-properties.adoc#databases-foo_db-local_doc_expiry_secs[databases.$db.local_doc_expiry_secs]).

Document expiry can now be set using the Sync Function.
A new built-in function, (xref:sync-function-api.adoc#expiry[expiry()]) can be used to set the Couchbase Server expiry for the document.

== Release Notes

This release contains a number of bug fixes and enhancements for Sync Gateway.
Find out more in the release notes.

xref:release-notes.adoc[Release Notes]
