== What's New

=== X.509 Authentication against Couchbase Server

Sync Gateway adds the ability to use x.509 certificates to authenticate against Couchbase Server 5.5 or higher. xref:release-notes.adoc#x-509-authentication-against-couchbase-server[Read more]

=== Continuous Logging

Continuous logging is a new feature in Sync Gateway 2.1 that allows the console log output to be separated from log files collected by Couchbase Support. xref:release-notes.adoc#continuous-logging[Read more]

xref:release-notes.adoc[Read more about the Sync Gateway 2.1 release]

== Compatibility Matrix

The table below summarizes the compatible versions of Sync Gateway with Couchbase Server.

[cols="4,1,1,1,1,1,1,1", options="header"]
|===
|
7+|Couchbase Server →

|Sync Gateway ↓
|4.0
|4.1
|4.5
|4.6
|5.0
|5.1
|5.5

|1.3

`feed_type: "DCP"`
|✖
|✖
|✖
|✖
|✔
|✔
|✔

|1.4

`feed_type: "DCP"`
|✖
|✖
|✖
|✖
|✔
|✔
|✔

|1.5

`shared_bucket_access: false`
|✔
|✔
|✔
|✔
|✔
|✔
|✔

|1.5

`shared_bucket_access: true`
|✖
|✖
|✖
|✖
|✔
|✔
|✔

|2.0

`shared_bucket_access: false`
|✔
|✔
|✔
|✔
|✔
|✔
|✔

|2.0

`shared_bucket_access: true`
|✖
|✖
|✖
|✖
|✔
|✔
|✔

|2.1

`shared_bucket_access: false`

`use_views: false`
|✔
|✔
|✔
|✔
|✔
|✔
|✔

|2.1

`shared_bucket_access: true`
|✖
|✖
|✖
|✖
|✔
|✔
|✔

|2.1

`use_views: true`
|✖
|✖
|✖
|✖
|✖
|✖
|✔
|===

For all of the above, the Couchbase Server https://developer.couchbase.com/documentation/server/current/architecture/core-data-access-buckets.html[bucket type] must be *Couchbase*. Usage of *Ephemeral* and *Memcached* buckets with Couchbase Mobile is not supported.