= What's New
:page-aliases: index
:page-status: {releaseStatus}
:page-role: -toc panes
:page-content: contextual
include::partial$_attributes-local.adoc[]

== Release 2.8
Sync Gateway 2.7 introduces significant performance and resilience enhancements which provide Enterprise-customers with:

[.pane__frames]

* *Inter Cluster Replication*
+
--
Adipisicing fugiat Lorem duis et non nulla nisi ad commodo fugiat ea. Eiusmod Lorem incididunt occaecat commodo qui fugiat ut eu consequat. Laborum incididunt amet adipisicing duis voluptate qui quis aliqua nulla eu laboris amet ex aliquip.

Read more ...
--
* *Another great feature*
+
--
Anim elit consectetur ex aute mollit deserunt esse aute nulla nostrud qui nulla ex. Exercitation sit ut ullamco esse irure eiusmod eiusmod. Minim sit quis reprehenderit qui commodo incididunt tempor.

Read more ...
--

[.pane__frames]

* *New mouse trap*
+
--
Cillum nostrud nisi elit veniam commodo nulla. Non veniam velit non labore commodo nisi qui sit enim officia. Nostrud in cupidatat sit ullamco. Ad amet eiusmod non nisi ipsum adipisicing aliquip esse. Magna pariatur aute pariatur adipisicing ipsum.

Read more ...
--
* *GSI*
+
--
Eu exercitation do anim velit voluptate magna veniam officia reprehenderit ut. Occaecat eu aliqua irure aliqua. Laboris laboris proident occaecat enim laborum quis ex nisi fugiat.
Duis ea aliquip veniam cillum ut occaecat dolor. Labore fugiat excepteur voluptate duis.

Read more ....
--

[.pane__frames]

* *CSI*
+
--
Eu exercitation do anim velit voluptate magna veniam officia reprehenderit ut. Occaecat eu aliqua irure aliqua. Laboris laboris proident occaecat enim laborum quis ex nisi fugiat.
Duis ea aliquip veniam cillum ut occaecat dolor. Labore fugiat excepteur voluptate duis.

Read more ....
--

* Fixes and enhancements
+
This release also contains a number of bug fixes and enhancements for Sync Gateway.
+
Find out more in the xref:release-notes.adoc[Release Notes], which also include details of the current maintenance release (SGW: {version-full}).

