= What's New
:page-layout: article
:page-content-type: reference
:page-status:
:page-edition:
:page-role: -toc
:description: Couchbase Sync Gateway -- What's new in the latest release
:keywords: edge nosql api synchronization replication

include::ROOT:partial$_std-hdr-sgw.adoc[]

:param-abstract: This content covers the new features and behaviors introduced in Sync Gateway {version}
:param-related: {xref-sgw-pg-release-notes}
include::partial$block-abstract.adoc[]

== Release 2.8

In addition to significant performance and resilience enhancements Sync Gateway 2.8 introduces enhanced support for Inter-Sync Gateway Replication and a developer preview of metrics API that allows integration with Prometheus/Grafana.

=== Inter-Sync Gateway Replication

include::partial$pn-change-log-content.adoc[tag=2-8-0-inter-sync-gateway]


=== Metrics API - developer preview
include::partial$pn-change-log-content.adoc[tag=2-8-0-metrics]

=== Fixes and enhancements

This release also contains a number of bug fixes and enhancements for Sync Gateway.

Highlights include the addition of a new OpenID Connect (OIDC) library, which broadens Sync Gateway's support of OIDC providers.
This includes enabling developers to configure token attributes to use as the Sync Gateway user name ({xref-sgw-pg-config-properties-databases-oidc-username-claim}).

Read More . . . {xref-sgw-pg-release-notes}  |  {xref-sgw-pg-release-notes-enhancements}
