= Sync Gateway

Sync Gateway: 

* Maintains up-to-date copies of documents where users need them. On mobile devices for instant access and on servers in data centers for reasons such as synchronizing documents, sharing documents, and loss-protection. Mobile apps create, update, and delete files locally, Sync Gateway takes care of the rest. 
* Provides access control, ensuring that users can only access documents to which they should have access. 
* Ensures that only _relevant_ documents are synced. Sync Gateway accomplishes this by examining document and applying business logic to decide whether to assign the documents to channels. Access control and ensuring that only relevant documents are synced are achieved through the use of _channels_ and the __sync function__. 

== Compatibility Matrix

The table below summarizes the compatible versions of Sync Gateway with Couchbase Server.

[cols="4,1,1,1,1,1,1,1", options="header"]
|===
|
7+|Couchbase Server →

|Sync Gateway ↓
|4.0
|4.1
|4.5
|4.6
|5.0
|5.1
|5.5

|1.3

`feed_type: "DCP"`
|✖
|✖
|✖
|✖
|✔
|✔
|✔

|1.4

`feed_type: "DCP"`
|✖
|✖
|✖
|✖
|✔
|✔
|✔

|1.5

`shared_bucket_access: false`
|✔
|✔
|✔
|✔
|✔
|✔
|✔

|1.5

`shared_bucket_access: true`
|✖
|✖
|✖
|✖
|✔
|✔
|✔

|2.0

`shared_bucket_access: false`
|✔
|✔
|✔
|✔
|✔
|✔
|✔

|2.0

`shared_bucket_access: true`
|✖
|✖
|✖
|✖
|✔
|✔
|✔
|===

For all of the above, the Couchbase Server https://developer.couchbase.com/documentation/server/current/architecture/core-data-access-buckets.html[bucket type] must be *Couchbase*. Usage of *Ephemeral* and *Memcached* buckets with Couchbase Mobile is not supported.