= Manage Audit Logs
:page-edition: Enterprise
:description: Administrators can manage audit logs to track operational irregularities and to support regulatory and security compliance standards.

[abstract]
{description}

== Enabling Audit Logging

Audit Logging on Sync Gateway is opt-in functionality and is disabled by default.
You can enable audit logging by setting the `enabled` property to true in your config file.

== Audit Log Configuration

There are two main ways in which you can configure audit logs:

* Via the bootstrap or startup config.
This will affect the global configuration.

* Via the database config.
This will affect the configuration on a per database basis.

=== Configuration with the Startup Config

Below you can find the minimal configuration required in your `startup_config` file to enable audit logging.

[source, json, indent=0]
----

"logging": {
    "audit": {
	  “audit_log_file_path”: “/path/to/file.log”,
    “enabled”: true,
    }
}

----

NOTE: Configuration via the startup config will affect your configuration globally.

To successfully configure audit logging, you must set a file path for your audit logs and set the `enabled` parameter to `true`.
Enabling and disabling audit logging is handled by the Admin REST API at a cluster and Sync Gateway database level.

=== Configuration with the Database Config

You can alter the configuration per Sync Gateway database by changing the database config.

Below is an example of a simple database configuration.

[source, json]
----
{
  "bucket": "todo", 
  "num_index_replicas": 0,
  “logging”: {
               “audit”: {
                          "enabled”: false,
                          “enabled_events”: [],
                          “disabled_users”: [
                                              {
                                                “name”: “user1”,
                                                “domain”: “sgw”
                                              }
                                            ],
                        },
  “disabled_roles”: [
                      {
                        “name”: “role1”,
                        “domain”: “sgw”
                      }
                    ],
               },
}  
----

IMPORTANT: If you enable audit logging in your startup config it is enabled globally.
Conversely, it is important to note that if audit logging is enabled in your database config but *not* your startup config, no audit logging will occur.

Couchbase recommends you only use configuration at the database level if you wish to alter your settings per database. 

== Filtering Audit Logs

You can filter audit logs to customize events that are stored in the log file. 
You can alter the following to affect events stored in the log file:

* Enabling and disabling users - This affects all events related to a specified user.
If a given user is disabled, no audit events from the user will be logged.

* Enabling and disabling events - This affects the specified events globally.
If a given event is disabled, it will not be logged regardless of the user.

NOTE: If an audit event has `DefaultEnabled` set to `true`, it does not need to be explicitly listed in the `enabled_events: []` array.
See xref:audit-log-events.adoc[] for more information on specific audit events.

=== Enabled and Disabled Events

Events can be enabled per database or globally.

The example below shows a section of a global startup config which would enable Public HTTP API requests and Public API user authenticated events only.

[source, json]
----
"logging": {
             "audit": {
                        “audit_log_file_path”: “/path/to/file.log”,
                        “enabled”: true,
                        “enabled_events”: [53270, 53280]
                      }
            }
----

Enabling the events at runtime without modifying the entire database

You can enable events at runtime without modifying the entire database using the following HTTP request methods:

* `GET /{db}/_config/audit`
* `PUT /{db}/_config/audit (replace)`
* `POST /{db}/_config/audit (upsert)`

These request methods apply changes at the database level, a possible use case is that you can modify the `enabled` parameter to disable all events for the database.

The examples below show two ways to specify audit events.


The first example enables the `Public HTTP API request` and `Public API user authenticated` events.

[source, json]
----
{
	“enabled”: true,
  “enabled_events”: [{“53270”: true, “53280”: true]
}
----

If you wanted to enable one event and disable another:

[source, json]
----
{
	“enabled”: true,
  “enabled_events”: [{“53270”: true, “53280”: false]
}
----

=== Disabled_users/disabled_roles fields (TODO)

These fields represent certain users for whom audit events will not occur. This might be something like an administrative user who is performing automated actions. There are two types of users:

- Users/roles that are created by Sync Gateway, these have to have ”domain”: “sgw” attached. They are https://docs.couchbase.com/sync-gateway/current/access-control-concepts.html#lbl-sgw-users
- Users that are are RBAC controlled https://docs.couchbase.com/sync-gateway/current/access-control-concepts.html#lbl-rbac-users - these would have ”domain”: “cbs” attached to them

== See Also 

* xref:audit-logging.adoc[]

* xref:audit-log-events.adoc[]

* xref:sgcollect-info.adoc[]

* xref:rest-api-admin.adoc[]

* xref:rest_api_admin_static.adoc[]
