= Release Notes
:page-layout: article
:page-status: beta
:page-roles: -toc
:page-aliases: release-notes

include::partial$_attributesLocal.adoc[]

:jira-url: {url-jira}
:natt: None at this time
:ke: Known issues
:fixed: Fixed at this Release
:enh: Enhancements
:nftr: New Features
:api: API Changes

{component-sgw}

[abstract]
--
This content provides release information pertaining to Sync Gateway {page-component-version} and subsequent maintenance releases.
--

== 2.8.0 -- 99 month 2020
<<Enhancements>> *|* <<Congiguration Changes,Config Changes>> *|* <<Support Notices>> *|* <<Known issues, Known Issues>> *|* <<Fixed at this Release,Fixed>>


=== Enhancements

Excepteur eiusmod est aliqua est non quis id sint. Incididunt in deserunt ex sint. Laboris proident ea qui deserunt sint sint sunt minim sit. Id anim occaecat culpa non amet duis cupidatat sit sint cillum cillum pariatur mollit.

Occaecat consequat occaecat do velit nostrud cupidatat ex exercitation nostrud anim reprehenderit qui aute. Sunt nisi excepteur est esse enim excepteur ipsum laboris non nostrud consequat sunt ex duis. Amet veniam irure pariatur consequat deserunt quis ad irure incididunt ea. Consequat aliqua quis esse ex mollit do cillum reprehenderit dolor est et elit cupidatat. Minim aliquip Lorem exercitation sint esse commodo aliquip id eiusmod.

Anim deserunt id ex pariatur labore reprehenderit exercitation amet reprehenderit ea sint. Ipsum excepteur sunt nisi nulla quis id adipisicing est in ea ullamco. Laborum quis nisi et ut dolore ullamco do. Minim adipisicing aliquip sunt officia commodo mollit non velit. Deserunt duis velit pariatur aliqua. Qui laborum dolor enim sit nulla in velit dolor sit adipisicing.

=== Configuration Changes
Sint id esse consectetur voluptate minim dolor pariatur anim culpa adipisicing sint aliqua ullamco sunt. Aliquip aliquip anim id sit incididunt nisi. Eu quis labore elit ad laboris proident ea cillum esse laborum. Culpa voluptate est excepteur mollit et esse incididunt ea nulla dolore. Minim quis exercitation in in exercitation nulla fugiat in incididunt velit elit est.

Amet labore tempor dolor amet anim do laboris. Ex ut consectetur consectetur aliqua aliqua reprehenderit sint laborum proident ex voluptate. Sunt deserunt sunt nisi anim minim ipsum sunt esse minim pariatur eiusmod exercitation ullamco. Ullamco officia commodo adipisicing velit nulla aliqua. Nulla ullamco in reprehenderit id commodo minim do id commodo id reprehenderit. Non sit pariatur amet ad sint irure officia. Occaecat aliqua et eu pariatur tempor.

=== Compatibility

https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.nf0vv4c38gr


=== Support Notices
// https://issues.couchbase.com/browse/DOC-6462 Support Notices

==== Sync Gateway

*Deprecation Notices*

// https://issues.couchbase.com/browse/DOC-6461 Deprecation notices

* Deprecate pre-H2 replication DB config method https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.u10lcuiyz5d0

*End of Life Notices*

* SG Replicate 1.0 https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.nwllc3an70af

*Constrants*

// https://issues.couchbase.com/browse/DOC-6462 Support Notices

* Replication between two remote databases https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.nwllc3an70af


=== {ke}

* Enim ipsum duis cillum pariatur.
* Enim ipsum duis cillum pariatur.
* Enim ipsum duis cillum pariatur.



=== {fixed}

* Enim ipsum duis cillum pariatur.
* Enim ipsum duis cillum pariatur.
* Enim ipsum duis cillum pariatur.


== Related Content
====
* How-to:
** xref:{component-sgw}::upgrade.adoc[Upgrading to {page-component-version}]
* Learn more:
** xref:{component-sgw}::pn-compatibility.adoc[Compatibility]
** xref:{component-sgw}::pn-supported-os.adoc[Supported OS]
** xref:{component-sgw}::pn-release-notes-archive.adoc[Release Note Archives]
** link:{url-cb-tutorials}[Couchbase Tutorials]
** link:{url-cb-blog-sgw}[Couchbase Blog]
====


