= Release Notes
:url-issues-sync: https://github.com/couchbase/sync_gateway/issues

== 2.1

*Deprecations*

The following features are being deprecated and will be unsupported in an upcoming version of Sync Gateway.

* *Bucket shadowing* has been deprecated since 1.4 and has now become unsupported.
The recommended approach to perform operations on a bucket dedicated to Couchbase Mobile is to enable xref:shared-bucket-access.adoc[shared bucket access].

*Performance Improvements*

- {url-issues-sync}/716[*#716*] Use sync.atomic to synchronize logging logLevel
- {url-issues-sync}/2396[*#2396*] SyncGateway restart after node automatic failover is taking more time
- {url-issues-sync}/2563[*#2563*] Allow callers to provide current value to WriteUpdateWithXattr
- {url-issues-sync}/3664[*#3664*] Unnecessary DCP reprocessing on SG restart

*Enhancements*

- {url-issues-sync}/1021[*#1021*] Enable log level to be set via SG config
- {url-issues-sync}/1652[*#1652*] Differentiate logging between standard out and standard error
- {url-issues-sync}/2664[*#2664*] Move to GSI for internal query operations
- {url-issues-sync}/3119[*#3119*] Avoid design doc/view creation when already present
- {url-issues-sync}/3157[*#3157*] Uptake the latest gocb for ipv6 support
- {url-issues-sync}/3259[*#3259*] Log Redaction
- {url-issues-sync}/3276[*#3276*] Sync Function requireAdmin() functionality
- {url-issues-sync}/3329[*#3329*] Support authenticating against CBS using x.509 certificate
- {url-issues-sync}/3388[*#3388*] Include body hash in Sync Gateway import calculation 
- {url-issues-sync}/3508[*#3508*] Allow configuration of GoCB opTimeout value
- {url-issues-sync}/3526[*#3526*] 2.1.0- sg collect info - Show message if sync gateway is not running

*Bugs*

- {url-issues-sync}/2173[*#2173*] Go-couchbase 500 errors when rebalancing
- {url-issues-sync}/3425[*#3425*] Uptake fix for https://github.com/couchbaselabs/sync_gateway_admin_ui/issues/47
- {url-issues-sync}/3452[*#3452*] Sync Function expiry() fails if passed a constant numeric value 
- {url-issues-sync}/3475[*#3475*] prependChanges can result in multiple revisions for a doc in channel cache 
- {url-issues-sync}/3548[*#3548*] Windows logs are written to "Program Files (x86)" when running from "Program Files"

*Known Issues*

- {url-issues-sync}/3562[*#3562*] Sync Gateway requires Couchbase Server nodes to use the same SSL memcached port

== Upgrading

The upgrade, from using views to using Global Secondary Indexes and N1QL, happens automatically when starting a Sync Gateway 2.1 node in a cluster that was previously using views.
By default, Sync Gateway requires the Couchbase Server cluster to be running Couchbase Server 5.5, with at least two nodes running the Index Service.
If this is not the case, users must configure the `use_views` and/or `num_index_replicas` properties in their Sync Gateway configuration during upgrade.

Installation follows the same general approach used in 2.0.
On startup, Sync Gateway will check for the existence of the required indexes, and only attempt to create them if they do not already exist.

Then, Sync Gateway will wait until indexes are available before starting to serve requests.

Sync Gateway 2.1 will *not* automatically remove the previously used design documents.
Removal of the obsolete design documents is done via a call to the xref:admin-rest-api.adoc#/server/post\__post_upgrade[+/_post_upgrade+] endpoint in Sync Gateway`'s Admin REST API.
This endpoint can be run in preview mode (`?preview=true`) to see which design documents would be removed.
To summarize, the steps to perform an upgrade to Sync Gateway 2.1 are:

. Upgrade one node in the cluster to 2.1, and wait for it to be reachable via the REST API (for example at \http://localhost:4985/).
. Upgrade the rest of the nodes in the cluster.
. Clean up obsolete views:
** *Optional* Issue a call to `/_post_upgrade?preview=true` on any node to preview which design documents will be removed.
To upgrade to 2.1, expect to see "sync_gateway" and "sync_housekeeping" listed.
** Issue a call to `/post_upgrade` to remove the obsolete design documents.
The response should indicate that "sync_gateway" and "sync_housekeeping" were removed.
