= Release Notes
:jira-url: https://issues.couchbase.com/browse
:url-issues-sync: https://github.com/couchbase/sync_gateway/issues

== Deprecated Configurations

The following configuration properties are being deprecated in this release and will be removed in a future release.

- `adminUI`
- `configServer`
- `databases.$db.feed_type`
- `pretty`
- `profileInterface`
- `log` (superseded by `logging`)
- `logFilePath` (superseded by `logging.log_file_path`)

The following configuration values are being deprecated in this release and will be removed in a future release.

- The `walrus` value on the `databases.$db.bucket` property is being deprecated. Sync Gateway instances using `walrus` for development should connect to a running instance of Couchbase Server.

== New Features

== Iridium

*Performance Improvements*

- https://github.com/couchbase/sync_gateway/issues/801[*#801*] Analyze
performance of single node with ForestDB bucket
- https://github.com/couchbase/sync_gateway/issues/3446[*#3446*] Resolve
performance issues related to go 1.8 -> 1.10 upgrade

*Enhancements*

- https://github.com/couchbase/sync_gateway/issues/52[*#52*] Channel
inspection API
- https://github.com/couchbase/sync_gateway/issues/98[*#98*] Ability to
assign ``default channels'' to new users
- https://github.com/couchbase/sync_gateway/issues/1107[*#1107*] Refresh
distributed index on _resync
- https://github.com/couchbase/sync_gateway/issues/1297[*#1297*] Do
automatic tuning of num_shards based on cluster topology
- https://github.com/couchbase/sync_gateway/issues/1316[*#1316*] Support
_doc_ids filter when using distributed index
- https://github.com/couchbase/sync_gateway/issues/1401[*#1401*] Ability
to put db offline via config
- https://github.com/couchbase/sync_gateway/issues/1619[*#1619*] SGW not
return with auth error to WebSocket _changes req after change user’s
credentials
- https://github.com/couchbase/sync_gateway/issues/1797[*#1797*] Include
channel info when get or bulk_get documents
- https://github.com/couchbase/sync_gateway/issues/1968[*#1968*] Ability
to take sg-accel offline

*Bugs*

- https://github.com/couchbase/sync_gateway/issues/577[*#577*]
Can not remove the sync_gateway service on MacOS
- https://github.com/couchbase/sync_gateway/issues/3800[*#3800*] Deprecate
configuration settings that will be removed from SG Mercury

*Known Issues*

- https://github.com/couchbase/sync_gateway/issues/1264[*#1264*] Sync
Gateway memory usage climbs continously
- https://github.com/couchbase/sync_gateway/issues/3562[*#3562*] Sync
Gateway requires Couchbase Server nodes to use the same SSL memcached
port
