= SG release notes

== Deprecation notices

The following features are being deprecated and will be unsupported in
an upcoming version of Sync Gateway.

* *Bucket shadowing* has been deprecated since 1.4 and will be
unsupported in an upcoming version of Couchbase Mobile. The recommended
approach to perform operations on the bucket dedicated to Couchbase
Mobile is to use the Sync Gateway REST API.

== New Features

* *Shared bucket access*
* *SSL and Multi-URL support*

== Notable Changes

* The Design Document definition used internally by Sync Gateway has
changed which may incur some application downtime during the upgrade.
See
xref:upgrade.adoc#view-indexing[view indexing].
* *Revs Limit lower limit:* The
xref:config-properties.adoc#1.5/databases-foo_db-revs_limit[databases.foo_db.revs_limit]
property now has a minimum value. See the API reference for more detail.
* *Rev Tree endpoint:* The
xref:admin-rest-api.adoc[+/{db}/_revtree/{doc}+]
endpoint returns the revision tree in dot syntax for the specified
document. This endpoint is not officially supported and should only be
used for troubleshooting and debugging purposes.

== 1.5.1

*Bugs*

* https://github.com/couchbase/sync_gateway/issues/3078[*#3078*] Channel
view results not being prepended to channel cache
* https://github.com/couchbase/sync_gateway/issues/3098[*#3098*] Error
migrating tombstoned documents:
`Did not update document "DOC_ID" w/ xattr: invalid arguments`

== 1.5 release

*Performance Improvements*

* https://github.com/couchbase/sync_gateway/issues/2218[*#2218*]
SyncGateway/SyncGateway replicator memory keeps growing continuosly and
resulting in OOM crash
* https://github.com/couchbase/sync_gateway/issues/2651[*#2651*] SG gets
killed due to excessive memory usage with continuous doc update

*Enhancements*

* https://github.com/couchbase/sync_gateway/issues/473[*#473*] Implement
Mobile Convergence to enable Sync Gateway to directly access Couchbase
Server buckets
* https://github.com/couchbase/sync_gateway/issues/1462[*#1462*] Sync
Gateway Accelerator is reporting itself as Sync Gateway
* https://github.com/couchbase/sync_gateway/issues/2151[*#2151*] The
/\{db}/_changes?include_docs=true request shouldn’t return _user/user
docs
* https://github.com/couchbase/sync_gateway/issues/2259[*#2259*] Add
support for RHEL in service install scripts

*Bugs*

* https://github.com/couchbase/sync_gateway/issues/2218[*#2218*]
SyncGateway/SyncGateway replicator memory keeps growing continuosly and
resulting in OOM crash
* https://github.com/couchbase/sync_gateway/issues/2367[*#2367*]
Omitting the logFilePath property in the logging configuration of Sync
Gateway results in a null pointer exception crash
* https://github.com/couchbase/sync_gateway/issues/2381[*#2381*] SG
Replicate stops when an attachment with no content type is replicated
* https://github.com/couchbase/sync_gateway/issues/2400[*#2400*] SG
collect info is not case sensitive on the config’s logFilePath property
* https://github.com/couchbase/sync_gateway/issues/2421[*#2421*] Discard
new rev sequence if it is less than a docs current rev sequence, to
avoid issues with caching
* https://github.com/couchbase/sync_gateway/issues/2500[*#2500*] Webhook
event not fired when using bucket shadowing
* https://github.com/couchbase/sync_gateway/issues/2565[*#2565*]
Non-empty oldDoc being sent to sync function during import
* https://github.com/couchbase/sync_gateway/issues/2626[*#2626*] Active
changes feeds not notified when deferred sequences get cached
* https://github.com/couchbase/sync_gateway/issues/2651[*#2651*] SG gets
killed due to excessive memory usage with continuous doc update
* https://github.com/couchbase/sync_gateway/issues/2677[*#2677*] Unable
to install SG 1.5.0 on Win 10

*Known issues*

* https://github.com/couchbase/sync_gateway/pull/2744[*#2744*] Failures
due to multi operation deletes
* https://github.com/couchbaselabs/sync-gateway-accel/issues/149[*#149*]
Changes missing on Sync Gateway Accelerator re-shard
* https://github.com/couchbase/sync_gateway/issues/2068[*#2068*] Update
user doc sequence for access-based channel grants
* https://github.com/couchbaselabs/sync-gateway-accel/issues/160[*#160*]
The `_doc_ids` changes feed filter doesn’t work with Accelerator