= Release Notes
:jira-url: https://issues.couchbase.com/browse
:url-issues-sync: https://github.com/couchbase/sync_gateway/issues

== 2.6.1

*Fixed in this Release*

- {jira-url}/CBG-530[*CBG-530*] New attachment metadata not preserved on CAS retry during document update
- {jira-url}/CBG-514[*CBG-514*] running sgcollect_info on command with root privileges is overriding bin/sync_gateway file on MacOS
- {jira-url}/CBG-502[*CBG-502*] x.509 broken due to deprecated CertificateAuthenticator

== 2.6.0

*Deprecated Configs*

* The following configuration properties are being deprecated in this release and will be removed in a future release:
** `adminUI`
** `configServer`
** `databases.$db.feed_type`
** `pretty`
** `profileInterface`
** `log` (superseded by `logging`)
** `logFilePath` (superseded by `logging.log_file_path`)
* The `walrus` value on the `databases.$db.bucket` property is being deprecated. Sync Gateway instances using `walrus` for development should connect to a running instance of Couchbase Server.

*New Features*

* Cache Enhancements
+
xref:index.adoc[Read more]

*Enhancements*

- {jira-url}/CBG-260[*CBG-260*] Add configurable minimum TLS version
- {jira-url}/CBG-220[*CBG-220*] Limit total size of rotated logs

*Fixed in this Release*

- {jira-url}/CBG-449[*CBG-449*] _removed entry not sent with delta sync
- {jira-url}/CBG-370[*CBG-370*] Sync gateway fails to start
- {jira-url}/CBG-364[*CBG-364*] Odd SG Installation errors
- {jira-url}/CBG-363[*CBG-363*] Return HTTP 413 when server rejects document due to size
- {jira-url}/CBG-362[*CBG-362*] Inconsistent handling between views and N1QL for tombstone removals
- {jira-url}/CBG-357[*CBG-357*] GoCB Bucket Incr amt=0 logic not taking 'def' into account
- {jira-url}/CBG-342[*CBG-342*] GoCB Bucket Incr amt=0 logic not handling errors correctly
- {jira-url}/CBG-324[*CBG-324*] Blip messages double-tagging user for redaction
- {jira-url}/CBG-321[*CBG-321*] Improve sg-replicate logging integration
- {jira-url}/CBG-309[*CBG-309*] Don't log expected REST errors to sg_error.log
- {jira-url}/CBG-306[*CBG-306*] Avoid panics as an error handling mechanism
- {jira-url}/CBG-288[*CBG-288*] Investigate TestN1qlQuery failures
- {jira-url}/CBG-286[*CBG-286*] SUBDOC operation attempted when server doesn't support them
- {jira-url}/CBG-284[*CBG-284*] Retry loops for bucket update ops have no backoff and no max retry count
- {jira-url}/CBG-280[*CBG-280*] Syncgateway doesn't import all documents while importing 50M docs ( build 2.1.3-4)
- {jira-url}/CBG-279[*CBG-279*] go-blip leaks nextFrameToSend goroutine under aborted multi-frame send
- {jira-url}/CBG-265[*CBG-265*] Post Upgrade fails to remove 2.0 era design docs
- {jira-url}/CBG-264[*CBG-264*] Post Upgrade "fails" in a cluster with no query nodes
- {jira-url}/CBG-253[*CBG-253*] Unused bulk_docs reserved sequences may not be released
- {jira-url}/CBG-225[*CBG-225*] Unresponsive REST API on startup
- {jira-url}/CBG-221[*CBG-221*] Admin/User views cannot handle both xattr and non-xattr simultaneously
- {jira-url}/CBG-189[*CBG-189*] Compact() shouldn't trigger import errors
- {jira-url}/CBG-159[*CBG-159*] CouchbaseServerVersion should use clusterCompatibility version

*Known Issues*

- {jira-url}/CBG-463[*CBG-463*] Potential feedback loop when replicating large attachments
- {jira-url}/CBG-317[*CBG-317*] network errors while getting bulk get with multi channel with server ssl enabled
- {jira-url}/CBG-502[*CBG-502*] x.509 certificate authentication broken due to deprecated CertificateAuthenticator
