= Release Notes
:jira-url: https://issues.couchbase.com/browse
:url-issues-sync: https://github.com/couchbase/sync_gateway/issues

*Deprecations*

The following features are being deprecated and will be unsupported in an upcoming version of Sync Gateway.

* *Bucket shadowing* has been deprecated since 1.4 and has now become unsupported.
The recommended approach to perform operations on a bucket dedicated to Couchbase Mobile is to enable xref:shared-bucket-access.adoc[shared bucket access].
* The xref:logging.adoc#log-rotation-deprecated[log rotation configuration] is being deprecated in favor of the xref:logging.adoc#continuous-logging[continuous logging configuration].

== 2.1.2

- {url-issues-sync}/3822[*#3822*] Rewrite and guard against non-covering queries

== Iridium

*Performance Improvements*

- https://github.com/couchbase/sync_gateway/issues/801[*#801*] Analyze
performance of single node with ForestDB bucket
- https://github.com/couchbase/sync_gateway/issues/3446[*#3446*] Resolve
performance issues related to go 1.8 -> 1.10 upgrade

*Enhancements*

- https://github.com/couchbase/sync_gateway/issues/52[*#52*] Channel
inspection API
- https://github.com/couchbase/sync_gateway/issues/98[*#98*] Ability to
assign ``default channels'' to new users
- https://github.com/couchbase/sync_gateway/issues/1107[*#1107*] Refresh
distributed index on _resync
- https://github.com/couchbase/sync_gateway/issues/1297[*#1297*] Do
automatic tuning of num_shards based on cluster topology
- https://github.com/couchbase/sync_gateway/issues/1316[*#1316*] Support
_doc_ids filter when using distributed index
- https://github.com/couchbase/sync_gateway/issues/1401[*#1401*] Ability
to put db offline via config
- https://github.com/couchbase/sync_gateway/issues/1619[*#1619*] SGW not
return with auth error to WebSocket _changes req after change user’s
credentials
- https://github.com/couchbase/sync_gateway/issues/1797[*#1797*] Include
channel info when get or bulk_get documents
- https://github.com/couchbase/sync_gateway/issues/1968[*#1968*] Ability
to take sg-accel offline

*Bugs*

- https://github.com/couchbase/sync_gateway/issues/577[*#577*]
Can not remove the sync_gateway service on MacOS
- https://github.com/couchbase/sync_gateway/issues/3800[*#3800*] Deprecate
configuration settings that will be removed from SG Mercury

*Known Issues*

- https://github.com/couchbase/sync_gateway/issues/1264[*#1264*] Sync
Gateway memory usage climbs continously
- https://github.com/couchbase/sync_gateway/issues/3562[*#3562*] Sync
Gateway requires Couchbase Server nodes to use the same SSL memcached
port

== 2.1.1

*Enhancements*

- {url-issues-sync}/1658[*#1658*] Purge doesn’t remove cached documents

*Bugs*

- {url-issues-sync}/3692[*#3692*] Failure to write old revision can result in malformed revision body in revtree
- {url-issues-sync}/3721[*#3721*] "_changes" feed not 100% reliable
- {url-issues-sync}/3724[*#3724*] Resync with xattrs causes warnings for every no-op
- {url-issues-sync}/3738[*#3738*] 2.0 replication doesn’t notify clients when unable to send rev message
- {url-issues-sync}/3740[*#3740*] Persist temporary revision body backups on import
- {url-issues-sync}/3756[*#3756*] DCP Feed does not seed from all nodes

*Known Issues*

- {jira-url}/MB-31990[*MB-31990*] and {jira-url}/MB-32120[*MB-32120*] Query failures when querying xattrs with non-covering index.
* *Workaround:* disable xref:2.1@index.adoc#guaranteed-availability[GSI indexing].
- {url-issues-sync}/3822[*#3822*] Sync Gateway channel queries to the Couchbase Server may time out.
* *Workaround:* disable xref:2.1@index.adoc#guaranteed-availability[GSI indexing].

== 2.1

*Performance Improvements*

- {url-issues-sync}/716[*#716*] Use sync.atomic to synchronize logging logLevel
- {url-issues-sync}/2396[*#2396*] SyncGateway restart after node automatic failover is taking more time
- {url-issues-sync}/2563[*#2563*] Allow callers to provide current value to WriteUpdateWithXattr
- {url-issues-sync}/3664[*#3664*] Unnecessary DCP reprocessing on SG restart

*Enhancements*

- {url-issues-sync}/1021[*#1021*] Enable log level to be set via SG config
- {url-issues-sync}/1652[*#1652*] Differentiate logging between standard out and standard error
- {url-issues-sync}/2664[*#2664*] Move to GSI for internal query operations
- {url-issues-sync}/3119[*#3119*] Avoid design doc/view creation when already present
- {url-issues-sync}/3157[*#3157*] Uptake the latest gocb for ipv6 support
- {url-issues-sync}/3259[*#3259*] Log Redaction
- {url-issues-sync}/3276[*#3276*] Sync Function requireAdmin() functionality
- {url-issues-sync}/3329[*#3329*] Support authenticating against CBS using x.509 certificate
- {url-issues-sync}/3388[*#3388*] Include body hash in Sync Gateway import calculation
- {url-issues-sync}/3508[*#3508*] Allow configuration of GoCB opTimeout value
- {url-issues-sync}/3526[*#3526*] 2.1.0- sg collect info - Show message if sync gateway is not running

*Bugs*

- {url-issues-sync}/2173[*#2173*] Go-couchbase 500 errors when rebalancing
- {url-issues-sync}/3425[*#3425*] Uptake fix for https://github.com/couchbaselabs/sync_gateway_admin_ui/issues/47
- {url-issues-sync}/3452[*#3452*] Sync Function expiry() fails if passed a constant numeric value
- {url-issues-sync}/3475[*#3475*] prependChanges can result in multiple revisions for a doc in channel cache
- {url-issues-sync}/3548[*#3548*] Windows logs are written to "Program Files (x86)" when running from "Program Files"

*Known Issues*

- {url-issues-sync}/3562[*#3562*] Sync Gateway requires Couchbase Server nodes to use the same SSL memcached port
