= SG release notes

== New features

* xref:accelerator.adoc[Sync Gateway Accelerator]
* xref:deployment-considerations.adoc#built-in-log-rotation[Log rotation]

== Notable Changes

* The Design Document definition used internally by Sync Gateway
Accelerator has changed which may incur some application downtime during
the upgrade. See
xref:upgrade.adoc#view-indexing[view indexing].

== Deprecation notices

The following features are being deprecated in 1.4 and will be
unsupported in an upcoming version (2.x) of Couchbase Mobile.

* *Bucket shadowing* is being deprecated in 1.4 and will be unsupported
in an upcoming version (2.x) of Couchbase Mobile. The recommended
approach to perform operations on the bucket dedicated to Couchbase
Mobile is to use the Sync Gateway REST API.

== 1.4.1 release

*Enhancements*

* https://github.com/couchbase/sync_gateway/issues/2373[*#2373*] Add
sample config for SG running with Accel
* https://github.com/couchbase/sync_gateway/issues/2428[*#2428*] Avoid
document body unmarshalling on changes requests

*Bugs*

* https://github.com/couchbase/sync_gateway/issues/1518[*#1518*] Data
races detected in channel_cache.go
* https://github.com/couchbase/sync_gateway/issues/2364[*#2364*] Omit
doc during Changes+ logging
* https://github.com/couchbase/sync_gateway/issues/2365[*#2365*] Account
for unused sequences after CAS retry and subsequent cancel
* https://github.com/couchbase/sync_gateway/issues/2427[*#2427*] Data
race in trimEncodedRevisionsToAncestor

== 1.4 release

*Performance Improvements*

* https://github.com/couchbase/sync_gateway/issues/1514[*#1514*] Run
long-running performance tests against 1.4

*Enhancements*

* https://github.com/couchbase/sync_gateway/issues/1713[*#1713*]
[sg-accel] Use reference counts to track active channels
* https://github.com/couchbase/sync_gateway/issues/1925[*#1925*] HTTP
basic auth for webhooks
* https://github.com/couchbase/sync_gateway/issues/2098[*#2098*] Upgrade
build to go 1.7.1
* https://github.com/couchbase/sync_gateway/issues/2160[*#2160*] Add log
rotation capabilities into Sync Gateway
* https://github.com/couchbase/sync_gateway/issues/2255[*#2255*] Update
sgcollect_info to collect logs defined logging config
* https://github.com/couchbase/sync_gateway/issues/2298[*#2298*] Update
sgcollect_info to capture rotated logs

*Bugs*

* https://github.com/couchbase/sync_gateway/issues/1529[*#1529*]
Longpoll `_changes` request that returns no results, returns invalid
sequence number for last_seq
* https://github.com/couchbase/sync_gateway/issues/1865[*#1865*] One
shot replication of granting access doc can lead to miss documents
* https://github.com/couchbase/sync_gateway/issues/1890[*#1890*] Calling
db `_online` when CBS bucket is not available results in ``no such
database'' even when CBS bucket is available again
* https://github.com/couchbase/sync_gateway/issues/2080[*#2080*] Startup
error when config includes unsupported/user_views
* https://github.com/couchbase/sync_gateway/issues/2084[*#2084*] Update
Windows install folder for sg_accel
* https://github.com/couchbase/sync_gateway/issues/2102[*#2102*] Protect
against empty doc body in handlePutDoc
* https://github.com/couchbase/sync_gateway/issues/2139[*#2139*]
Sg_accel packages should use example config from sync-gateway-accel repo
* https://github.com/couchbase/sync_gateway/issues/2159[*#2159*] Handle
channel removal for coalesced feed updates
* https://github.com/couchbase/sync_gateway/issues/2187[*#2187*] SG
panic when upgrading keepalive http connection to WebSockets
* https://github.com/couchbase/sync_gateway/issues/2212[*#2212*] Channel
filtered sg-replicate stops due to channel removals
* https://github.com/couchbase/sync_gateway/issues/2270[*#2270*]
Starting sync gateway from command line does not always report the right
status

*Known Issues*

* https://github.com/couchbase/sync_gateway/issues/2341[*#2341*]
Channel_index bucket authentication requires username

*Sync Gateway Accelerator Known Issues*

* https://github.com/couchbaselabs/sync-gateway-accel/issues/17[Sync
Gateway Accel does not recover when removing a node from Couchbase
Server Cluster]: removing a node from the Couchbase Server Cluster can
cause Sync Gateway Accel to fail. Restarting the Accel node resolves the
issue.
* https://github.com/couchbaselabs/sync-gateway-accel/issues/10[Client
Rollback Support]: when Couchbase Server issues a rollback, Sync Gateway
Accel handles that rollback and rolls back the data in the channel index
bucket. However, we’re not yet invalidating client sequence/since values
that were sent to clients pre-rollback. As a result, clients may miss
documents written to sequence values in the rollback window.
* https://github.com/couchbaselabs/sync-gateway-accel/issues/126[Add
Index Document Inspection REST API]: the majority of the index bucket
contents are stored as binary documents. Getting a human-readable
version of the contents of these documents would be very useful while
debugging some types of issues.
