= SG Release Notes
:url-issues-sync: https://github.com/couchbase/sync_gateway/issues

== Deprecation Notices

The following features are being deprecated and will be unsupported in an upcoming version of Sync Gateway.

* *Bucket shadowing* has been deprecated since 1.4 and has now become unsupported.
The recommended approach to perform operations on a bucket dedicated to Couchbase Mobile is to enable xref:shared-bucket-access.adoc[shared bucket access].

== Upgrading

Starting in Sync Gateway 2.0, Sync Gateway's design documents include the version number in the design document name.
In this release for example, the design documents are named `_design/sync_gateway_2.0` and `_design/sync_housekeeping_2.0`.

On startup, Sync Gateway will check for the existence of these design documents, and only attempt to create them if they do not already exist.
Then, Sync Gateway will wait until views are available and indexed before starting to serve requests.
To evaluate this, Sync Gateway will issue a `stale=false&limit=1` query against the Sync Gateway views (channels, access and role_access).

If the view request exceeds the default timeout of 75s (which would be expected when indexing large buckets), Sync Gateway will log additional messages and retry.
The logging output will look like this:

[source,bash]
----
14:26:41.039-08:00 Design docs for current SG view version (2.0) found.
14:26:41.039-08:00 Verifying view availability for bucket default...
14:26:42.045-08:00 Timeout waiting for view "access" to be ready for bucket "default" - retrying...
14:26:42.045-08:00 Timeout waiting for view "channels" to be ready for bucket "default" - retrying...
14:26:42.045-08:00 Timeout waiting for view "role_access" to be ready for bucket "default" - retrying...
14:26:44.065-08:00 Timeout waiting for view "access" to be ready for bucket "default" - retrying...
14:26:44.065-08:00 Timeout waiting for view "role_access" to be ready for bucket "default" - retrying...
14:26:44.065-08:00 Timeout waiting for view "channels" to be ready for bucket "default" - retrying...
14:26:44.072-08:00 Views ready for bucket default.
----

Sync Gateway 2.0 will *not* automatically remove the previous design documents.
Removal of the obsolete design documents is done via a call to the new xref:admin-rest-api.adoc#/server/post\__post_upgrade[`_post_upgrade`] endpoint in Sync Gateway's Admin REST API.
This endpoint can be run in preview mode (`?preview=true`) to see which design documents would be removed.
To summarize, the steps to perform an upgrade to Sync Gateway 2.0 are:

. Upgrade one node in the cluster to 2.0, and wait for it to be reachable via the REST API (for example at \http://localhost:4985/).
. Upgrade the rest of the nodes in the cluster.
. Clean up obsolete views:
** *Optional* Issue a call to `_post_upgrade?preview=true` on any node to preview which design documents will be removed.
To upgrade to 2.0, expect to see "sync_gateway" and "sync_housekeeping" listed.
** Issue a call to `_post_upgrade` to remove the obsolete design documents.
The response should indicate that "sync_gateway" and "sync_housekeeping" were removed.

== GitHub issues

*Performance Improvements*

* {url-issues-sync}/1850[#1850] Avoid duplicate parsing of HTTP query string
* {url-issues-sync}/2871[#2871] Review bucket_gocb concurrent op limits
* {url-issues-sync}/2928[#2928] Optimize document unmarshalling for GetDoc
* {url-issues-sync}/3102[#3102] Use rev cache for _changes w/ include_docs

*Enhancements*

* {url-issues-sync}/744[#744] When try to put nonexistent document with rev: Document revision conflict
* {url-issues-sync}/1280[#1280] Auto-expire unused _local checkpoint documents
* {url-issues-sync}/1580[#1580] Use latest version of Otto
* {url-issues-sync}/2354[#2354] Windows service wrapper should write to a configurable stderr log file
* {url-issues-sync}/2709[#2709] Conflict-free mode (allow_conflicts:false)
* {url-issues-sync}/3015[#3015] Set document expiry via Sync Function
* {url-issues-sync}/3123[#3123] Log _sync:seq on startup
* {url-issues-sync}/3136[#3136] Inter-document compression in BLIP replicator
* {url-issues-sync}/3105[#3105] Set document expiry via Sync Function

*Bugs*

* {url-issues-sync}/1003[#1003] SG with bucket shadowing doesn't work properly after CB restarted
* {url-issues-sync}/1406[#1406] Feedtype=DCP not working sometimes
* {url-issues-sync}/1488[#1488] Rebalance -in a CBS node results in timeouts which manifests as empty changes feed
* {url-issues-sync}/2108[#2108] Missing sequences in _changes feed causing sg-replicate missing documents replication
* {url-issues-sync}/2223[#2223] Wrong name being set for users
* {url-issues-sync}/2371[#2371] Logging - "Replicate" works when in *.json but not when you PUT _logging
* {url-issues-sync}/2383[#2383] Channel cache missing data when request instantiating cache times out
* {url-issues-sync}/2410[#2410] SG gets into a 100% cpu state, where restart is the only recovery
* {url-issues-sync}/2441[#2441] RedHat/Centos 6 'initctl restart sync_gateway' does not work as expected
* {url-issues-sync}/2458[#2458] Log rotation skipping BLIP keys
* {url-issues-sync}/2717[#2717] SG Blip handler not reloading user channels
* {url-issues-sync}/3048[#3048] Panic when attempting to make invalid update to a conflicting document
* {url-issues-sync}/3049[#3049] Allow non-winning tombstone revisions when running with allow_conflicts=false
* {url-issues-sync}/3054[#3054] Mobile import of SDK write doesn't preserve expiry
* {url-issues-sync}/3107[#3107] _revisions property is stored in rev cache after new_edits=false write
* {url-issues-sync}/3108[#3108] Channel grant to role doesn't trigger reload of user context during write
* {url-issues-sync}/3146[#3146] One-shot changes requests should log timing information
* {url-issues-sync}/3174[#3174] sgcollect_info crashes if error encountered getting expvars
* {url-issues-sync}/3247[#3247] Ensure one-shot sg-replicate replications don't start until views are indexed
* {url-issues-sync}/3248[#3248] CloseNotifier handling not being used for continuous changes
* {url-issues-sync}/3307[#3307] Pushing yet-unseen tombstoned doc to Sync Gateway returns error in XATTR mode
* {url-issues-sync}/3344[#3344] Sync Gateway 1.5.1 panics when querying a view
