= Admin REST API
:page-aliases: refer/rest-api-admin.adoc
:page-layout: article
:page-status:
:page-edition:
:page-role: -toc
:page-content: Reference
:description: Description of the Sync Gateway Admin REST API

include::partial$_std-hdr-sgw.adoc[]

:param-abstract: Use the API explorer to find out more about Sync Gateway's endpoints by functionality.
:param-related: {rest-api--xref}  |  {rest-api-metrics--xref}  |  {rest-api-client-app--xref}
:topic-group: REST API
include::partial$block-abstract.adoc[]



== Introduction

The Admin REST API is for administrator use only, and hence is *not* accessible from the clients directly.

To allow users to access the Admin API up you need to create a Couchbase Server-based RBAC-user for them -- see: {rest-api-access--xref}

NOTE: For document changes sent to Sync Gateway through the Admin REST API, the Sync Function executes with *admin* privileges. +
Calls to `requireUser`, `requireAccess` and `requireRole` will be no-ops, and will always appear successful.


== API Explorer
The API explorer below groups all the endpoints by functionality.
You can click on a label to expand the list of endpoints and also generate a curl request for each endpoint.


swagger_ui::{attachmentsdir}/rest-api-admin.yaml[]


// swagger_ui::{attachmentsdir}/rest-api-admin-legacy.yaml[]

include::partial$block-related-content-api.adoc[]
