= Secure API Access
:page-aliases: start/rest-api-access.adoc, start/get-started-access-rest-api.adoc, get-started-access-rest-api.adoc
:page-partials:
:page-layout: article
:page-content: Reference
:description: Sync Gateway REST API Access

include::partial$_std-hdr-sgw.adoc[]

:param-abstract: Shows how to access Sync Gateway APIs
:param-related: {rest-api--xref}  |  {rest-api-admin--xref}  |  {rest-api-metrics--xref}
:topic-group: REST API
include::partial$block-abstract.adoc[]

:xref--pfx: {sgw--xref}:
:tls-encryption--xref: {sgw--xref}{secure-sgw-access--page}[enforcing TLS encryption]

== Overview

Sync Gateway provides secure access to its REST APIs, namely the:

* {rest-api--xref}
* {rest-api-admin--xref} -- for the administration and configuration of {sgw}
* {rest-api-metrics--xref} -- for the monitoring of {sgw} performance metrics

Each REST API is accessed through a different, <<lbl-port-cfg, user-specifiable>>, TCP port.
This makes it easy to control their physical exposure, perhaps to keep the Admin REST API secure behind your firewall.

{sgw-s} 3.0 brings additional optional but default layers of security through {tls-encryption--xref} for all API traffic and Couchbase Server Role-Based Access Control (RBAC) authorization and authentication for all <<lbl-secure-users,Admin and Metrics API users>>.

RBAC user authentication enables <<lbl-secure-users,Secure Remote Administrations>> of {sgw} clusters.
This is critical in cloud native deployments.
It provides secure and fine-grained access control.


== TLS

In 3.0, TLS is enabled by default.
It uses credentials provided with the request for authentication.
The only exception to this is the use of the Public REST API's _GUEST_ mode; which is for use in testing and-or development environments only.

For more on TLS, see: {tls-encryption--xref}.


[#lbl-secure-users]
== Secure Remote Administration
// tag::secremacc[]

Secure Remote Administration is *on* by default.

In order to submit Admin or Metrics REST API requests you should create specific Couchbase Server users for that purpose.
You will then provide a valid set of Couchbase Server credentials for these RBAC-users in each API request.

Authenticated users will have access to Admin and-or Metrics API functionality, application data and configuration settings.

// end::secremacc[]

The access-level will depend on the selected role. Currently available roles may vary depending on the Couchbase Server release version -- see <<tbl-ee-svr-sgw-roles>>. +

.{sgw-s} role availability by release
[#tbl-ee-svr-sgw-roles,cols="2,^1,^1,^1,^1",options="header"]
|===

1.1+|Couchbase Server
3+|{enterprise} Versions
|{community} Versions

h|Available Roles
h|6.1 - 7.0
h|5.5 - 6.0
h|5.1
h|All Versions

|sync-gateway role
|y
|-
|-
|-

|application-access
|y
|y
|-
|-

|bucket-full-access
|y
|y
|y
|-

|Full Admin
|y
|y
|y
|y

|===

For more on creating Couchbase Server users see the Couchbase Server content here {server-manage-security-users-and-roles--xref}.


[#lbl-optout]
== Secure Remote Authentication Opt-out
You can choose to disable secure remote authentication -- for development and testing purposes *only* -- by using these bootstrap configuration settings or CLI flags:

* Bootstrap file:
** `api.admin_interface_authentication`
** `api.metrics_interface_authentication`
* CLI flags
** `-admin_interface_authentication=false`.
** `-metrics_interface_authentication=false`.


== LDAP Authentication

Authentication against an external system such as LDAP is possible through Couchbase Server.

However, this can increase the risk of performance and or connection issues -- for more on this see the Couchbase Server documentation {server-security-auth-domains--xref-ldap}


[#lbl-port-cfg]
== Port Configuration

You can change the ports used for any of the interface types by editing the bootstrap configuration -- as shown in <<ex-port-cfg>> -- and restarting the {sgw} node.
The default ports are shown in <<network-ports>>.


[#ex-port-cfg]
.Configuring ports
====
[{tabs}]
=====
Admin::
+
--

[source, json]
----
  api: {
    "admin_interface": "http://localhost:4985", // <.>
    "admin_interface_authentication": true,

    // ... additional group properties

  },
----

--

Metrics::
+
--

[source, json]
----
  api: {
    "metrics_interface": "http://localhost:4986", // <.>
    "metrics_interface_authentication": true,

    // ... additional group properties

  },
----

--

Public::
+
--

[source, json]
----
  api: {
    "public_interface": "http://localhost:4984", // <.>

    // ... additional group properties

  },
----


--
=====

<.> The value of the _interface_ property is a string consisting of a colon followed by a port number (for example, `:4985`).
You can also include a host name or numeric IP address before the colon to bind only to that network interface, as shown here
====

As a useful special case, the IP address 127.0.0.1 binds to the loopback interface, making the port unreachable from any other host.
This is the default setting for the admin interface.


[#lbl-port-req]
.Network Port Requirements
include::partial$sgw-network-port-reqs.adoc[]

For more on configuration see {}

include::partial$block-related-content-api.adoc[]