
= Admin REST API
:page-aliases: admin-rest-api
:page-layout: article
:page-role: panes
:page-status: {releaseStatus} -- {releaseComments}
:page-content: conceptual
include::partial_attributesLocal.adoc[]

ifeval::["{releaseStatus}" == "beta"]
[.pane__frame--orange]
.Author's Notes
--
Document relevant aspects of _Replication's Admin REST API_.
NEEDS UPDATING TO REFLECT SG REPLICATE 2.0 CHANGES.

Amendments required to:

* sync-gateway-public.yml
* sync-gateway-admin.yml
* rest-api-public.adoc
* rest-api-admin.adoc{{}}

Information sources include:

* https://issues.couchbase.com/browse/DOC-6463
* https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e77c903#heading=h.i1nbf1ox8o1w

--
endif::[]

[abstract]
Use the API explorer to find out more about Sync Gateway's endpoints by functionality.

== API Explorer
The API explorer below groups all the endpoints by functionality.
You can click on a label to expand the list of endpoints and also generate a curl request for each endpoint.

swagger_ui::{attachmentsdir}/sync-gateway-admin.yaml[]


== Related Content

[.pane__frames]

* *How-to*
+
--
include how-to links as relevant,

include how-to links as relevant,
--

* *Learn more*
+
--
include any related concept links

include tutorial links as relevant

include blog links as relevant
--

* *Reference material*
+
--
include any reference docs

(eg config file or api)
--