= Admin REST API
:page-aliases: refer/rest-api-admin.adoc
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role: -toc
:page-content: Reference
:description: Description of the Sync Gateway Admin REST API

include::partial$_set_page_context.adoc[]

:param-abstract: Use the API explorer to find out more about Sync Gateway's endpoints by functionality.
:param-related: {rest-api--xref}  |  {rest-api-metrics--xref}  |  {rest-api-client-app--xref}
:topic-group: REST API
include::partial$_show_page_header_block.adoc[]

:param_type: admin
include::partial$block-caveats.adoc[tag='swaggerui']
:param_type!:


== Introduction

The Admin REST API is for administrator use only, and hence is *not* accessible from the clients directly.

To allow users to access the Admin API up you need to create a Couchbase Server-based RBAC-user for them -- see: {rest-api-access--xref}

NOTE: For document changes sent to Sync Gateway through the Admin REST API, the Sync Function executes with *admin* privileges. +
Calls to `requireUser`, `requireAccess` and `requireRole` will be no-ops, and will always appear successful.


== API Explorer


The API explorer below groups all the endpoints by functionality.
You can click on a label to expand the list of endpoints and also generate a curl request for each endpoint.

Each endpoint description specifies its RBAC role requirements, but see
xref:rest-api-access-rbac-roles.adoc[RBAC Roles]
and the Couchbase Server documentation here
{server-security-roles--xref}
if further information is required.


swagger_ui::{attachmentsdir}/rest-api-admin.yaml[]


include::partial$block-related-content-api.adoc[]
