= Metrics REST API
:page-aliases: refer/rest-api-metrics.adoc
:page-layout: article
:page-status:
:page-edition:
:page-role:
:page-content: conceptual
:description: Description of the Sync Gateway Metrics Rest API

include::partial$_std-hdr-sgw.adoc[]

:param-abstract: Use the API explorer to find out more about Sync Gateway's endpoints by functionality.
:param-related: {rest-api--xref}  |  {rest-api-admin--xref}  |  {rest-api-client-app--xref}  |  {xref-sgw-pg-stats-monitoring}  |  {xref-sgw-pg-stats-prometheus}
:topic-group: REST API
include::partial$block-abstract.adoc[]

== Introduction

Sync Gateway makes collecting performance data easy and secure by providing a Metrics REST API.
This API, separate from both the Public and Admin REST APIs, is available by default on port `4986` -- see <<lbl-act>> for how to change this, if needed.
It exposes Sync Gateway's stats on two endpoints, which deliver the same data in one of two formats:

* The `_metrics` endpoint returns Sync Gateway statistics in {glos-term-prometheus} format. +
For example: `GET host:4986/_metrics` +
+
For information on integration with Prometheus -- see {xref-sgw-pg-stats-prometheus} and our blog entry {url-blog-prometheus}.

* The `_expvars` endpoint returns Sync Gateway statistics in JSON format.

[#lbl-act]
== Configuration

include::partial$prometheus-activation.adoc[]

== API Explorer

You can browse the API using the explorer below.
The explorer groups all the endpoints by functionality.
Just click a label to expand the endpoints.
You can also generate curl requests if required, for each endpoint.

swagger_ui::{attachmentsdir}/rest-api-metrics.yaml[]

include::partial$block-related-content-api.adoc[]
