= Public REST API
:idprefix:
:idseparator: -

The API explorer below groups all the endpoints by functionality.
You can click on a label to expand the list of endpoints.

You can also send a request to each endpoint against an instance of Sync Gateway.
To do so, you must enable CORS with the following in the configuration file.
Refer to the Sync Gateway link:getting-started.html[installation guide] for more information on starting a new instance of Sync Gateway.

[source,javascript]
----

{
    ...
    "CORS": {
        "Origin":["*"],
        "LoginOrigin":["*"],
        "Headers":["Content-Type"],
        "MaxAge": 1728000
    },
    ...
}
----

== API Explorer

[subs="attributes+"]
++++
<link href="https://couchbase-docs.s3.amazonaws.com/assets/swagger-ui-3.7/swagger-ui.css" media="screen" rel="stylesheet" type="text/css"/>
<style>
  .article .body pre, #swagger-ui .article .body-param pre {
    text-shadow: none !important;
  }
  #swagger-ui a {
    color: #3b4151 !important;
  }
  #swagger-ui .swagger-ui .tab li {
    min-width: 100px;
  }
  #swagger-ui .information-container.wrapper {
    display: none;
  }
  #swagger-ui .topbar {
    display: none;
  }
</style>
<div id="swagger-ui"></div>
<script src="https://couchbase-docs.s3.amazonaws.com/assets/swagger-ui-3.7/swagger-ui-bundle.js"> </script>
<script src="https://couchbase-docs.s3.amazonaws.com/assets/swagger-ui-3.7/swagger-ui-standalone-preset.js"> </script>
<script>
const ui = SwaggerUIBundle({
	url: "https://couchbase-docs.s3.amazonaws.com/mobile/{version}/rest-apis/sync-gateway-public.json",
	dom_id: '#swagger-ui',
	deepLinking: true,
	presets: [
		SwaggerUIBundle.presets.apis,
		SwaggerUIStandalonePreset
	],
	tagsSorter: "alpha",
	operationsSorter: "alpha",
	docExpansion: "none",
	layout: "StandaloneLayout"
})
window.ui = ui
</script>
++++
