= Roles
:page-aliases: learn/roles.adoc
:page-layout: article
:page-role:
:page-status:
:page-content: conceptual

include::partial$_std-hdr-sgw.adoc[]

:topic-group: Concepts
include::partial$block-abstract.adoc[]


// For how to create a user -- see {xref-sgw-pg-users}.

Roles are named collections of channels -- see {xref-sgw-pg-channels}.
A user account can be assigned to zero or more roles.
A user inherits the channel access of all roles it belongs to.
This is very much like Unix groups, except that roles do not form a hierarchy.

You access roles through the Admin REST API much like users are accessed, through URLs of the form {rest-api-admin-pfx}#/role[/{tkn-db}/_role/{name}].
Role resources have a subset of the properties that users do: `name`, `admin_channels`, `all_channels`.

Roles have a separate namespace from users, so it's legal to have a user and a role with the same name.

Admin REST API::
You can assign a role to a user by sending a PUT request to {rest-api-admin-pfx}#/user/put\__db___user__name_[/{tkn-db}/_user/{name}] where `db` is the configured name of the database and `name` is the user name.
+
The roles to assign to the user are specified in the `admin_roles` array.
+
[source,bash]
----
$ curl -vX POST "http://localhost:4985/mydatabase/_user/" -H "accept: application/json" -H "Content-Type: application/json" -d '{"name": "john", "password": "pass", "admin_roles": ["foo"]}'
----

Configuration file::
A user can also be assigned to a role in the configuration file.
This method is convenient for testing and to get started, otherwise it is generally recommended to use the *Admin REST API* for a programmatic behavior.
+
[source,json]
----
{
  "databases": {
    "mydatabase": {
      "users": { // <1>
        "GUEST": {"disabled": true},
        "john": {"password": "pass", "admin_roles": ["foo"]}
      }
    }
  }
}
----
<1> {legacy-configuration-properties-pfx}#databases-this_db-users-this_user-admin_roles[databases.$db.users.$user.admin_roles]



include::partial$block-related-content-data.adoc[]