= Scopes and Collections Configuration for Sync Gateway
:page-aliases: learn/scopes-and-collections-config.adoc
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:page-content: conceptual
:description: pass:q[Configure Scopes and Collections for Sync Gateway - Examples with descriptions.]

This section explains how to configure Scopes and Collections for Sync Gateway. 
It describes configuration options and provides example configuration code.

== Understanding Buckets, Scopes, and Collections
Each database can contain multiple buckets. 
Each bucket can hold multiple scopes, and each scope can contain multiple collections.

When you create a bucket, a bucket._default._default element is inherently included (see the documentation on xref:server:learn:data/scopes-and-collections.adoc#default-scope-and-collection[Default Scopes and Collections] in Couchbase Server). 
Couchbase creates the default bucket to ensure backward compatibility.

Only Couchbase Server (CBS) allows using the word 'default' in naming conventions. 
As a result, you may see the term _default.default when creating a new bucket.

== Configuration Options

When upgrading to Sync Gateway 3.1, it's not necessary to include `scopes` and `collections` in the configuration. 
If you choose not to specify them, your previous data set will still be compatible. 
Keep in mind that the provided examples are optional.

You have these options to configure Scopes and Collections Sync for Gateway:

* *custom scope/custom collection (the option we cover here)* 
You can define 1 custom scope per database with up to 1000 custom collections.
+
If you don't specify a custom scope and collection, any documents you create will be saved in the default scope and collection.

* *default scope/custom collection* 
You can choose the default scope with up to 1000 custom collections.
+
If you don't specify a custom scope and collection, any documents you create will be saved in the default scope and collection.

* *default scope/default collection* 
You can choose the default scope with default collection in release 3.1.
+
If you don't specify a custom scope and collection, any documents you create will be saved in the default scope and collection.
+

When you import a dataset created in previous versions of Couchbase Server, the documents will automatically be saved in the `_default` scope and `_default` collection.

== Configuration Example: custom scope/custom collection

This example covers a configuration with 1 custom Scope and 2 custom Collections:

[source,javascript]
----
{
  "name": "db",
  "bucket": "bucket",
  "scopes" : {
    "scope1": {
      "collections": {
        "collection1" : {
            "sync": `
                function(doc, oldDoc, meta) {
                    if (doc.type != "default") {
                        throw({forbidden : "Rejected document"})
                    }
                    channel("legacy")
                }
            `,
            "import_filter": `
              function(doc) {
                return doc.type == "mobile"
              }
            `
        },
        "collection2" : {
          "sync": `
            function(doc, oldDoc, meta) {
              channel("collection1")
            }
          `,
          "import_filter": `
              function(doc) {
                return doc.type == "mobile"
              }
          `
        }
      }
    }
  },
  "num_index_replicas": 0
}
----

== Collections Configuration Description

Here is the description for the custom `Scope` with 2 custom `Collections` configuration. 
The database's structure, collections, sync functions, import filters, and index replicas are essential in accurately validating, filtering, and synchronizing documents within the database. 

== Database Information

=== db
This sets the name of the database to "db".

=== bucket
This indicates the bucket's name (where the data will be stored), in this case, "bucket".

== Scopes
A Scope can contain a set of Collections. 
You have the option to use the default provided by Couchbase or customize it to fit your specific needs.

=== scope1
You can define 1 custom scope per database with up to 1000 custom collections.

If you don't specify a custom scope and collection, any documents you create will be saved in the default scope and collection.

== Collections
A Collection can contain a set of documents. 
You have the option to use the default provided by Couchbase or customize it to fit your specific needs.

=== Collection1
Collection1 is storage for documents that are labelled as "default". 
Its sync function guarantees that any changes made to documents in Collection1 are also reflected in a legacy system. 
In addition, Collection1's import filter ensures that only documents labelled as "mobile" are imported.

=== Sync Function:
[source,javascript]
----
function(doc, oldDoc, meta) {
    if (doc.type != "default") {
        throw({forbidden : "Rejected document"});
    }
    channel("legacy");
}
----

Whenever a document is synced or updated in collection1, a function called `sync` is executed. 
This function has three parameters:

* New document (doc)
* Existing document (oldDoc)
* Document metadata (meta)

If the type field of the document is not `default`, the function will throw an error message saying "Rejected document" and call the `channel` function with the argument "legacy".

[NOTE]
====
This code example illustrates a specific use case for sync functions. 
For more information about others, see xref:sync-function.adoc[Sync Functions].
====

=== Import Filter:
[source,javascript]
----
function(doc) {
    return doc.type == "mobile";
}
----
When importing documents into collection1, there's an import filter that checks the `type` field value to determine if a document should be imported. 
If the `type` field equals `mobile`, the filter returns true, and the document is imported.

[NOTE]
====
This code example illustrates a specific use case for import filters. 
For more information about others, see xref:import-filter.adoc[Import Filters].
====

== Collections
A Collection can contain a set of documents. 
You have the option to use the default provided by Couchbase or customize it to fit your specific needs.

=== Collection2
Collection2 is a mirror of collection1, and is storage for documents that are labelled as "default". Collectio2's import filter ensures that only documents labelled as "mobile" are imported. Any changes made to documents in collection2 are also made to collection1, and vice versa.

=== Sync Function
[source,javascript]
----
function(doc, oldDoc, meta) {
    channel("collection1");
}
----

Whenever a document is synced or updated in `collection2`, its sync function is triggered. 
This function calls the `channel` function with `collection1` as an argument, which means it will communicate with the sync function of `collection1`. 

The sync function occurs every time a document is modified, regardless of whether or not it has any significance. 
Here are the examples when it happens:

* A document within a CBS bucket is updated by a process other than Sync Gateway. 
If the auto_import feature is on, the import_filter will decide if the document is eligible for import. 
If it passes, the sync function will activate.

* A document has been copied from a Couchbase Lite client.

* A document can be created or modified by using the Sync Gateway xref:rest-api-admin.adoc[REST API].

[NOTE]
====
This code example illustrates a specific use case for sync functions. 
For more information about others, see xref:sync-function.adoc[Sync Functions].
====

=== Import Filter
[source,javascript]
----
function(doc) {
    return doc.type == "mobile";
}
----

When importing documents for `collection2`, the import filter applies the same criteria as `collection1`. 
This filter is based on the value of the `type` field and is used to filter the documents.

[NOTE]
====
This code example illustrates a specific use case for import filters. 
For more information about others, see xref:import-filter.adoc[Import Filters].
====

=== Index Replicas
[source,javascript]
----
{
    "num_index_replicas": 0
}
----

The num_index_replicas property specifies the number of replicas that should be created for each index in the database. 
In this example, database will not have any index replicas created.
