= Scopes and Collections
// :page-aliases: scopes-and-collections.adoc
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:page-content: conceptual
:description: pass:q[Scopes and Collections in Couchbase Mobile 3.1 enable you to logically separate and organize data while managing app lifecycles independently across Mobile and Edge applications.]

== New Features

Sync Gateway is designed to provide a secure and efficient method for synchronizing and accessing data over the web. This document outlines the recent enhancements to Sync Gateway, specifically the addition of Scopes and Collections support.

1. Scopes and Collections Support: Adding Scopes and Collections support allows for an improved method of defining and enforcing data access control. This enhancement ensures that only authorized users can access the appropriate data.

2. Simplified Data Organization and Synchronization by streamlining the data organization and synchronization process, Sync Gateway enables users to build and scale applications more efficiently while maintaining a high level of security.

== Sync Gateway's support for Scopes and Collections

Sync Gateway's primary function in Scopes and Collections is facilitating data synchronization between Couchbase Lite clients and Couchbase Server. The Sync Gateway accomplishes this by managing and executing the following:

=== High Application Density at the Edge

* *Scopes and Collections at the Sync Gateway Level* +
Scopes and Collections at the Sync Gateway level can effectively manage extensive cloud-to-edge deployments, encompassing a wide range of edge applications employing a microservices-based architecture.

* *Autonomous Development, Deployment, and Scaling* +
This system facilitates the autonomous development, deployment, and scaling of loosely coupled microservices, each maintaining its dedicated and secure data repository.

* *The InterSync Gateway* +
The InterSync Gateway streamlines duplicating data between the local cluster and its cloud counterpart, maintaining uniformity.

* *Replication at the App Level* +
Instead of copying data for every microservice separately, replication can be configured at the app level.

=== Sync Gateway Metadata Isolation

* *Scopes and Collections for Isolation* +
Scopes and collections are used to isolate Sync Gateway metadata.

* *Default Scope/Collection for System Data* +
The `_default scope/collection` is used for system data maintained by Sync Gateway. In contrast, user-defined scopes/collections are used for application data.

* *Separating System Metadata and Application Data* +
Using separate Scopes and collections for system metadata and application data helps to logically isolate them and avoid accidental modification or deletion of system metadata by the application.

* *Implementing Role-Based Access Controls (RBAC)* +
To further safeguard against such risks, an SDK-based application implements role-based access controls (RBAC) to restrict access to the `_default scope/collection`, which typically contains critical sync metadata.

[Note]
====
Separating system metadata into its own Scope simplifies the implementation and management of the app data lifecycle.
====

=== Sync Gateway and Couchbase Lite Clients

* *Direct Syncing of Scopes* +
Sync Gateway enables Couchbase Lite clients to sync one or more Scopes directly to other Couchbase Lite clients over a local network via Couchbase Lite Peer-to-Peer protocol.

* *Bypassing Cloud-Based Control Points* +
This can be done without the need for a cloud-based control point.

* *Setting Up Replications* +
A Couchbase Lite client can set up one or more replications to one or more Sync Gateway database endpoints.

* *Syncing Collections* +
Each replication can sync one or all collections associated with that Scope.

* *Local Persistence of Data* +
The Couchbase Lite client can also locally persist data in a Scope not synced to remote Sync Gateway.