= Secure Sync Gateway Access
:page-role:
:page-edition: 3.0
:page-aliases: anchor-secure-sync-gateway-access.adoc
:description: Couchbase Sync Gateway TLS encryption and verification

include::partial$_std-hdr-sgw.adoc[]
:topic-group: Security
:param-related:  {authentication-users--xref}  |  {authentication-certs--xref}
:param-abstract!:
include::partial$block-abstract.adoc[]

:svc-config-json: https://github.com/couchbase/sync_gateway/blob/master/examples/serviceconfig.json[blob serviceconfig.json]


== Overview

From {sgw-te} 3.0, TLS is required by default for all communications with Couchbase Server.
TLS v1.3 is supported as the default protocol.

This approach means that that all endpoints communicating with {sgw} must also be encrypted, including:

* REST API endpoints
* Replication and client side network traffic, for example through Couchbase Lite replications

We strongly recommend always having TLS enabled, although this can be over-ridden for *development and testing only*.

Additionally, the _Admin_ and _Metrics REST API_ security is also enhanced by the use of _Couchbase Server RBAC user_ credentials to authenticate and authorize access -- see: {rest-api-access--xref}

// ===  Behavior

// .{sgw} <--> REST API
// [#tbl-restapi-behavior, cols="1a,1,1a, options="header"]
// |===

// .>h| Configuration Properties
// .>h| Default Behavior
// .>h| Opt-Out Trigger

// |{bootstrap-schema--xref--api-https-tls-cert-path} +
// {bootstrap-schema--xref--api-https-tls-key-path}
// |TLS encryption is enabled by default, unless the opt-out is triggered
// |Omit the key and certificate path properties from the configuration

// |===


== {sgw-t}-Couchbase Lite Sync

Couchbase Lite client applications must be updated to use TLS when connecting to {sgw} nodes running in default mode.

<<tbl-tls-config-options>> shows the TLS configuration options, whilst <<tbl-replication-behavior>> shows the default and opt-out behavior.


.TLS configuration options
[#tbl-tls-config-options,cols="4m,7m,^1a,10a", options="header"]
|===

|Bootstrap Configuration
|Command-line flag
|Default
|Purpose

|api.https.tls_key_path
|-api.https.tls_key_path
|nil
|Provide the path footnote:[pass:q,a[This can be absolute, or relative to the {sgw} executable's directory]] to the TLS private key file.

|api.https.tls_cert_path
|-api.https.tls_cert_path
|-
|Provide the path to the TLS certificate file.

|===

Omit both options to use _plaintext_ -- for development and-or testing *only* -- see the {configuration-schema-bootstrap--xref}.

.TLS behavior
[#tbl-replication-behavior, cols="1a,1,1a, options="header"]
|===

.>h| Configuration Properties
.>h| Default Behavior
.>h| Opt-Out Trigger

|{bootstrap-schema--xref--api-https-tls-cert-path} +
{bootstrap-schema--xref--api-https-tls-key-path}
|TLS verification and encryption is enabled by default, unless the opt-out is triggered
|Provide nil values for the key and certificate paths

|===


== Couchbase Server

By default {sgw-te} requires TLS encryption and the server scheme is specified as `couchbases://`.

You can set the {bootstrap-schema--xref--bootstrap-server-tls-skip-verify} flag `true` to connect to 'default CBS'.
But, this must only be done for testing or development purposes. 

// == Configuration
The content in <<tbl-tls-config-options>> shows the TLS configuration options for {sgw)-Couchbase Server communication.
The options include flags that will allow you to override the requirement to use TLS -- for use in testing and-or development environments *only*.

.Configuration options {sgw} <-->Couchbase Server
[#tbl-tls-config-options,cols="4a,3a,3a", options="header"]
|===

|Bootstrap Configuration / +
Command-line flag
|Default Behavior
|Opt-out

|`bootstrap.use_tls_server` +
CLI: `-bootstrap.use_tls_server`
|TLS enabled +
|Omit from bootstrap file or set this `false` in CLI to turn-off off TLS completely -- *development and testing only*

|`bootstrap.server_tls_skip_verify` +
CLI: `-bootstrap.server_tls_skip_verify`
|TLS enabled unless `use_tls_server` opt-out used
|* Omit from bootstrap file or set this `true` in CLI to skip server verification of certificates (self- or CA-signed) but leave encryption enabled. +
* Do not provide `ca_cert_path`, `x509_cert_path`, or `x509_cert_path`
* Use for *development and testing only*

| `bootstrap.ca_cert_path` +
CLI: `-bootstrap.ca_cert_path`
|Provides the path to the root CA certificate to verify the certificate chain and hostname of the Couchbase Server cluster
|Omit if not required

| `bootstrap.x509_cert_path` +
CLI: `-bootstrap.x509_cert_path`
|Provides the path to the client's certificate to authenticate against Couchbase Server footnote:[5.5 or above]
|Omit if not required

| `bootstrap.x509_key_path` +
CLI: `-bootstrap.x509_key_path`
|Provides the path to the the client's private key to authenticate against Couchbase Server footnote:[5.5 or above]
|Omit if not required

|===


=== Behavior


.Sync Gateway <--> Couchbase Server behavior
[#tbl-server-behavior, cols="3a,4a,2m", options="header"]
|===

.>h|Required Configuration
.>h| Default Behavior
.>h| Opt-Out Trigger

|Use `couchbases://` server scheme +
Set the certificate and key path:

* {bootstrap-schema--xref--bootstrap-ca-cert-path} +
* {bootstrap-schema--xref--bootstrap-x509-cert-path} +
* {bootstrap-schema--xref--bootstrap-x509-key-path}

|* Sync Gateway will error non-secure server schemes (`couchbase:` or `ws:`) unless the opt-out is triggered
* If a `ca_cert_path` is specified then only certificates from that CA will be accepted.
* If `ca_cert_path` is omitted
** If `server_skip_tls_verify=true` +
Then {sgw} will skip validation of any server cert, but still require encryption.
This includes skipping validation of certs that are from a trusted/well known CA
** If `server_skip_tls_verify=false` +
Then only certificates from a trusted/well known CA will be accepted

|use_tls_server=false (or omitted) +
server_skip_tls_verify=true (or included)

|===


== Launching Sync Gateway as Service
The `serviceconfig.json` file uses the `couchbases:` scheme, with `server_skip_tls_verify=true` by default, to facilitate testing and development; no TLS validation is done.

You can set TLS validation using the  following settings:

* {bootstrap-schema--xref--bootstrap-ca-cert-path}
* {bootstrap-schema--xref--bootstrap-x509-cert-path}
* {bootstrap-schema--xref--bootstrap-x509-key-path}
* {bootstrap-schema--xref--bootstrap-server-tls-skip-verify}


== Launching Sync Gateway at Command Line

You can set TLS validation using the  following command line flags:

* -bootstrap.ca_cert_path
* -bootstrap.x509_cert_path
* -bootstrap.x509_key_path
* -bootstrap.server_skip_tls_verify

Sync Gateway will error non-secure server schemes (`couchbase:` or `ws:`) unless the opt-out option is true.
 
You can no longer start {sgw} without providing at least one parameter; with no configuration file specified, you would need to provide a TLS Cert/Key, or set {bootstrap-schema--xref--bootstrap-server-tls-skip-verify}.


For information on creating and installing certificates, see {authentication-certs--xref}.

include::partial$block-related-content-api.adoc[]
