= Eventing -- Server Compatibility
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:page-partial:
:description: How Sync Gateway works with Couchbase Server's Eventing feature
:idprefix:
:idseparator: -


include::partial$_set_page_context.adoc[]


// BEGIN -- Page Attributes
// END -- Page Attributes


// BEGIN -- Page Header
:param-topic-group: compatibility
:param-related: {compatibility--xref}
include::partial$_show_page_header_block.adoc[]
// END -- Page Header


include::partial$block-caveats.adoc[tags=ee-only-feature]


== Introduction

Couchbase Server provides the backing data store for Sync Gateway.

TIP: See: {compatibility--xref} for version compatibility information.

Couchbase Server's {server-eventing--xref} feature provides a framework to operate on changes to data in real time.

Here we provide details on how {server-eventing--xref} relates to data changes in the Couchbase Mobile ecosystem.

== Using Eventing - Server 7.6.3+

include::partial$block-caveats.adoc[tags=eventing-mixed-mode]

Sync Gateway 3.2.0 and later supports interoperability with Eventing from Couchbase Server version 7.6.3+.
You can use Eventing to handle data changes that happen when applications interact and to integrate with other Couchbase services such as Data, Query and Full Text Search.

You can now create Eventing functions with read-write bindings with the source bucket associated with a Sync Gateway database.

You can also use Eventing to generate vector embeddings from document fields, see xref:couchbase-lite:ROOT/cbl-whatsnew.adoc#vector-search[Vector Search] for more details about Vector Search with Couchbase Lite.

Eventing now skips all documents with IDs prefixed with `_sync`.

For Sync Gateway versions that write import XATTRs:

* Eventing now prevents infinite recursion.

* Eventing now prevents duplicate mutations with the opt-in `import_mutation_aware` boolean flag.

NOTE: If the `import_mutation_aware` flag is set to `true`, the performance of the Eventing function will drop because every mutation processed by Eventing will require a subdocument operation to maintain a cursor or progress for any Function that is sharing a Sync Gateway endpoint.  

The procedure to enable Sync Gateway support for an Eventing function is as follows:

. On Couchbase Server, xref:server:eventing:eventing-api.adoc#basic_pause[pause the function].

. Using the Eventing REST API, set the `allow_sync_documents` setting for the function to false.
+
NOTE: You must also include the `deployment_status` and `processing_status` settings in the request body.
+
For example, for a global function with a scope of `*.*`:
+
[source, shell]
----
curl -XPOST -d '{
  "deployment_status": true,
  "processing_status": false,
  "allow_sync_documents": false
}' "http://$ADMIN:$PASSWORD@$HOST:8096/api/v1/functions/my_function/settings"
----
+
For a scoped function:
+
[source, shell]
----
curl -XPOST -d '{
  "deployment_status": true,
  "processing_status": false,
  "allow_sync_documents": false
}' "http://$USER:$PASSWORD@$HOST:8096/api/v1/functions/my_function/settings?bucket=bulk&scope=data"
----
+
Where:
+
* `$HOST` is the hostname or IP address of a node running the Eventing service.
+
* `$ADMIN` is the user name of an administrator.
+
* `$USER` is the user name of any authorized user .
+
* `$PASSWORD` is the password to connect to Couchbase Server.
+
. On Couchbase Server, xref:server:eventing:eventing-api.adoc#basic_resume[resume the function].

For more details, see xref:server:eventing:eventing-api.adoc[Eventing REST API].

== Using Eventing (Pre-Server 7.6.3)

You can use Eventing and Sync Gateway connected to the same bucket when Eventing operates on server buckets in *read only* mode -- see {server-eventing-terminologies--xref-bindings} for how to do this.

You should write your Eventing function to be *idempotent*; to behave correctly when the same mutation is seen more than once.
This is necessary because:

* When a single document update is made directly by Sync Gateway, such as those replicated from Couchbase Lite, it generates a single server mutation that writes both the document body and the metadata.
+
When an update originates outside of Couchbase mobile then multiple mutations are generated because Sync Gateway must update both the document's body and its _sync metadata (XATTRs).

* _Eventing_ detects these mutations and invokes its `OnUpdate` *for each*; whether it's for the modified body of the document, Sync Gateway metadata, or both.
It is here that you need to code the function to apply the same update once only.
One way to do this is to use the crc64 function call to identify when an update is to the Sync Gateway metadata only -- see: {server-eventing-constructs-crc64--xref} for more on how to do this.

_Eventing_ prevents inadvertent use of its functions on _Sync Gateway_ read-write buckets.
You will see the following  warning if you try to do this: +
`SyncGateway is enabled on: <bucket-name>, deployment of source bucket mutating handler will cause Intra Bucket Recursion`

// BEGIN -- Page Footer
include::partial$block-related-content-sync.adoc[]
// END -- Page Footer
