= Buckets -- Server Compatibility
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:description: pass:q[How _Sync Gateway_ works with _Couchbase Server's_ _Buckets_]
:idprefix:
:idseparator: -


include::partial$_set_page_context.adoc[]


// BEGIN -- Page Attributes
// END -- Page Attributes


// BEGIN -- Page Header
:param-topic-group: compatibility
:param-related: {compatibility--xref}
include::partial$_show_page_header_block.adoc[]
// END -- Page Header

== Introduction

A bucket in Couchbase Server is the fundamental space for storing data.
Each bucket contains a hierachy of Scopes and Collections to logically group keys and values.

For more information, see xref:server:learn:buckets-memory-and-storage/buckets.adoc[]

TIP: See: {compatibility--xref} for version compatibility information.

You can find details here about compatibility between Couchbase Server buckets and the Couchbase Mobile ecosystem.

== Durability

Sync Gateway does not support non-default durability settings and therefore xref:server:learn:data/durability.adoc[durable writes].
Make sure your buckets have their bucket durability setting set to `None`.
If this is not the case you'll get a xref:server:learn:data/durability.adoc#failure-scenarios[failure scenario], `Write while SyncWrite is pending`, and the attempt at a durable write fails.

// BEGIN -- Page Footer
include::partial$block-related-content-sync.adoc[]
// END -- Page Footer
