= Eventing -- Server Compatibility
:page-edition: enterprise
:description: pass:q[How _Sync Gateway_ works with _Couchbase Server's_ _Eventing_ feature]
:idprefix:
:idseparator: -


include::partial$_std-hdr-sgw.adoc[]


// BEGIN -- Page Attributes
// END -- Page Attributes


// BEGIN -- Page Header
:topic-group: compatibility
:param-related: {server-compatibility-xdcr--xref}  |  {server-compatibility-eventing--xref}  |   {server-compatibility-transactions--xref}  |   {server-compatibility-collections--xref}  | {compatibility--xref}
include::partial$block-abstract.adoc[]
// END -- Page Header


include::partial$block-caveats.adoc[tags=ee-only-feature]


== Introduction

Couchbase Server provides the backing data store for Sync Gateway and there are some considerations you needs to be aware of when using its features alongside Couchbase mobile.

For example, Couchbase Server's {server-eventing--xref} feature provides a framework to operate on changes to data in real time.
Here we provide details on how {server-eventing--xref} relates to data changes in the Couchbase Mobile ecosystem.


== Using Eventing

You can use Eventing and Sync Gateway connected to the same bucket, when Eventing operates in *read only* mode.

To do this, you must write your Eventing function to be *idempotent*; to behave correctly when the same mutation is seen more than once.
This is necessary because:

* When a single document update is made directly by Sync Gateway, such as those replicated from Couchbase Lite, it generates a single server mutation that writes both the document body and the metadata.
+
But when an update originates outside of Couchbase mobile then multiple mutations are generated.
That is because Sync Gateway must update both the document's body and its _sync metadata (XATTRs).

* _Eventing_ detects these mutations and invokes its `OnUpdate` *for each*; whether it is for the modified body of the document, XATTRs, or both.
It is here that you need to code the function to apply the same update once only.
One way to do this is to use the crc64 function call -- see: {server-eventing-constructs-crc64--xref} for more on how to do this.

_Eventing_ prevents inadvertent use of its functions on _Sync Gateway_ read-write buckets.
You will see the following  warning if you try to do this: +
`SyncGateway is enabled on: <bucket-name>, deployment of source bucket mutating handler will cause Intra Bucket Recursion`

// BEGIN -- Page Footer
include::partial$block-related-content-sync.adoc[]
// END -- Page Footer
