= Monitoring
:xref-cb-config: xref:sync-gateway:ROOT:stats-monitoring.adoc#

Sync Gateway 2.5 includes a number of new metrics available through the Admin REST API (`/_expvars`).
Those new metrics cover performance, resource utilization and health checks of the Sync Gateway nodes.

The following `curl` command requests the monitoring stats on the Admin REST API.

[source,java]
----
curl -X GET "http://localhost:4985/_expvar" -H "accept: application/json"
----

The response is a JSON object with the following schema.

[source,json,subs="normal"]
----
{
  "{xref-cb-config}sync-gateway[sync-gateway]": {
    "{xref-cb-config}global[global]": {
      "{xref-cb-config}resource_utilization[resource_utilization]": {
        "admin_net_bytes_recv": 0,
        "admin_net_bytes_sent": 0,
        "error_count": 0,
        "go_memstats_heapalloc": 0,
        "go_memstats_heapidle": 0,
        "go_memstats_heapinuse": 0,
        "go_memstats_heapreleased": 0,
        "go_memstats_pausetotalns": 0,
        "go_memstats_stackinuse": 0,
        "go_memstats_stacksys": 0,
        "go_memstats_sys": 0,
        "goroutines_high_watermark": 0,
        "num_goroutines": 0,
        "process_cpu_percent_utilization": 0,
        "process_memory_resident": 0,
        "pub_net_bytes_recv": 0,
        "pub_net_bytes_sent": 0,
        "system_memory_total": 0,
        "warn_count": 0
      }
    }
    "{xref-cb-config}per_db[per_db]": {
      "$dbname": {
        "{xref-cb-config}cache[cache]": {
          "{xref-cb-config}chan_cache_active_revs[chan_cache_active_revs]": 0,
          "{xref-cb-config}chan_cache_hits[chan_cache_hits]": 0,
          "{xref-cb-config}chan_cache_max_entries[chan_cache_max_entries]": 0,
          "{xref-cb-config}chan_cache_misses[chan_cache_misses]": 0,
          "{xref-cb-config}chan_cache_num_channels[chan_cache_num_channels]": 0,
          "{xref-cb-config}chan_cache_removal_revs[chan_cache_removal_revs]": 0,
          "{xref-cb-config}chan_cache_tombstone_revs[chan_cache_tombstone_revs]": 0,
          "{xref-cb-config}num_skipped_seqs[num_skipped_seqs]": 0,
          "{xref-cb-config}rev_cache_hits[rev_cache_hits]": 0,
          "{xref-cb-config}rev_cache_misses[rev_cache_misses]": 0
        },
        "{xref-cb-config}security[security]": {
          "{xref-cb-config}auth_failed_count[auth_failed_count]": 0,
          "{xref-cb-config}auth_success_count[auth_success_count]": 0,
          "{xref-cb-config}num_access_errors[num_access_errors]": 0,
          "{xref-cb-config}num_docs_rejected[num_docs_rejected]": 0,
          "{xref-cb-config}total_auth_time[total_auth_time]": 0
        }
      },
    }
  }
}
----

== sync-gateway

Monitoring stats

=== global

Global Sync Gateway stats

==== resource_utilization

Resource utilization stats

=== per_db

Stats for each database declared in the config file

==== cache

Stats relative to caching

===== abandoned_seqs

The number of skipped sequences that were not found after 60 minutes and were abandoned.

===== chan_cache_active_revs

The number of active revisions in the channel cache.

===== chan_cache_hits

Channel cache requests fully served by the cache.

===== chan_cache_max_entries

Size of the largest channel cache.

Helps with channel cache tuning, and as a hint on cache size variation (when compared to average cache size).

===== chan_cache_misses

Channel cache requests not fully served by the cache.

===== chan_cache_num_channels

Number of channels being cached.

Insight into total number of channels being cached - provides insight into potential max cache size (num channels * max_cache_size), as well as node usage.

===== chan_cache_removal_revs

The number of removal revisions in the channel cache.

Acts as a reminder that removals must be considered when tuning the channel cache size.
Also helps users understand whether they should be tuning tombstone retention policy (metadata purge interval), and running compact.

===== chan_cache_tombstone_revs

The number of tombstone revisions in the channel cache.

Acts as a reminder that tombstones and removals must be considered when tuning the channel cache size.
Also helps users understand whether they should be tuning tombstone retention policy (metadata purge interval), and running compact.

===== num_skipped_seqs

Number of skipped sequences.

Helps with channel cache tuning, and as a hint on cache size variation (when compared to average cache size).

===== rev_cache_hits

Revision cache hits.

===== rev_cache_misses

Revision cache misses.

==== database

Stats relative to the database

===== crc32c_match_count

Count of instances during import when the document cas had changed, but the document body was not changed.

===== dcp_caching_count

Count of DCP mutations added to Sync Gateway's channel cache.  Can be used with dcp_caching_time to monitor cache processing latency.

===== dcp_caching_time

Time between DCP mutation arriving at Sync Gateway and being added to channel cache (aggregate).

===== dcp_received_count

Number of document mutations received by Sync Gateway over DCP.

===== dcp_received_time

Time between document write and document being received by Sync Gateway over DCP.  If the document was written prior to Sync Gateway starting the feed, is measured as the time since the feed was started.  Can be used to monitor DCP feed processing latency.

===== doc_reads_bytes_blip

Total number of bytes read via Couchbase Lite 2.x replication since Sync Gateway startup.

===== doc_writes_bytes

Total number of bytes written as part of document writes since Sync Gateway startup.

===== doc_writes_bytes_blip

Total number of bytes written as part of Couchbase Lite 2.x document writes since Sync Gateway startup.

===== num_doc_reads_blip

Count of the number of documents read via Couchbase Lite 2.x replication since Sync Gateway startup.

===== num_doc_reads_rest

Count of the number of documents read via the REST API since Sync Gateway startup. Includes Couchbase Lite 1.x replication.

===== num_doc_writes

Count of the number of documents written via any means since Sync Gateway startup.

===== num_replications_active

Approximate number of active replications. Only counts continuous pull replications.

===== num_replications_total

Count of the number of replications created since Sync Gateway startup.

===== sequence_get_count

Number of high sequence lookups.

===== sequence_released_count

Number of unused, reserved sequences released by Sync Gateway.

===== sequence_reserved_count

Number of sequences reserved by Sync Gateway.

==== Security

Stats relative to security

===== auth_failed_count

Number of unsuccessful authentications. Useful to monitor the number of authentication errors.

===== auth_success_count

Number of successful authentications. Useful to monitor the number of authenticated requests.

===== num_access_errors

Count of documents rejected by write access functions (requireAccess/requireRole/requireUser).

===== num_docs_rejected

Count of documents rejected by the sync function. Useful to debug sync function issues and identify unexpected incoming documents.

===== total_auth_time

Total time it took to authenticate the last incoming request.