= Monitoring
include::partial$_attributesLocal.adoc[]

:xref-cb-config: xref:{version}@sync-gateway:ROOT:stats-monitoring.adoc#
:url-golang-memstats: https://golang.org/pkg/runtime/#MemStats
:goto-url-golang-memstats: {url-golang-memstats}[Go memstats]

== Introducing Sync Gateway Stats

As deployments scale to support a large number of connected Couchbase Lite clients, Sync Gateway nodes are becoming increasingly important. So, effectively monitoring their performance and health is essential.

Sync Gateway makes capturing that information easy, through its Admin REST API, which provides access to a number of useful metrics covering a node's:

* Performance
* Resource utilization and
* Health

You can request the monitoring stats, from the Admin REST API, using the `expvars` method, as shown in this `curl` command:

[source,java]
----
curl -X GET "http://localhost:4985/_expvar" -H "accept: application/json"
----

The response is a JSON object with the schema detailed in <<Sync Gateway Stats Schema>>, use the click-through links to find out more about each item.

== Sync Gateway Stats Schema

The statistics detailed in this schema are reset at each node restart; that is they are not persisted. So all totals, counts and averages are the values accrued since the last node restart unless otherwise specified.

[source,json,subs="normal"]
----
{
  "{xref-cb-config}syncgateway[syncgateway]": {
    "{xref-cb-config}global[global]": {
      "{xref-cb-config}resource_utilization[resource_utilization]": {
        "{xref-cb-config}admin_net_bytes_recv[admin_net_bytes_recv]": 0,
        "{xref-cb-config}admin_net_bytes_sent[admin_net_bytes_sent]": 0,
        "{xref-cb-config}error_count[error_count]": 0,
        "{xref-cb-config}go_memstats_heapalloc[go_memstats_heapalloc]": 0,
        "{xref-cb-config}go_memstats_heapidle[go_memstats_heapidle]": 0,
        "{xref-cb-config}go_memstats_heapinuse[go_memstats_heapinuse]": 0,
        "{xref-cb-config}go_memstats_heapreleased[go_memstats_heapreleased]": 0,
        "{xref-cb-config}go_memstats_pausetotalns[go_memstats_pausetotalns]": 0,
        "{xref-cb-config}go_memstats_stackinuse[go_memstats_stackinuse]": 0,
        "{xref-cb-config}go_memstats_stacksys[go_memstats_stacksys]": 0,
        "{xref-cb-config}go_memstats_sys[go_memstats_sys]": 0,
        "{xref-cb-config}goroutines_high_watermark[goroutines_high_watermark]": 0,
        "{xref-cb-config}num_goroutines[num_goroutines]": 0,
        "{xref-cb-config}process_cpu_percent_utilization[process_cpu_percent_utilization]": 0,
        "{xref-cb-config}process_memory_resident[process_memory_resident]": 0,
        "{xref-cb-config}pub_net_bytes_recv[pub_net_bytes_recv]": 0,
        "{xref-cb-config}pub_net_bytes_sent[pub_net_bytes_sent]": 0,
        "{xref-cb-config}system_memory_total[system_memory_total]": 0,
        "{xref-cb-config}warn_count[warn_count]": 0
      }
    },
    "{xref-cb-config}per_db[per_db]": {
      "{xref-cb-config}dbname[$dbname]": {
        "{xref-cb-config}cache[cache]": {
          "{xref-cb-config}abandoned_seqs[abandoned_seqs]":0,
          "{xref-cb-config}chan_cache_active_revs[chan_cache_active_revs]": 0,
          "{xref-cb-config}chan_cache_bypass_count[chan_cache_bypass_count]": 0,
          "{xref-cb-config}chan_cache_channels_added[chan_cache_channels_added]": 0,
          "{xref-cb-config}chan_cache_channels_evicted_inactive[chan_cache_channels_evicted_inactive]": 0,
          "{xref-cb-config}chan_cache_channels_evicted_nru[chan_cache_channels_evicted_nru]": 0,
          "{xref-cb-config}cache_compact_count[cache_compact_count]": 0,
          "{xref-cb-config}chan_cache_hits[chan_cache_hits]": 0,
          "{xref-cb-config}chan_cache_max_entries[chan_cache_max_entries]": 0,
          "{xref-cb-config}chan_cache_misses[chan_cache_misses]": 0,
          "{xref-cb-config}chan_cache_num_channels[chan_cache_num_channels]": 0,
          "{xref-cb-config}chan_cache_pending_queries[chan_cache_pending_queries]":0,
          "{xref-cb-config}chan_cache_removal_revs[chan_cache_removal_revs]": 0,
          "{xref-cb-config}chan_cache_tombstone_revs[chan_cache_tombstone_revs]": 0,
          "{xref-cb-config}high_seq_cached[high_seq_cached]": 0,
          "{xref-cb-config}high_seq_stable[high_seq_stable]": 0,
          "{xref-cb-config}num_active_channels[num_active_channels]": 0,
          "{xref-cb-config}pending_seq_len[pending_seq_len]": 0,
          "{xref-cb-config}num_skipped_seqs[num_skipped_seqs]": 0,
          "{xref-cb-config}rev_cache_bypass[rev_cache_bypass]": 0,
          "{xref-cb-config}rev_cache_hits[rev_cache_hits]": 0,
          "{xref-cb-config}rev_cache_misses[rev_cache_misses]": 0,
          "{xref-cb-config}skipped_seq_len[skipped_seq_len]": 0
        },
        "{xref-cb-config}cbl_replication_pull[cbl_replication_pull]": {
          "{xref-cb-config}attachment_pull_bytes[attachment_pull_bytes]": 0,
          "{xref-cb-config}attachment_pull_count[attachment_pull_count]": 0,
          "{xref-cb-config}max_pending[max_pending]": 0,
          "{xref-cb-config}num_pull_repl_active_continuous[num_pull_repl_active_continuous]": 0,
          "{xref-cb-config}num_pull_repl_active_one_shot[num_pull_repl_active_one_shot]": 0,
          "{xref-cb-config}num_pull_repl_caught_up[num_pull_repl_caught_up]": 0,
          "{xref-cb-config}num_pull_repl_since_zero[num_pull_repl_since_zero]": 0,
          "{xref-cb-config}num_pull_repl_total_continuous[num_pull_repl_total_continuous]": 0,
          "{xref-cb-config}num_pull_repl_total_one_shot[num_pull_repl_total_one_shot]": 0,
          "{xref-cb-config}request_changes_count[request_changes_count]": 0,
          "{xref-cb-config}request_changes_time[request_changes_time]": 0,
          "{xref-cb-config}rev_processing_time[rev_processing_time]": 0,
          "{xref-cb-config}rev_send_count[rev_send_count]": 0,
          "{xref-cb-config}rev_send_latency[rev_send_latency]": 0
        },
        "{xref-cb-config}cbl_replication_push[cbl_replication_push]": {
          "{xref-cb-config}attachment_push_bytes[attachment_push_bytes]": 0,
          "{xref-cb-config}attachment_push_count[attachment_push_count]": 0,
          "{xref-cb-config}conflict_write_count[conflict_write_count]": 0,
          "{xref-cb-config}doc_push_count[doc_push_count]": 0,
          "{xref-cb-config}propose_change_count[propose_change_count]": 0,
          "{xref-cb-config}propose_change_time[propose_change_time]": 0,
          "{xref-cb-config}sync_function_count[sync_function_count]": 0,
          "{xref-cb-config}sync_function_time[sync_function_time]": 0,
          "{xref-cb-config}write_processing_time[write_processing_time]": 0
        },
        "{xref-cb-config}database[database]": {
          "{xref-cb-config}abandoned_seqs[abandoned_seqs]": 0,
          "{xref-cb-config}cache_feed[cache_feed]": 0,
          "{xref-cb-config}crc32c_match_count[crc32c_match_count]": 0,
          "{xref-cb-config}dcp_caching_count[dcp_caching_count]": 0,
          "{xref-cb-config}dcp_caching_time[dcp_caching_time]": 0,
          "{xref-cb-config}dcp_received_count[dcp_received_count]": 0,
          "{xref-cb-config}dcp_received_time[dcp_received_time]": 0,
          "{xref-cb-config}doc_reads_bytes_blip[doc_reads_bytes_blip]": 0,
          "{xref-cb-config}doc_writes_bytes[doc_writes_bytes]": 0,
          "{xref-cb-config}doc_writes_bytes_blip[doc_writes_bytes_blip]": 0,
          "{xref-cb-config}doc_writes_xattr_bytes[doc_writes_xattr_bytes]":0,
          "{xref-cb-config}high_seq_feed[high_seq_feed]":0,
          "{xref-cb-config}import_feed[import_feed]":0,
          "{xref-cb-config}num_doc_reads_blip[num_doc_reads_blip]": 0,
          "{xref-cb-config}num_doc_reads_rest[num_doc_reads_rest]": 0,
          "{xref-cb-config}num_doc_writes[num_doc_writes]": 0,
          "{xref-cb-config}num_replications_active[num_replications_active]": 0,
          "{xref-cb-config}num_replications_total[num_replications_total]": 0,
          "{xref-cb-config}sequence_assigned_count[sequence_assigned_count]": 0,
          "{xref-cb-config}sequence_get_count[sequence_get_count]": 0,
          "{xref-cb-config}sequence_incr_count[sequence_incr_count]":0,
          "{xref-cb-config}sequence_released_count[sequence_released_count]": 0,
          "{xref-cb-config}sequence_reserved_count[sequence_reserved_count]": 0,
          "{xref-cb-config}warn_channels_per_doc_count[warn_channels_per_doc_count]": 0,
          "{xref-cb-config}warn_grants_per_doc_count[warn_grants_per_doc_count]": 0,
          "{xref-cb-config}warn_xattr_size_count[warn_xattr_size_count]": 0
        },
        "{xref-cb-config}delta_sync[delta_sync]": {
          "{xref-cb-config}delta_cache_hit[delta_cache_hit]": 0,
          "{xref-cb-config}delta_cache_miss[delta_cache_miss]": 0,
          "{xref-cb-config}delta_pull_replication_count[delta_pull_replication_count]": 0,
          "{xref-cb-config}delta_push_docs_count[delta_push_docs_count]": 0,
          "{xref-cb-config}deltas_requested[deltas_requested]": 0,
          "{xref-cb-config}deltas_sent[deltas_sent]": 0
        },
        "{xref-cb-config}gsi_views[gsi_views]": {
          "{xref-cb-config}gsi[GSIs]": 0,
          "{xref-cb-config}views[Views (Design doc or view)]": 0,
          "{xref-cb-config}num_access_errors[num_access_errors]": 0,
          "{xref-cb-config}num_docs_rejected[num_docs_rejected]": 0,
          "{xref-cb-config}total_auth_time[total_auth_time]": 0
        },
        "{xref-cb-config}security[security]": {
          "{xref-cb-config}auth_failed_count[auth_failed_count]": 0,
          "{xref-cb-config}auth_success_count[auth_success_count]": 0,
          "{xref-cb-config}num_access_errors[num_access_errors]": 0,
          "{xref-cb-config}num_docs_rejected[num_docs_rejected]": 0,
          "{xref-cb-config}total_auth_time[total_auth_time]": 0
        },
        "{xref-cb-config}shared_bucket_import[shared_bucket_import]": {
          "{xref-cb-config}import_cancel_cas[import_cancel_cas]": 0,
          "{xref-cb-config}import_count[import_count]": 0,
          "{xref-cb-config}import_error_count[import_error_count]": 0,
          "{xref-cb-config}import_high_seq[import_high_seq]": 0,
          "{xref-cb-config}import_partitions[import_partitions]": 0,
          "{xref-cb-config}import_processing_time[import_processing_time]": 0
          }
      }
    },
    "{xref-cb-config}per_replication[per_replication]": {
      "{xref-cb-config}replname[$replname]": {
        "{xref-cb-config}sgr_active[sgr_active]": true,
        "{xref-cb-config}sgr_docs_checked_sent[sgr_docs_checked_sent]": 0,
        "{xref-cb-config}sgr_num_attachment_bytes_transferred[sgr_num_attachment_bytes_transferred]": 0,
        "{xref-cb-config}sgr_num_attachments_transferred[sgr_num_attachments_transferred]": 0,
        "{xref-cb-config}sgr_num_docs_failed_to_push[sgr_num_docs_failed_to_push]": 0,
        "{xref-cb-config}sgr_num_docs_pushed[sgr_num_docs_pushed]": 0
      }
    }
  }
}
----

== Global stats

=== syncgateway

Monitoring stats

=== global

Global Sync Gateway stats

=== resource_utilization

Resource utilization stats

See: {url-golang-memstats} for more on memory allocator statistics

==== admin_net_bytes_recv
Description::
Total number of bytes received (since node start-up) on the network interface to which the Sync Gateway xref:config-properties.adoc#adminInterface[admin interface] is bound.
+
By default, that is the number of bytes received on `127.0.0.1:4985` since node start-up.
Use Case::
Throughput on admin interface = `admin_net_bytes_recv` / `admin_net_bytes_sent`

==== admin_net_bytes_sent
Description::
Total number of bytes sent (since node start-up) on the network interface to which the Sync Gateway xref:config-properties.adoc#adminInterface[admin interface] is bound.
+
By default, that is the number of bytes sent on `127.0.0.1:4985` since node start-up.

Use Case::
This metric can be useful in calculating the throughput on Sync Gateway's admin interface:

_Throughput on admin interface_ = `admin_net_bytes_recv` / `admin_net_bytes_sent`

==== error_count

Number of errors logged.

==== memory allocator statistics

See: {url-golang-memstats} for more on memory allocator statistics

===== go_memstats_heapalloc

Go memstats.HeapAlloc -- {goto-url-golang-memstats}

===== go_memstats_heapidle

Go memstats.HeapIdle -- {goto-url-golang-memstats}

===== go_memstats_heapinuse

Go memstats.HeapInuse -- {goto-url-golang-memstats}

===== go_memstats_heapreleased

Go memstats.HeapReleased -- {goto-url-golang-memstats}

===== go_memstats_pausetotalns

Go memstats.PauseTotalNs -- {goto-url-golang-memstats}

===== go_memstats_stackinuse

Go memstats.StackInuse -- {goto-url-golang-memstats}

===== go_memstats_stacksys

Go memstats.StackSys -- {goto-url-golang-memstats}

===== go_memstats_sys

Go memstats.Sys -- {goto-url-golang-memstats}

==== goroutines_high_watermark

Peak number of go routines since process start.

==== num_goroutines

Number of goroutines.

==== process_cpu_percent_utilization

Description::
The CPU's utilization as percentage value.
Derivation::
The CPU usage calculation is performed based on _user_ and _system_ CPU time, but it doesn't include components such as `iowait`.
This means that the values of `process_cpu_percent_utilization` and `%Cpu`, returned when running the `top` command, will *differ*  .

==== process_memory_resident

Memory utilization (_Resident Set Size_) for the process, in bytes.

==== pub_net_bytes_recv
Description::
Total number of bytes received (since node start-up) on the network interface to which the Sync Gateway xref:config-properties.adoc#interface[public interface] is bound.
+
By default, that is the number of bytes received on `127.0.0.1:4984` since node start-up.

Use case::
 To calculate throughput on the public interface --  `pub_net_bytes_recv` / `pub_net_bytes_sent`

==== pub_net_bytes_sent
Description::
Total number of bytes sent (since node start-up) on the network interface to which Sync Gateway xref:config-properties.adoc#interface[public interface] is bound.
+
By default, that is the number of bytes sent on `127.0.0.1:4984` since node start-up.
Use case::
To calculate throughput on the public interface --  `pub_net_bytes_recv` / `pub_net_bytes_sent`

==== system_memory_total
Description::
Total memory available on the system in bytes.

==== warn_count
Description::
Number of warnings logged.

== Metrics by Database

{xref-cb-config}cache[cache] | {xref-cb-config}cbl_replication_pull[cbl_replication_pull] | {xref-cb-config}cbl_replication_push[cbl_replication_push] | {xref-cb-config}database[database] | {xref-cb-config}delta_sync[delta_sync] | {xref-cb-config}gsi_views[gsi_views] | {xref-cb-config}security[security] | {xref-cb-config}shared_bucket_import[shared_bucket_import]

=== per_db

Stats for each database declared in the config file

=== $dbname

Stats relative to a database declared in the config file.

=== cache

Stats relative to caching

==== abandoned_seqs
Description::
The number of skipped sequences that were not found after 60 minutes and were abandoned.

==== chan_cache_active_revs
Description::
The number of active revisions in the channel cache.

==== chan_cache_bypass_count
Description::
Number of transient bypass channel caches created to serve requests when the channel cache was at capacity.

==== chan_cache_channels_added
Description::
Number of channel caches added.
Constraints::
Doesn't decrease when the channel is removed.
Similar to <<chan_cache_num_channels>> but doesn't track removals.

==== chan_cache_channels_evicted_inactive
Description::
Number of channel cache channels evicted due to inactivity.

==== chan_cache_channels_evicted_nru
Description::
Number of active channel cache channels evicted, based on ‘not recently used’ criteria.

==== chan_cache_compact_count
Description::
Number of channel cache compaction runs

==== chan_cache_compact_time
Description::
Amount of time channel cache compaction has taken in total, across all compaction runs.

==== chan_cache_hits
Description::
Channel cache requests fully served by the cache.
Use Case::
Calculating the Channel Cache Hit Ratio
+
`Channel Cache Hit Ratio`  = `chan_cache_hits` / (`chan_cache_hits` + `chan_cache_misses`)

==== chan_cache_max_entries
Description::
Size of the largest channel cache.
Use Case::
Helps with channel cache tuning, and as a hint on cache size variation (when compared to average cache size).

==== chan_cache_misses
Description::
Channel cache requests not fully served by the cache.
Use Case::
Calculating the Channel Cache Hit Ratio
+
`Channel Cache Hit Ratio`  = `chan_cache_hits` / (`chan_cache_hits` + `chan_cache_misses`)

anchor:chan_cache_num_channels[]

==== chan_cache_num_channels
Description::
Number of channels being cached.
Use Case::
The total number of channels being cached provides insight into potential max cache size (
`num channels` * `max_cache_size`), as well as node usage.

==== chan_cache_pending_queries
Description::
Number of channel cache pending queries.

==== chan_cache_removal_revs
Description::
The number of removal revisions in the channel cache.
Use Case::
Acts as a reminder that removals must be considered when tuning the channel cache size.
Also helps users understand whether they should be tuning tombstone retention policy (metadata purge interval), and running compact.

==== chan_cache_tombstone_revs
Description::
The number of tombstone revisions in the channel cache.
Use Case::
* Acts as a reminder that tombstones and removals must be considered when tuning the channel cache size.
* Also helps users understand whether they should be tuning tombstone retention policy (metadata purge interval), and running compact.

==== high_seq_cached
Description::
The highest sequence number cached.
Constraints::
There may be skipped sequences lower than high_seq_cached.

==== high_seq_stable
Description::
The highest contiguous sequence number that has been cached.

==== num_active_channels
Description::
Number of active channels.

==== num_skipped_seqs
Description::
Number of skipped sequences.
Use Case::
Helps with channel cache tuning, and as a hint on cache size variation (when compared to average cache size).

==== pending_seq_len
Description::
Number of pending sequences.
These are out-of-sequence entries waiting to be cached.

==== rev_cache_bypass
Description::
Number of revision cache bypass operations performed.

==== rev_cache_hits
Description::
Revision cache hits.
Use Case::
Can be used to calculatd the ratio of revision cache hits:
+
_Rev Cache Hit Ratio_ = `rev_cache_hits` / (`rev_cache_hits` + `rev_cache_misses`)

==== rev_cache_misses
Description::
Revision cache misses.
Use Case::
Can be used to calculate the ratio of revision cache misses:
+
_Rev Cache Miss Ratio_ = `rev_cache_misses` / (`rev_cache_hits` + `rev_cache_misses`)

==== skipped_seq_len
The current length of pending skipped sequence queue.

=== cbl_replication_pull

==== attachment_pull_bytes
Description::
Average size of attachments pulled.
This is the *pre-compressed* size.

==== attachment_pull_count
Description::
Number of attachments pulled.

==== max_pending
Description::
High watermark for number of documents buffered during feed processing, waiting on a missing earlier sequence.

==== num_pull_repl_active_continuous
Description::
Gauge representing the number of continuous pull replications in the active state.

==== num_pull_repl_active_one_shot
Description::
Gauge representing the number of one-shot pull replications in the active state.

==== num_pull_repl_caught_up
Description::
Gauge representing the number of replications which have caught up to the latest changes.

==== num_pull_repl_since_zero
Description::
Number of new replications starting per second. That is where `/_changes?since`=0).

==== num_pull_repl_total_continuous
Description::
Gauge representing the number of continuous pull replications.

==== num_pull_repl_total_one_shot
Description::
Gauge representing the number of one-shot pull replications.

==== request_changes_count
Description::
Number of `_changes` requested
Use Case::
This metric can be used to calculate the latency of `_changes` requests:
+
`_changes` request latency = `request_changes_time` / `request_changes_count`

==== request_changes_time
Description::

Use Case::
This metric can be used to calculate the latency of `_changes` requests:
+
`_changes` request latency = `request_changes_time` / `request_changes_count`

==== rev_processing_time
Description::
The total amount of time processing rev messages (revisions) during pull revision.
Use Case::
This metric can be used with `rev_send_count` to calculate the average processing time per revision.
+
_average processing time per revision_ = `rev_processing_time` / `rev_send_count`.

==== rev_send_count
Description::
The total number of rev messages processed during replication
Use Case::
This metric can be used with `rev_procesing_time` to calculate the average processing time per revision.
+
_average processing time per revision_ = `rev_processing_time` / `rev_send_count`.

==== rev_send_latency
Description::
The total amount of time between Sync Gateway receiving a request for a revision and that revision being sent.
+
In a pull replication, Sync Gateway sends a `/_changes` request to the client and the client responds with the list of revisions it wants to receive.
+
So, `rev_send_latency` measure the time between the client asking for those revisions and Sync Gateway sending them to the client.


Use Case::
This metric gives the time taken to respond to a `/ changes` request.

Constraints::
* The derived value includes latency associated with processing other revisions in the same batch.
* Measuring time from the `/_changes` response means that this stat will vary significantly depending on the changes batch size.
A larger batch size will result in a spike of this stat, even if the processing time per revision is unchanged.
+
A more useful stat might be the average processing time per revision:
+
_average processing time per revision_ = xref:#rev_processing_time[rev_processing_time] / xref:#rev_send_count[rev_send_count].

=== cbl_replication_push

==== attachment_push_bytes
Description::
Number of attachment bytes pushed
//Use case::

==== attachment_push_count
Description::
Number of attachments pushed.
// Use case(s)::

==== conflict_write_count
Description::
Number of writes that left the document in a conflicted state.
Includes new conflicts, and mutations that don’t resolve existing conflicts.
// Use case(s)::

==== doc_push_count
Description::
Number of documents pushed.
// Use case(s)::

==== propose_change_count
Description::
The total number of _changes_ and-or _proposeChanges_ messages processed since node start-up.

Use case::
The _propose_change_count_ stat can be useful when:

* Assessing the number of redundant change requests being pushed by the client.
+
Do this by comparing the _propose_change_count_ value with the number of actual writes (<<bmk_num_doc_writes,num_doc_writes>>), which could indicate that clients are pushing changes already known to Sync Gateway.
* Identifying situations where push replications are unexpectedly being restarted from zero.

NOTE: P2P synchronizations will typically show a higher incidences of rejected proposed changes.

==== propose_change_time
Description::
The total time spent processing _changes_ and/or _proposeChanges_ messages.

// Derivation:
// It is derived by dividing the total time spent handling changes divided by the number of documents included in each request.

Use case::
The _propose_change_time_ stat can be useful in diagnosing push replication issues arising from potential bottlenecks _changes_ and-or _proposeChanges_ processing.

Contraints::
The _propose_change_time_ is not included in the <<bmk_write_processing_time,write_processing_time>>.

==== sync_function_count
Description::
The total number of times that the _sync_function_ is evaluated.
Use case::
The _sync_function_count_ stat is useful in assessing the usage of the _sync_function_, when used in conjunction with the <<bmk_sync_function_time,sync_function_time>>.

anchor:bmk_sync_function_time[]

==== sync_function_time
Description::
The total time spent evaluating the _sync_function_.
Use case::
The _sync_function_time_ stat can be useful when:

* Troubleshooting excessively long push times, where it can help identify potential _sync_function_ bottlenecks (for example, those arising from complex, or inefficient, _sync_function_ design
* Assessing the overall contribution of the _sync_function_ processing to overall push replication write times.


anchor:bmk_write_processing_time[]

==== write_processing_time
Description::
Total time spent processing writes.
Measures complete request-to-response time for a write.
Use case::
The _write_processing_time_ stat can be useful when:

* Determining the _Average time per write_, which is _write_processing_time_ divided by the <<bmk_num_doc_writes,num_doc_writes>> stat value
* Assessing the benefit of adding additional Sync Gateway nodes, as it can point to SGW being a bottleneck
* Troubleshooting slow push replication, in which case it ought to be considered in conjunction with <<bmk_sync_function_time,sync_function_time>>.

=== database

Stats relative to the database

==== abandoned_seqs
Description::
Number of skipped sequences abandoned, based on `cache.channel_cache.max_wait_skipped`.

==== cache_feed
Description::
Contains low level dcp stats:
* dcp_backfill_expected - Expected number of sequences in backfill
* dcp_backfill_completed - Number of backfill items processed
* dcp_rollback_count - Number of DCP rollbacks

==== crc32c_match_count
Description::
Count of instances during import when the document cas had changed, but the document was not imported because the document body had not changed.

anchor:bmk_dcp_caching_count[]

==== dcp_caching_count
Description::
Count of DCP mutations added to Sync Gateway's channel cache.
Use Case::
Can be used with `<<bmk_dcp_caching_time,dcp_caching_time>>` to monitor cache processing latency.
That is, the time between seeing a change on the DCP feed and when it's available in the channel cache.
+
_DCP cache latency_ = `dcp_caching_time` / `dcp_caching_count`

anchor:bmk_dcp_caching_time[]

==== dcp_caching_time
Description::
Time between DCP mutation arriving at Sync Gateway and being added to channel cache (total).

Use Case::
Can be used with `<<x,dcp_caching_count>>` to monitor cache processing latency.
That is, the time between seeing a change on the DCP feed and when it's available in the channel cache.
+
_DCP cache latency_ = `dcp_caching_time` / `dcp_caching_count`

==== dcp_received_count
Description::
Number of document mutations received by Sync Gateway over DCP.

==== dcp_received_time
Description::
Time between document write and document being received by Sync Gateway over DCP.
If the document was written prior to Sync Gateway starting the feed, is measured as the time since the feed was started.
Use Case::
Can be used to monitor DCP feed processing latency.

==== doc_reads_bytes_blip
Description::
Total number of bytes read via Couchbase Lite 2.x replication since Sync Gateway node startup.

==== doc_writes_bytes
Description::
Total number of bytes written as part of document writes since Sync Gateway node startup.

==== doc_writes_bytes_blip
Description::
Total number of bytes written as part of Couchbase Lite 2.x document writes since Sync Gateway node startup.

==== doc_writes_xattr_bytes
Description::
Total size of xattrs written (in bytes).

==== high_seq_feed
Description::
Highest sequence number seen on the caching DCP feed.

==== import_feed
Description::
Contains low level dcp stats:
* dcp_backfill_expected - Expected number of sequences in backfill
* dcp_backfill_completed - Number of backfill items processed
* dcp_rollback_count - Number of rollbacks that occur

==== num_doc_reads_blip
Description::
Count of the number of documents read via Couchbase Lite 2.x replication since Sync Gateway node startup.

==== num_doc_reads_rest
Description::
Count of the number of documents read via the REST API since Sync Gateway node startup.
Includes Couchbase Lite 1.x replication.

anchor:bmk_num_doc_writes[]

==== num_doc_writes
Description::
Count of the number of documents written by any means (replication, rest API interaction or imports) since Sync Gateway node startup.

==== num_replications_active
Description::
Number of active replications.
Constraints::
Only counts continuous pull replications.

==== num_replications_total
Description::
The total number of replications created since Sync Gateway node startup.

==== sequence_assigned_count
Description::
Number of sequence numbers assigned.

==== sequence_get_count
Description::
Number of high sequence lookups.

==== sequence_incr_count
Description::
Number of times the sequence counter document has been incremented.

==== sequence_released_count
Description::
Number of unused, reserved sequences released by Sync Gateway.

==== sequence_reserved_count
Description::
Number of sequences reserved by Sync Gateway.

==== warn_channels_per_doc_count
Description::
Number of warnings relating to the channel count exceeding the channel count threshold.
Corresponding warning message::
Doc id: {document id} channel count: {channel count} exceeds {channel count} for channels per doc warning threshold

==== warn_grants_per_doc_count
Description::
Number of warnings relating to the grant count exceeding the grant count threshold.

Corresponding warning message::
Doc id: {document id} access and role grants count: {grant count} exceeds {grant count} for grants per doc warning threshold

==== warn_xattr_size_count
Description::
Number of warnings relating to the xattr sync data being larger than a configured threshold.

Corresponding warning message::
Doc id: {document id} sync metadata size: {xattr bytes} bytes exceeds {xattr bytes} bytes for sync metadata warning threshold

=== delta_sync

==== delta_cache_hit
Description::
Count of requested deltas that were available in the revision cache.

==== delta_cache_miss
Description::
Count of requested deltas that were not available in the revision cache.

==== delta_pull_replication_count
Description::
The number of delta replications that have been run.

==== delta_push_doc_count
Description::
Number of documents pushed as a delta from a previous revision.

==== deltas_requested
Description::
Times a revision is sent as delta from a previous revision.

==== deltas_sent
Description::
Number of revisions sent to clients as deltas.

=== gsi_views

==== GSIs

{query name}_count::
Number of queries performed

{query name}_error_count::
Number of errors occurred performing query

{query name}_time::
Total time taken to perform queries

Where {query name} is a placeholder representing a _Valid Query Name_, as defined below:

.Valid Query Names
* access
* roleAccess
* channels
* channelsStar
* sequences
* principals
* sessions
* tombstones
* resync
* allDocs

==== Views

{design doc name}.{view  name}_count::
Number of view queries performed
{design doc name}.{view  name}_error_count::
Number of errors occurred performing query
{design doc name}.{view  name}_time::
Time taken to perform view query

Where {design doc name} and {view name} are placeholders representing a _Valid Design Doc Name_ and a _Valid View Name_, as defined below:

.Valid Design Doc Names
* sync_gateway
* sync_housekeeping

.Valid View Names
* principals
* channels
* access
* access_vbseq
* role_access
* role_access_vbseq
* all_docs
* import
* sessions
* tombstones



=== Security

Stats relative to security

anchor::bmk_auth_failed[]

==== auth_failed_count
Description::
Number of unsuccessful authentications.
Use Case::
Useful to monitor the number of authentication errors.

anchor::bmk_auth_success[]

==== auth_success_count
Description::
Number of successful authentications.
Use Case::
Useful to monitor the number of authenticated requests.

==== num_access_errors
Description::
Count of documents rejected by write access functions (requireAccess, requireRole, requireUser).

==== num_docs_rejected
Description::
Count of documents rejected by the sync function.
Use Case::
Useful to debug sync function issues and identify unexpected incoming documents.

==== total_auth_time
Description::
Total time spent to authenticate all requests.
Use Cases::
Can be compared with `<<bmk_auth_success,auth_success>>` and `<<bmk_auth_failed,auth_failed>>` to compute the average.

=== shared_bucket_import

==== import_cancel_cas
Description::
Number of imports cancelled due to cas failure.

==== import_count
Description::
Number of docs imported.

==== import_error_count
Description::
Number of errors as a result of a document import.
Corresponding Error Message::
Error importing doc {document id}: {error}

==== import_high_seq
Description::
Highest sequence number imported.

==== import_partitions
Description::
Number of import partitions.

==== import_processing_time
Description::
Time taken to process a document import.

== Metrics by replication

=== Per_replication

This _per_replication_ group header encompases all the  stats for each replication between Sync Gateway instances declared in the config file.
It comprises one or more  <<replname,$replname>> groups, replications, as introduced by the <<replname,$replname>> group header.

NOTE: These metrics refer to Sync Gateway replications only; Couchbase Lite replications are not included.

anchor:replname[]

=== $replname

This is the group header for the stats for each replication between two Sync Gateway instances declared in the config file.

=== sgr_active
Description::
Whether the replication is active at this time.

=== sgr_docs_checked_sent
Description::
Number of documents checked for changes since replication started.
This represents the number of potential _change notifications_ pushed by Sync Gateway.

Constraints::
This is not necessarily the number of _documents_ pushed, as a given target might already have the change.

Values::
* Continuous replication:
+
The value is `true` for the duration of the replication, and also once it has caught up (i.e is in the idle state).
  The value is `false` if the replication is explicitly cancelled.

* One-shot replication
+
The value is `true` for the duration of the replication, and then `false` when it has completed or if it is cancelled.
Use Case::
This can be useful when analyzing replication history, and to filter by active replications.

=== sgr_num_attachments_transferred
Description::
Number of attachments transferred since replication started.

=== sgr_num_attachment_bytes_transferred
Description::
Number of attachment bytes transferred since replication started.

=== sgr_num_docs_failed_to_push
Description::
Number of documents that failed to be pushed since replication started.

=== sgr_num_docs_pushed
Description::
Number of documents that were pushed since replication started.
