= New in {release}
:page-aliases: sgw-whatsnew.adoc, whats-new.adoc, what-is-new.adoc
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:description: Couchbase Sync Gateway -- What's new in the latest release
:keywords: edge nosql api synchronization replication

include::ROOT:partial$_set_page_context.adoc[]

:xref-sgw-bmk-cfg-dbsvr: xref:{configuration-properties-legacy--page}#databases-this_db-server[Couchbase Server Connection String]
:xref-sgw-bmk-cfg-hideprodvn: xref:{configuration-properties-legacy--page}#hide_product_version[Hide Product Version in Headers]


:param-abstract: This content covers the new features introduced in Sync Gateway {release}

:param-related: {xref-sgw-pg-release-notes}
include::partial$_show_page_header_block.adoc[]

CAUTION: {sgw-t} 3.0.x introduces some breaking changes.
If you are upgrading from 2.x, please refer to the {upgrading--xref} page.
Users should be able to upgrade to 3.1.x from 3.0.x without manual intervention.


== Overview of {sgw-t} 3.1.0

Couchbase Mobile's cloud-to-edge support for scopes and collections allows application developers to organize and logically isolate data.  

Independent lifecycle management and fine-grained security control simplifies the deployment of multi-tenant and high-application density cloud-to-edge applications at scale.

Scopes and collections are a first class concept, synced between Couchbase Lite and Sync Gateway, between Sync Gateways (Inter Sync Gateway Replication), between Couchbase Lite peers, as well as available offline-first on Couchbase Lite devices.




See more details of xref:3.0@whatsnew.adoc[what's new in the previous 3.0 release.]

include::partial$block-related-content-data.adoc[]
