= New In {release}
:page-aliases: sgw-whatsnew.adoc, whats-new.adoc, what-is-new.adoc
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:description: Couchbase Sync Gateway -- What's new in the latest release
:keywords: edge nosql api synchronization replication

include::ROOT:partial$_set_page_context.adoc[]

:xref-sgw-bmk-cfg-dbsvr: xref:{configuration-properties-legacy--page}#databases-this_db-server[Couchbase Server Connection String]
:xref-sgw-bmk-cfg-hideprodvn: xref:{configuration-properties-legacy--page}#hide_product_version[Hide Product Version in Headers]


:param-abstract: This content covers the new features introduced in Sync Gateway {release}

:param-related: {xref-sgw-pg-release-notes}
include::partial$_show_page_header_block.adoc[]

include::partial$block-caveats.adoc[tags=eventing-mixed-mode]

== Release 3.3.0 (July 2025)

=== New Features

==== Partitioned Indexes

Sync Gateway 3.3 introduces support for partitioned indexes.
Partitioned indexes offer horizontal scalability for large deployments by sharding indexes across multiple nodes.
Only `allDocs` and `channels` indexes can be partitioned.

Partitioned indexes are not intended for general use in Sync Gateway.
They may decrease performance, as each partition is queried separately and results are aggregated.

You should only migrate to partitioned indexes in cases where you are using memory-optimized indexes which exceed the memory capacity of a single index node, and you cannot reduce the index size using collections or database sharding.

For more information, see xref:deploy:index-partitions.adoc[].

==== Disable the Public All Docs Endpoint

Sync Gateway 3.3 introduces an option to disable the xref:rest-api:rest_api_public.adoc#tag/Document/operation/get_keyspace-_all_docs[`GET /{keyspace}/_all_docs`] operation in the Public REST API.
That operation is intended mainly for debugging in a small setup.
With a large number of documents, it may lead to timeouts and out-of-memory conditions on the Query nodes.

In any sizeable setup, it is recommended that you should instead use the xref:rest-api:rest_api_public.adoc#tag/Database-Management/operation/get_keyspace-_changes[`GET /{keyspace}/_changes`] operation to get all documents for a user, or the xref:rest-api:rest_api_public.adoc#tag/Document/operation/post_keyspace-_bulk_docs[`POST /{keyspace}/_bulk_docs`] operation to return a specific subset of documents.

To disable the xref:rest-api:rest_api_public.adoc#tag/Document/operation/get_keyspace-_all_docs[`GET /{keyspace}/_all_docs`] operation in the Public REST API, set xref:configuration:configuration-schema-database.adoc#disable_public_all_docs[`disable_public_all_docs`] to `true` in the database configuration.
This option is set to `false` by default; it will be set to `true` by default in a future release.

==== Interactive Admin Credentials for SG Collect Info

In Sync Gateway 3.3 and later, the `--sync-gateway-password` command line argument has been removed from `sgcollect_info` for security reasons.
When you specify the `--sync-gateway-username` option, `sgcollect_info` prompts you to enter the password interactively.
Attempting to use the `--sync-gateway-password` option causes an error, with instructions for next steps.

Alternatively, you can set credentials using the `SG_USERNAME` and `SG_PASSWORD` environment variables to avoid the prompt.

For more information, see xref:manage:sgcollect-info.adoc[].

==== Performance Improvements for Larger Deployments

Sync Gateway 3.3 includes several performance enhancements for larger deployments.
Change notification processing has been optimized to better support high volumes of connected clients per Sync Gateway node.
Channel cache memory and CPU utilization has been optimized, particularly under high write load.
Finally, memory and CPU usage associated with skipped sequence processing, which commonly occurs under high write load, has been reduced.

== See Also

xref:3.2@sync-gateway:ROOT:whatsnew.adoc[What's new in previous version 3.2].

=== Sync Gateway Release Notes

xref:product-notes:release-notes.adoc[Read the full 3.3 release notes here].


== Upgrading

xref:ROOT:upgrading.adoc[].

include::partial$block-related-content-data.adoc[]
