= New In {release}
:page-aliases: sgw-whatsnew.adoc, whats-new.adoc, what-is-new.adoc
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:description: Couchbase Sync Gateway -- What's new in the latest release
:keywords: edge nosql api synchronization replication

include::ROOT:partial$_set_page_context.adoc[]

:xref-sgw-bmk-cfg-dbsvr: xref:{configuration-properties-legacy--page}#databases-this_db-server[Couchbase Server Connection String]
:xref-sgw-bmk-cfg-hideprodvn: xref:{configuration-properties-legacy--page}#hide_product_version[Hide Product Version in Headers]


:param-abstract: This content covers the new features introduced in Sync Gateway {release}

:param-related: {xref-sgw-pg-release-notes}
include::partial$_show_page_header_block.adoc[]

[WARNING]
--

Do not deploy Eventing/Sync Gateway until all SGW nodes are at version 3.2.
For earlier Sync Gateway versions that do not write import XATTRs, Eventing functions may encounter infinite recursions and duplicate mutations if deployed in a mixed mode SGW environment.
This occurs if you have a mixed installation consisting of Sync Gateway 3.2 and an earlier version, and you deploy a new Eventing or Sync Gateway function during an upgrade.

--
== Release 3.2.1 (October 2024)

=== Additional Rev Cache Configuration Option

You can now specify a memory limit on your rev cache with the `rev_cache.max_memory_count_mb` configuration option.
You can use this option alongside existing configurable limits to the number of documents in the rev cache to reduce the risk of Out of Memory (OOM) issues.

For more information, see xref:configuration-schema-database.adoc#cache-rev_cache-max_memory_count_mb[Rev Cache Max Memory Count Config Option].

== Release 3.2.0 (September 2024)

=== Eventing Support with Sync Gateway 3.2.0+ and Couchbase Server 7.6.3+

Sync Gateway 3.2.0 now supports improved interoperability with Eventing from Couchbase Server version 7.6.3+.

You can now create Eventing functions with read-write bindings with the source bucket associated with a Sync Gateway database.
You can use Eventing to handle data changes that happen when applications interact and to integrate with other Couchbase services such as Data, Query and Full Text Search.

For more information, see xref:server-compatibility-eventing.adoc[]

=== Audit Logging Support

Couchbase now provides Audit Logging support for Sync Gateway. Audit Logging provides tools for administrators to track operational irregularities and to support regulatory and security compliance standards, such as link:https://www.hhs.gov/hipaa/index.html[HIPAA] and link:https://soc2.co.uk/soc2[SOC-2].
For more information, see xref:audit-logging.adoc[].

== See Also

xref:3.1@sync-gateway:ROOT:whatsnew.adoc[What's new in previous version 3.1].

=== Sync Gateway Release Notes

xref:3.2@release-notes.adoc[Read the full 3.2 release notes here].

== Upgrading

xref:upgrading.adoc[].

include::partial$block-related-content-data.adoc[]
