= New in {release}
:page-aliases: sgw-whatsnew.adoc, whats-new.adoc, what-is-new.adoc
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:description: Couchbase Sync Gateway -- What's new in the latest release
:keywords: edge nosql api synchronization replication

include::ROOT:partial$_set_page_context.adoc[]

:xref-sgw-bmk-cfg-dbsvr: xref:{configuration-properties-legacy--page}#databases-this_db-server[Couchbase Server Connection String]
:xref-sgw-bmk-cfg-hideprodvn: xref:{configuration-properties-legacy--page}#hide_product_version[Hide Product Version in Headers]


:param-abstract: This content covers the new features introduced in Sync Gateway {release}

:param-related: {xref-sgw-pg-release-notes}
include::partial$_show_page_header_block.adoc[]

CAUTION: {sgw-t} 3.0.x introduces some breaking changes.
If you are upgrading from 2.x, please refer to the {upgrading--xref} page.
Users should be able to upgrade to 3.1.x from 3.0.x without manual intervention.


== Overview of {sgw-t} 3.1.0

// tag::scopes-and-collections[]
Couchbase Sync Gateway now provides advanced cloud-to-edge support for xref:data-modeling.adoc#Scopes-and-Collections[Scopes and Collections]. This will provide seamless synchronization and efficient data management across distributed environments, from cloud infrastructure to edge devices.

Scopes and Collections enable mobile and edge devices to benefit from:

* *Logical grouping:* Organizing related documents and simplifying your querying, boosting indexing efficiency, and streamlining data retrieval.

* *Independent lifecycle management:* Allowing you to manage each Scope and Collection individually without affecting other Scopes or Collections within the same bucket, providing greater data management flexibility.

* *Access Control:* Scopes and Collections are safeguarded by Role-Based Access Control (RBAC), ensuring secure access management. RBAC allows you to control access to specific scopes or collections, enabling granular security control and protecting data from unauthorized access.
// end::scopes-and-collections[]


Read the full xref:3.1@release-notes.adoc[3.1 release notes].

See more details of xref:3.0@whatsnew.adoc[what's new in the previous 3.0 release.]

include::partial$block-related-content-data.adoc[]
