= New in {release}
:page-aliases: sgw-whatsnew.adoc, whats-new.adoc, what-is-new.adoc
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:description: Couchbase Sync Gateway -- What's new in the latest release
:keywords: edge nosql api synchronization replication

include::ROOT:partial$_set_page_context.adoc[]

:xref-sgw-bmk-cfg-dbsvr: xref:{configuration-properties-legacy--page}#databases-this_db-server[Couchbase Server Connection String]
:xref-sgw-bmk-cfg-hideprodvn: xref:{configuration-properties-legacy--page}#hide_product_version[Hide Product Version in Headers]


:param-abstract: This content covers the new features introduced in Sync Gateway {release}

:param-related: {xref-sgw-pg-release-notes}
include::partial$_show_page_header_block.adoc[]

CAUTION: {sgw-t} 3.0.x introduces some breaking changes.
If you are upgrading from 2.x, please refer to the {upgrading--xref} page.
Users should be able to upgrade to 3.1.x from 3.0.x without manual intervention.

* *New support for Scopes and Collections* +
Couchbase has introduced support for Scopes and Collections for self-managed cloud-to-edge deployments only in xref:couchbase-lite:ROOT:index.adoc[Couchbase Lite 3.1.0] and xref:introduction.adoc[Sync Gateway 3.1.0]. 
This release won't cause any issues with existing apps, as it's compatible with older versions. 
If you have an app that uses bucket-based APIs, you can still upgrade to 3.1, but please note that this API is now deprecated.

* *Improved Data Organization and Access Control for Scopes and Collections* +
Couchbase Mobile now offers Scopes and Collections, allowing more efficient and scalable data organisation within a bucket. 
This also introduces an improved method of defining and enforcing data xref:access-control-concepts.adoc[Access Control] more granularly. 
Multi-tenant apps will also experience better scalability and independent data lifecycle management.

* *Improved metadata isolation for Scopes and Collections* +
Sync Gateway 3.1.0 has improved metadata isolation. 
The system data maintained by Sync Gateway is now stored in the `_default` Scope/Collection, while both the `_default` and user-defined Scope/Collection can be used for application data. 
For more information, examples and use cases, see https://www.couchbase.com/blog/scopes-collections-couchbase-mobile/[Scopes and Collections Support in Couchbase Mobile for Edge Applications].

* *Collection-Level Sync Functions and Scoped User Associations* +
The xref:sync-function.adoc[Sync Functions] now work on a Collection level, and additional optional fields have been added to the database configurations to support this update. 
Each database is designed to support only one Scope. Users can be associated with that Scope and shared across multiple Collections.

* *Enhanced Collection Synchronization and Local Data Storage with Couchbase Lite Client* +
With Couchbase Lite client replications, you can synchronize one or multiple Collections within a specific scope. 
The Couchbase Lite client also will store data locally in a scope not synchronized with the remote Sync Gateway.


Read the full xref:3.1@release-notes.adoc[3.1 release notes].

See more details of xref:3.0@whatsnew.adoc[what's new in the previous 3.0 release.]

include::partial$block-related-content-data.adoc[]
