// BEGIN -- PAGE -- write-access.adoc
// BEGIN PAGE DEFINITION
//  LOCATION modules/ROOT/pages/
//  PURPOSE:
//    This is a standard content presentations page.
//    Its name/title identify the content/topic
//  PARAMETERS:
//    None
//  INCLUSION USAGE --
//    This module uses attributes from:
//    - /modules/ROOT/pages/_partials/_page-index.adoc -- xref page links
//
//    This module uses these inclusions:
//    - /modules/ROOT/pages/_partials/_std-hdr-sgw.adoc -- std attribute environment
//    - /modules/ROOT/pages/_partials/block-abstract.adoc --  std text block for page header content
//    - /modules/ROOT/pages/_partials/block-related-content-deploy.adoc --  std text block for page footer content
//    - modules/ROOT/assets/images -- .png/.jpeg images
//  INCLUSION USAGE
// END PAGE DEFINITION
= Write Security
:page-aliases: learn/write-access.adoc
:description: pass:q[How to manage write-access in Sync Gateway to ensure secure cloud-to-edge synchronization of enterprize data.]

include::partial$_std-hdr-sgw.adoc[]


// BEGIN -- Page Heading
:param-topic-group: access-control
:param-abstract: pass:q[The Sync Function API provides several methods that you can use to validate document creation, updates and deletions.]
:param-related!:
include::partial$block-abstract.adoc[]
// END -- Page Heading


== Introduction

You should use the _Sync Function_ to validate any changes and to authorize document writes.


== Access Old Document

Before you can validate a document update, you often need to know which user is changing it, and sometimes you need to compare the old and new revisions.
The Sync Function makes it easy to access any pre-revision document content -- see <<ex-old-doc>>:

[#ex-old-doc]
.Access Pre-revision Document Content]
====

[source,javascript]
----
function(doc, oldDoc) { ... } // <.>
----

<.> Here in the Sync Function header, the `oldDoc` contains the document content prior to any changes.
It is empty if this is a new document.
====


== Validate Document Changes

For document schema validation, you can write your own rules in the Sync Function.
Use it to validate any document changes made before writing them.

When a document is deemed invalid, you can simply call the built-in JavaScript {sync-function-api-throw-cmd--xref} function to raise an exception and reject the revision -- see <<ex-reject>>.

Rejected documents are not saved to the Sync Gateway database, so no access changes take effect.
Instead an error code (usually 403 Forbidden) is returned to Couchbase Lite's replicator.

Any other exception (including implicit ones thrown by the JavaScript runtime, like array bounds exceptions) will also prevent the document update.
These will cause the gateway to return an HTTP `500 -- Internal Error` status.

[#ex-reject]
.Rejecting Invalid Documents
====
[source,javascript]
----
throw ({forbidden: "error message"}) // <.>
----

<.> A `403 -- Forbidden` status and the given error string is returned to the client.
====


// tag::write-access[]
[#lbl-control-write-access]
== Control Write Access

Use the Sync Function's helper functions such as {sync-function-api-require-role-cmd--xref} or {sync-function-api-require-user-cmd--xref} to specify the user(s) allowed to write a document -- see <<ex-check-write-access>>

[#ex-check-write-access]
.Checking the User to Allow Write Access
====
In this example, our simple Sync Function validates whether the user modifying a document is a valid owner by checking if they are recorded as an owner of the old document:

[source,javascript]
----
function (doc, oldDoc) {
  if (oldDoc) {
    requireUser(oldDoc.owner); // may throw({forbidden: "wrong user"})
  }
}
----
====

If the user or role making the change is not in that list, an exception is thrown and the update is rejected with an error.

Similarly, {sync-function-api-require-access-cmd--xref} requires that the user making the change has access to any of the listed channels -- see <<ex-helpers>> for more helper function usage.

NOTE: The Sync Function executes with admin privileges for changes made using the {rest-api-admin--xref}.
So, `requireUser`, `requireAccess` and `requireRole` are no-ops; they will always be successful.


[#ex-helpers]
.Helper Function examples
====
This example shows how to use some of the helper functions:

[source,javascript]
----

requireUser("snej") // <.>

requireUser(["snej", "jchris", "tleyden"]) // <.>

requireRole("admin") // <.>

requireRole(["admin", "old-timer"]) // <.>

requireAccess("events") // <.>

requireAccess(["events", "messages"]) // <.>
----
<.> throw an error if username is not "snej"
<.> throw if username is not in the list
<.> throw an error unless the user has the "admin" role
<.> throw an error unless the user has one of those roles
<.> throw an error unless the user has access to read the "events" channel
<.> throw an error unless the can read one of these channels
====


When sending a change to Sync Gateway through the {rest-api-admin--xref}, the Sync Function is executed with admin privileges: calls to `requireUser`, `requireAccess` and `requireRole` are no-ops (that is, they will always be successful).

TIP: To create and manage user accounts, refer to {xref-sgw-pg-users}.
// end::write-access[]


include::partial$block-related-content-sync.adoc[]
// END -- PAGE -- write-access.adoc