params:
  inDir: ./
  inFile: rest-api-admin
  outDir: ./
  selectors:
  - Bootstrap_model
  - Database_model
  - Replication_model
  - Role_and_User_model
pyyaml_settings:
  encoding: utf-8
  default_flow_style: false
  sort_keys: false
