= Sync Gateway Documentation

ifdef::env-github[]
:warning-caption: :warning:
endif::[]
// URLs:
:url-org: https://github.com/couchbase
:url-contribute: https://docs.couchbase.com/home/contribute/index.html
:url-workflow: https://docs.couchbase.com/home/contribute/workflow-overview.html
:url-ui: {url-org}/docs-ui
:url-playbook: {url-org}/docs-site
:url-cli: {url-org}/couchbase-cli
:url-backup: {url-org}/backup
:url-analytics: https://github.com/couchbaselabs/asterix-opt
:url-issues: https://issues.couchbase.com
:url-issues-doc: {url-issues}/browse/DOC


This repository hosts the documentation source for Couchbase's Sync Gateway product.


== Contributing


We recognize and value the experience and skills of the wider Couchbase community.
As such, open source contributions to our documentation are always welcome.

* If you find an error, or see room for improvement on a page, please don't keep it to yourself.
Even if you don't plan to make the change yourself, we would still like to know what it is!
+
Raise a DOC issue by clicking the _Leave Additional Feedback?_ link on the bottom-right of any page on this site.

* You can also submit simple changes, such as typo fixes and minor clarifications or more extensive content additions and updates -- see
{url-workflow}[Contributing Workflow].

Check out our {url-contribute}[contributing guide] to learn more on how to:

* Submit a bug or feedback issue

* Set up your documentation workspace

* build the documentation

* submit a pull request

Thank you for helping to make the documentation better.

All bugs and enhancements for the Couchbase documentation are tracked using the {url-issues-doc}[DOC project issue board^].


== Docs Component Configuration


This repository contains an Antora docs component.
Keep in mind these key repository features:

* Component name, version, and start page are configured in each branch's _antora.yml_ file.

* The navigation for Sync Gateway is stored in the ROOT module's `nav.adoc` file.

* Production branches use the *release/X.Y* naming pattern (e.g., release/2.8, release/3.0).

 ** The {url-playbook}[docs site playbook] instructs Antora to automatically aggregate any branch names that start with *release/*.

== Documentation Site Toolchain

The documentation source files are marked up with AsciiDoc.
Once merged into a version branch, the source files and their assets are aggregated, converted to HTML, and published by Antora to our staging and production sites.

The docs components and {url-ui}[site UI] are orchestrated by the {url-playbook}[docs site playbook] as described in the {url-contribute}[contributing guide].
