== 3.3.0 -- June 2025

include::partial$block-caveats.adoc[tags=eventing-mixed-mode]

=== Partitioned Indexes

Sync Gateway 3.3 introduces support for partitioned indexes.
Partitioned indexes offer horizontal scalability for large deployments by sharding indexes across multiple nodes.

=== Disable the Public All Docs Endpoint

Sync Gateway 3.3 introduces an option to disable the xref:rest_api_public.adoc#tag/Document/operation/get_keyspace-_all_docs[`GET /{keyspace}/_all_docs`] operation in the Public REST API.

=== Interactive Admin Credentials for SG Collect Info

In Sync Gateway 3.3 and later, the `sgcollect_info` tool provides an interactive password prompt so that you can enter administrative credentials.

For more information on new features and enhancements in this release, see xref:whatsnew.adoc[].

Version 3.3.0 of Sync Gateway also delivers the following features and enhancements:

[#maint-3-3-0]
=== Fixed Issues

TODO: Fixes

=== Enhancements

TODO: Enhancements

=== Known Issues

None for this release.

=== Deprecations

TODO: Deprecations

NOTE: For an overview of the latest features offered in Sync Gateway 3.3, see xref:whatsnew.adoc[].
