

// tag::operation-before[]


[[_create_db]]
==== Create a Sync Gateway database
....
PUT /{db}/
....



// tag::operation-begin[]


===== Description


// tag::description[]

Use this endpoint to add new Sync Gateway databases.

Provide the database name in the URL path.
Provide the required database configuration settings as a JSON object in the request body.

By default the created database is brought online immediately, *unless* you include `&quot;offline&quot;: true` in the configuration.

`See: {rest-api-admin--xref}` for further information on this.



// end::description[]


===== Parameters


// tag::parameters[]


[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**db** +
__required__|Database name|string
|**Body**|**db config settings** +
__required__||<<_database_configuration_model,database_configuration_model>>
|===



// end::parameters[]



===== Responses



// tag::responses[]


[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**201**|201 OK – Successful Create Operation|No Content
|**401**|401 - Unauthorized

Typically arising when the supplied basic auth credentials do not match those found on Couchbase Server|No Content
|===



// end::responses[]


===== Security


// tag::security[]



// end::security[]



// end::operation-begin[]



// end::operation-before[]



