

// tag::operation-before[]


[[_upsert_db_config]]
==== Update Sync Gateway database configuration settings
....
PUT /{db}/_config
....



// tag::operation-begin[]


===== Description


// tag::description[]

Use this endpoint to update the configuration of an existing database.

Provide the database name in the URL path.
Provide the required database configuration settings as a JSON object in the request body.
You only need to provide those settings you wish to change.

`See: {rest-api-admin--xref}` for further information on this.



// end::description[]


===== Parameters


// tag::parameters[]


[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**db** +
__required__|Database name|string
|**Body**|**db config settings** +
__required__||<<_database_configuration_model,database_configuration_model>>
|===



// end::parameters[]



===== Responses



// tag::responses[]


[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|200 OK – Successful Operation|No Content
|**401**|401 - Unauthorized

Typically arising when the supplied basic auth credentials do not match those found on Couchbase Server|No Content
|===



// end::responses[]


===== Security


// tag::security[]



// end::security[]



// end::operation-begin[]



// end::operation-before[]



