

// tag::operation-before[]


[[_upsert_role]]
==== Role
....
PUT /{db}/_role/{name}
....



// tag::operation-begin[]


===== Description


// tag::description[]

Use this convenience endpoint to upsert a Sync Gateway role for the specified database.



// end::description[]


===== Parameters


// tag::parameters[]


[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**db** +
__required__|Database name|string
|**Path**|**name** +
__required__|Role name, may contain any combination of the characters `[a-z A-Z 0-9 - + . @ %]`, when creating a role any other characters must be percent encoded, see: https://en.wikipedia.org/wiki/Percent-encoding.

When passing a role name in a URL path it must be escaped again using percent encoding e.g. if a role is created with the name "0\|59", the '\|' character must first be percent-encoded resulting in "0%7C59". When using the same role name in a URL path it must be percent-encoded a second time resulting in "0%257C59"|string
|**Body**|**role** +
__optional__|The message body is a JSON document that contains the following objects.|<<_role,role>>
|===



// end::parameters[]



===== Responses



// tag::responses[]


[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|200 OK – The role was updated successfully|No Content
|**201**|201 Created – The role was created successfully|No Content
|===



// end::responses[]


===== Security


// tag::security[]



// end::security[]



// end::operation-begin[]



// end::operation-before[]



