

// tag::operation-before[]


[[_upsert_user]]
==== Creates or updates a user
....
PUT /{db}/_user/{name}
....



// tag::operation-begin[]


===== Description


// tag::description[]

Use the `\_user` endpoint to create or update a Sync Gateway user for the specified database.



// end::description[]


===== Parameters


// tag::parameters[]


[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**db** +
__required__|Database name|string
|**Path**|**name** +
__required__|User's name, may contain contain any combination of the characters `[a-z A-Z 0-9 - + . @ %]`, when creating a user any other characters must be percent encoded, see: https://en.wikipedia.org/wiki/Percent-encoding.

When passing a user name in a URL path it must be escaped again using percent encoding e.g. if a user is created with the name "0\|59", the '\|' character must first be percent-encoded resulting in "0%7C59". When using the same user name in a URL path it must be percent-encoded a second time resulting in "0%257C59"|string
|**Body**|**body** +
__optional__|Request body|<<_user,user>>
|===



// end::parameters[]



===== Responses



// tag::responses[]


[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|200 OK – The user record was updated successfully|No Content
|**201**|201 Created – The user record was created successfully|No Content
|===



// end::responses[]


===== Security


// tag::security[]



// end::security[]



// end::operation-begin[]



// end::operation-before[]



