= Replication SDelta-Sync
:page-layout: article
:page-role: panes
:page-status: {releaseStatus} -- {releaseComments}
:page-content: conceptual
include::partial_attributes-local.adoc[]


ifeval::["{releaseStatus}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--
Document relevant aspects of _Delta Sync Behvaior in Replication_.

Information sources include:

* https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit#

--
endif::[]


[abstract]
Cover inter-sync-gateway replication Resolution Stats and Monitoring

== Overview

.points to cover, include

* {empty}
+
--
Replicator config must include a new  flag to enable/disable delta sync on a per replication basis . Defaults to OFF.

The following tables outlines the interaction with the database level delta sync flag
Database Level Disabled on Target :

Include the table
--
+
* Configuration : Design spec
+
Documentation :Must document new flag
*  Replicator config must include a new  flag to disable auto-purge on removal behavior on  a per replication basis .
+
Configuration : Design spec
+
Documentation :Must document new flag



== Related Content

[.pane__frames]

* *How-to*
+
--
include how-to links as relevant,

include how-to links as relevant,
--

* *Learn more*
+
--
include any related concept links

include tutorial links as relevant

include blog links as relevant
--

* *Reference material*
+
--
include any reference docs

(eg config file or api)
--