= Inter-Cluster Replication Types
:page-layout: article
:page-status: {release-status-sgw} -- {release-comments-sgw}
:page-edition: Under Develoment
:page-role:

include::shared-mobile::partial$_attributes-shared.adoc[]
include::partial$_attributes-local.adoc[]
:xref-pfx-sgw: {xref-pfx-sgw}:
include::partial$_page-index.adoc[]
include::partial$_glossary-links.adoc[]

ifeval::["{releaseStatus}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--
Document relevant aspects of _Replication Types_.

.Information sources include:

* Ticket: https://issues.couchbase.com/browse/DOC-6386[DOC-6386]
* Initialization: https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit#heading=h.ui85bh142wa2
* Terminology: https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit#heading=h.e6nktl2sekol

--
endif::[]

[abstract]
Sync Gateway inter-sync-gateway replication supports two replication types: _Persistent_ and _Transient_ (or _Adhoc_). Persistent replication survives restarts, whilst adhoc replications run once only, on creation.

== Overview

[.pane__frame--orange]
.Author's Notes
--
Summarize the types, their differences and why one or other may be prefered in given scenarios.
--

.Points to cover include:
* System will support the ability to setup or create two types of replications
Persistent replicators that will survive restarts.
Adhoc or transient replicators that only run one once upon creation
+
This requirement is predominantly for documentation purposes
+
Documentation: To add description in SG-Replicate page
* Users can create  ad-hoc replications via “replication” REST endpoint
+
Adhoc replications is not guaranteed to run on the node on which it is started. These replications will be distributed across available nodes
* Users can setup persistent replicators statically via config file or dynamically via a new “replication” REST endpoint
+
These replicators will survive restarts. Persistent replications will be distributed across available nodes.
+
Documentation:  This should be the recommended way of configuring replications in prod environments. With SG Replicate 2, all nodes can be configured with same replicators.
* Continuous or oneshot replicators configured via config file will automatically start when Sync Gateway is started or restarted. There will be an option to override that behavior such that they do not start automatically on launch.
+
Note : This requirement does not apply to  replications configured via REST API
+
This behavior is the same as pre-Hydrogen (Inter-sync-gateway Replication (v1))

* Users will have the option for configuring
unidirectional (source-> target (push) or target->source (pull)) or
bi-directional (source <-> target (push-pull)) replication. ‘
+
This is to simplify configuration and to also leverage the full-duplex nature of websockets connection to use  a single websocket connection for both push and pull.
* User under which replication is being run must have read and write access to data being replicated.
+
The system does not have a provision to enforce this automatically. It is upto the user to configure the sync functions appropriately to ensure consistency.
+
For instance, consider case of a target cluster in active standby,  if a document on source cluster passes validation per sync function in source cluster but it is rejected by sync function in target cluster, then the stand by cluster will not be a replica of  the original cluster
+
While it is certainly possible for clusters to be configured with different access control policies if that is the desired system behavior, users must be cautioned if that’s not what they expect.
+
Documentation: Add a note to clarify the same

== Persistent Replication

[.pane__frame--orange]
.Author's Notes
--
expand an-or edit this section, cross check with design spec.
include links to glossary content for content-reuse purposes
--

.points to cover include
--
Persistent replications are replications that survive Sync Gateway restarts.  All replications are persisted by default unless explicitly flagged as not.

// tag::glos-persistent-replication[]
Persistent replication is defined in the configuration file `sync-gateway.json` (see  xref:sync-gateway::config-properties.adoc[Sync Gateway configuration properties]).
It is started automatically and survives restarts.

// end::glos-persistent-replication[]

NOTE: Recommended method is to define a persistent replication using the _Configuration_ file.
With _SG Replicate 2.0_ you can configure all nodes with the replicators.
--

== Transient Replication

[.pane__frame--orange]
.Author's Notes
--
expand an-or edit this section, cross check with design spec.
include links to glossary content for content-reuse purposes
--

Started dynamically using the xref:sync-gateway::rest-api-client.adoc[Admin Rest API] endpoint `_replication`.

.Points to cover include
--
Adhoc are transient replicators that only run once when started. These are predominantly used for doing one off replications for troubleshooting etc. They do not survive Sync Gateway restarts.

These replications are transient and not persisted. This is useful if users want to setup  replications on-demand after Sync Gateway is started, for instance a replication that needs to be scheduled to be run at midnight every Thursday. In this case, it is likely that there is an automation script that schedules the adhoc replication on a predefined schedule. Or an emergency one-time update that needs to be pushed out to all edge from primary data clusters.
--


[.pane__frames.cols-3]
== Related Content

.How-to ...

* include how-to links as relevant,
* include how-to links as relevant,

.Learn more ...

include::partial$_related-content.adoc[tags=icr]

.Dive Deeper ...

* Reference content
** {xref-sgw-pg-config-properties}
include::partial$_related-content.adoc[tags=community]
