= Inter-Cluster Replication (SGR-1)
:pge-aliases: running-replications.adoc
:page-layout: article
:page-status: {release-status-sgw} -- {release-comments-sgw}
:page-edition: Under Development
:page-role:
:description: Inter-sync-gateway replication (Sync Gateway to Sync Gateway) using SG-Replicate1.0 protocol

include::partial$_std-hdr-sgw.adoc[]
// include::partial$block-authors-notes.adoc[tag=sgr1]

:topic-group: Inter-sync-gateway Replication
:param-related: {xref-sgw-pg-config-properties} | {xref-sgw-pg-rest-api-admin}
include::partial$block-abstract.adoc[]


// Footnotes
:fn-icr: footnote:icr[As of Sync Gateway version 2.8]
:fn-arch: footnote:arch[This architecture is also known as _ship-to-shore_ or _hub-and-spoke_.]
:fn-icr-ref: footnote:icr[]
:fn-arch-ref: footnote:arch[]

CAUTION: This content covers inter-sync-gateway replication using the Inter-sync-gateway Replication (v1) protocol.

== Replication Characteristics

= Protocol

Sync Gateway supports the ability to run replications between two Sync Gateway clusters using Inter-sync-gateway Replication (v1) (SGR-1).

SGR-1 replications are HTTP(s)-based.

One-shot replications are always run asynchronously even if the `async` property is not set to true.

Replications always run on their initializing node.



// All replications are based on a {glos-term-replication-definition} provided either to the Admin REST API or the JSON configuration file -- see: <<replication-definitions>>.

// Replications may be given a user defined `replication_id` otherwise Sync Gateway will generate a random UUID.

=== Types of Replication
Replications are either: {glos-term-adhoc-replication} (REST API only) or {glos-term-persistent-replication}.
They can also be configured to run in one of two-modes: {glos-term-continuous} or {glos-term-oneshot}.

=== Granularity

Replications take place at document level with routing provided by channel filtering where required.

=== Directionality
Replications are uni-directional between two Sync Gateway databases (local or remote).
You can achieve bi-directional replication by running multiple replications  simultaneously.
For example by running a Pull on database _A_ from _B_ and concurrently a Pull on _B_ from _A_.

== Security

=== Authentication

Under SGR01 inter-sync-gateway replications are HTTP(s)-based.

=== Access Control
Access control is achieved by using the _Sync function_ together with the security credentials (user name and password).

.Author's Note
[NOTE]
--
Include an example sync function demonstrating this.
--

== Availability and Resilience

=== High Availability
A measure of high-availability can be achieved by running a replication on multiple nodes in the cluster, although this result in redundant processing.

== Network Resilience
Network resiliency is built-in for _continuous_ replications, which will restart automatically whenever the node does and will retry lost connections every 500ms indefinitely.

== Initialization
As covered in {xref-sgw-pg-icr-sgreplicate-init},
replications are defined by a {glos-term-replication-definition} in either:

* The JSON configuration file (`sync-gateway-config.json`) for _persistent_ replications (_continuous_ or _one-shot_) -- see: <<running-configured-replications>>
* The  REST API for _ad hoc_ replications (one-shot only) -- see: <<running-rest-api-initialized-replications>>


== Replication Definitions

All replications are 'initialized' by a {glos-term-replication-definition} in the configuration file or Admin REST API.
For SGR-1 _replications definition_ are at Sync Gateway level -- see: <<replication-definition-elements>>.


[#replication-definition-elements]
.Replication Definition Elements
[cols="1,1,3,1"]
|===
|Name |Type |Description |Default

|`source`
|URL
|_Required._ A URL pointing to the source database for the replication, the URL may be relative i.e. just the name of a local database on the Sync Gateway instance.
The URL may point to the Admin REST API which will replicate all documents in the DB, or it may point to the public REST API which will only copy documents in the users assigned channels.
When specifying credentials, the URL must be of the form `user:password@host`.
|none

|`target`
|URL
|_Required._ A URL pointing to the target database for the replication, the URL may be relative i.e. just the name of a local database on the Sync Gateway instance.
The URL may point to the Admin REST API or it may point to the public REST API, this will impact the behavior of the target database sync function.
When specifying credentials, the URL must be of the form `user:password@host`.
|none

|`continuous`
|Boolean
|_Optional._ Indicates whether the replication should be a one-shot or continuous replication.
|false

|`filter`
|String
|_Optional._ Passes the name of filter to apply to the source documents, currently the only supported filter is "sync_gateway/bychannel", this will replicate documents only from the set of named channels.
|none

|`query_params`
|Object
|_Optional._ Passes parameters to the filter, for the "sync_gateway/bychannel" filter the value should be an array or channel names (JSON strings).
|none

|`cancel`
|Boolean
|_Optional._ Indicates that a running replication task should be canceled, the running task is identified by passing its `replication_id` or by passing the original source and target values.
|false

|`replication_id`
|String
|_Optional._ If the cancel parameter is true then this is the id of the active replication task to be canceled, otherwise this is the `replication_id` to be used for the new replication.
If no replication_id is given for a new replication it will be assigned a random UUID.
|false

|`async`
|Boolean
|_Optional._ Indicates that a one-shot replication should be run asynchronously and the request should return immediately.
Replication progress can be monitored by using the `_active_tasks` resource.
|false

|`changes_feed_limit`
|Number
|_Optional._ The maximum number of change entries to pull in each loop of a continuous changes feed.
|50
|===

== Running Configured Replications

All replications in the Sync Gateway configuration file will auto-start when Sync Gateway starts.
For replication definition parameters/properties -- see: <<replication-definitions>>.

NOTE: One-shot replications that reference local databases (as source or target) will start after a short delay (5 seconds) to allow the local REST APIs to start.


.Running a replication on startup
====
[source,json]
----
{
    "log":["*"],
    "replications":[
        {
            "source": "db",
            "target": "db-copy"
        },
        {
            "source": "db",
            "target": "http://user:password@example.com:4985/db-copy"
        },
        {
            "replication_id":"continuous-remote-local",
            "source": "http://user:password@example.com:4985/db-backup",
            "target": "db"
            "continuous":true
        },
        {
            "replication_id":"continuous-filtered",
            "source": "db",
            "target": "http://user:password@example.com:4985/db-copy"
            "continuous":true,
            "changes_feed_limit":1000,
            "filter":"sync_gateway/bychannel",
            "query_params":["channel1","channel2"]
        }
    ],
    "databases": {
        "db": {
            "server": "http://localhost:8091",
            "bucket": "db",
            "users": {
                "GUEST": {"disabled": false, "admin_channels": ["*"]}
            }
        },
        "db-copy": {
            "server": "http://localhost:8091",
            "bucket": "db-copy",
            "users": {
                "GUEST": {"disabled": false, "admin_channels": ["*"]}
            }
        }
    }
}
----
====

== Running REST API Initialized Replications

REST API replications are initialized and run by sending a `POST` request to the server endpoint `_replicate`, with a request body comprising a JSON object containing the replication definition's parameters.

Both one-shot and continuous replications can be run in this way.

NOTE: When running multiple replications on a Sync Gateway database both source and target databases must use identical _sync functions_, otherwise it could lead to unexpected behavior.

.Running replications via the API
=====
[{tabs}]
====

One-shot (local)::
+
--
These parameters start a one-shot replication between two databases on the local Sync Gateway instance.
The request will block until the replication has completed.

[source, json]
----
{
  "source": "db",
  "target": "db-copy"
}
----
--

One-shot::
+
--
These parameters start a one-shot replication between one database on the local Sync Gateway instance and one on a remote Sync Gateway instance, with user credentials.
The request will return immediately and the replication will run asynchronously.

[source,javascript]
----
{
    "source": "db",
    "target": "http://user:password@example.com:4985/db-copy",
    "async":true
}
----
--

Continuous::
+
--
These parameters start a continuous replication between one database on the local Sync Gateway instance and one on a remote Sync Gateway instance with the user provided `replication_id`.
The request will return immediately and the replication will run asynchronously.

[source,javascript]
----
{
    "replication_id":"my-named-replication",
    "source": "db",
    "target": "http://user:password@example.com:4985/db-copy",
    "continuous":true
}
----
--

Continuous (batched and filtered)::
+
--
These parameters start a continuous replication between one database on the local Sync Gateway instance and one on a remote Sync Gateway instance.
The replicator will batch up to 1000 revisions at a time, this will improve replication performance but will use more memory resources.
Source database documents will be filtered so that only those tagged with the channel names "channel1" or "channel2" are replicated.

[source,javascript]
----
{
    "source": "db",
    "target": "http://user:password@example.com:4985/db-copy",
    "continuous":true,
    "changes_feed_limit":1000,
    "filter":"sync_gateway/bychannel",
    "query_params":["channel1","channel2"]
}
----
--
=====





== Monitoring Replications

* Use `_active_tasks` to monitor Inter-sync-gateway Replication (v1) replications  (`GET`)
+
The content returned will be the same as that returned by `_replicationStatus` and contains additional content over the Inter-sync-gateway Replication (v1) version:
+
** direction
** is_persistent
** status (stopped/running).
** last_seq_push
** last_seq_pull

By default a simple one-shot replication blocks until it is complete and returns the stats for the completed task.
Async one-shot and continuous replications return immediately with the in flight task stats.

You can get a list of active replication tasks by sending a GET request to the `_active_tasks` endpoint, this will return a list of all running one-shot and continuous replications for the current Sync Gateway instance.

The response is a JSON array of active task objects, each object contains the original request parameters for the replication, a unique `replication_id` and some stats for the replication instance.
The list of returned stats and their meaning can be found on the API reference of the xref:admin-rest-api.adoc#/server/get\__active_tasks[`_active_tasks`] endpoint.

[source,javascript]
----
[
    {
        "type":"replication",
        "replication_id":"6a4924c24424b635a80f50cd660fb192",
        "continuous":true,
        "source":"http://example.com:4985/source",
        "target":"http://example.com:4985/target",
        "docs_read":0,
        "docs_written":0,
        "doc_write_failures":0,
        "end_last_seq":null
    },
    {
        "type":"replication",
        "replication_id":"active-to-backup",
        "continuous":true,
        "source":"http://example2.com:4985/active",
        "target":"http://example2.com:4985/backup",
        "docs_read":1000,
        "docs_written":850,
        "doc_write_failures":10,
        "end_last_seq":25680
    }
]
----

== Canceling replications

An active replication task is canceled by sending a POST request to the server endpoint `_replicate`, with a JSON object.
The JSON object must contain the `cancel` property set to true and either a valid `replication_id` or the identical source, target and continuous values used to start the replication.

This will cancel an active replication with a `replication_id` of "my-one-shot-replication", the `replication_id` value can be obtained by sending a request to `_active_tasks`.

[source,javascript]
----
{
    "cancel": true,
    "replication_id": "my-one-shot-replication"
}
----

This will cancel a replication that was started with same "source" and "target" values as those in the cancel request.
By omitting the "continuous" property it's value will default to *false*, a replication must also have been started as a one-shot to match.

[source,javascript]
----
{
    "cancel":true,
    "source": "db",
    "target": "db-copy"
}
----

When an active task is canceled, the response returns the stats of the replication up to the point when it was stopped.

[source,javascript]
----
{
    "type":"replication",
    "replication_id":"3791d562153505408e0b2730603ed7c1",
    "continuous":true,
    "source":"http://0.0.0.0:4985/source",
    "target":"http://0.0.0.0:4985/target",
    "docs_read":12,
    "docs_written":12,
    "doc_write_failures":0,
    "start_last_seq":0,
    "end_last_seq":"28"
}
----

== Replication Statistics

include::partial$icr-api-expvars-GET.adoc[]


Use the `_expvars` Admin REST API to access following stats:

|===
| Item | SGR1

|"sgr_num_attachment_bytes_transferred": 0,
|Y

| "sgr_num_attachments_transferred": 0,
|Y

| "sgr_num_docs_failed_to_push": 0,
|Y

|"sgr_num_docs_failed_to_push_access": 0,
|N

| "sgr_num_docs_pushed":
|Y

| "sgr_delta_pull_replication_count"
|NOT APPLICABLE

| "sgr_delta_push_doc_count"
|NOT APPLICABLE

| "sgr_deltas_requested":
|NOT APPLICABLE

| "sgr_deltas_sent":
|NOT APPLICABLE

|sgr_conflict_delected
|NOT APPLICABLE

|sgr_conflict_resolved
| NOT APPLICABLE

|sgw_conflict_skipped_error
|NOT APPLICABLE

|===






== Constraints
[temporary holding]
* Can only replicates SG databases that are hosted on recent versions of Sync Gateway (after commit 50d30eb3d on March 7, 2014)
* In deployments with multiple Sync Gateway nodes, only _one_ of the Sync Gateways should be configured for replications.
If multiple Sync Gateways are configured for replications, it could substantially increase the amount of duplicate work, and therefore should be avoided.
The limitation is that the system is not guaranteed to be Highly Available: if the Sync Gateway that is chosen to drive the replication goes down or is otherwise removed from the system, then the replications will stop.
* Replication between Sync Gateway databases doesn't support automatic conflict resolution even when the no-conflicts mode is enabled (i.e xref:config-properties.adoc#databases-foo_db-allow_conflicts["allow_conflicts": false]).
When running two Sync Gateway clusters with the no-conflicts mode enabled, cross-cluster document conflicts will result in that document no longer being replicated.
Deployments  must implement a custom conflict resolver in an external app as specified xref:resolving-conflicts.adoc[here].
To avoid this, the application must ensure concurrent, cross-cluster updates are not made to a given document.


include::partial$block-related-content-icr.adoc[]