= Replication Behavior
:page-layout: article
:page-status: {release-status-sgw} -- {release-comments-sgw}
:page-edition: Under Develoment
:page-role:

include::shared-mobile::partial$_attributes-shared.adoc[]
include::partial$_attributes-local.adoc[]
:xref-pfx-sgw: {xref-pfx-sgw}:
include::partial$_page-index.adoc[]
include::partial$_glossary-links.adoc[]

ifndef::release-status-sgw[:release-status-sgw!:]

ifeval::["{releaseStatus}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--
Document relevant aspects of _replication behavior, including:

* Expected Behavior

** https://issues.couchbase.com/browse/DOC-6494
** https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.vwjngb7h5lpm

* Handling Failure
** https://issues.couchbase.com/browse/DOC-6466
** See: https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e77c903#heading=h.pqomyq9rgqb0

--
endif::[]


[abstract]
Covers the topic of replication behaviour.

== Overview


[.pane__frame--orange]
.Author's Notes
--
Summarize expected, failure and  upgrade bahavior pattersn. Expand in sections below as needed.
--

.points to cover, include:




Occaecat fugiat deserunt incididunt nostrud ipsum qui est ipsum est dolor do. Aliqua laboris proident dolore consequat laboris commodo cupidatat non proident incididunt consequat incididunt et. Esse veniam commodo qui do.

Enim id labore Lorem ex deserunt et aliqua pariatur dolore aliquip incididunt exercitation excepteur dolor. Anim nulla id pariatur officia dolor consequat occaecat do consectetur aliquip magna. Veniam reprehenderit ex aliqua sunt consequat in. Lorem consequat id commodo velit sit ad tempor eu. Id reprehenderit qui adipisicing minim. Sunt enim labore quis non consectetur.

Officia esse pariatur anim consequat laboris ex ut elit ullamco anim nulla aliqua. Deserunt voluptate consequat minim ullamco ullamco ipsum exercitation. Est cillum ad aliquip esse sunt labore magna ipsum est ullamco enim et voluptate quis. Tempor do sunt occaecat exercitation dolor cupidatat veniam labore mollit est ex non mollit cupidatat. Voluptate nulla labore culpa Lorem enim voluptate dolor sint reprehenderit.

== Expected Behavior


[.pane__frame--orange]
.Author's Notes
--
Summarize expected happy path behavior
see: https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e77c903#heading=h.vwjngb7h5lpm
--


Ex dolor reprehenderit velit sint aliquip. Aliquip consectetur culpa enim ad cillum minim nisi. Veniam culpa est ad adipisicing elit esse aliquip ut mollit. Amet non ad non fugiat velit nisi minim esse consectetur aliqua eu. Nostrud eu sit aliqua do ex fugiat. Minim pariatur aute culpa eu consectetur.

Eiusmod dolor id aliqua esse enim esse dolore exercitation officia magna aliquip. Velit ad laborum cillum sint. Nisi nisi Lorem minim est commodo dolore.
// https://issues.couchbase.com/browse/DOC-6494
// https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.vwjngb7h5lpm


== Handling Failure


[.pane__frame--orange]
.Author's Notes
--
Summarize failure behaviors (eg network disconnects etc), how to handle, troubleshooting etc

* Document  Failure handling aspects 
See: https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e77c903#heading=h.pqomyq9rgqb0

* Specific highlight/callout points: include:
New property max-backoff-time: https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?disco=AAAAGVSgvNI
 
* Target is : icr-behavior.adoc#handling-failure

* see https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e77c903#heading=h.pqomyq9rgqb0
* and https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit# comments
* and scenerios in table at end of section
--



Ipsum ipsum exercitation veniam minim dolor exercitation labore non elit amet id cillum ut exercitation. Quis mollit ullamco aliquip eiusmod ex veniam nostrud sint dolor culpa aute mollit. Aute laboris irure laborum cupidatat non pariatur incididunt eu fugiat. Nulla ea voluptate anim qui. Culpa qui excepteur eu cillum mollit fugiat do.

Officia ad in laborum aute est et fugiat. Tempor ad non irure Lorem qui ut tempor. Sit fugiat mollit anim magna veniam labore occaecat non voluptate nulla ipsum. Sunt reprehenderit eu do eu sunt laboris velit laboris sint. Deserunt et nisi qui deserunt nisi aliqua occaecat ex enim culpa tempor. Adipisicing ad ut ipsum ipsum nisi eu exercitation. Sunt cupidatat officia sunt laborum irure sunt nulla enim in cillum.
// https://issues.couchbase.com/browse/DOC-6466
// See: https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e77c903#heading=h.pqomyq9rgqb0


== Upgrade Behavior


[.pane__frame--orange]
.Author's Notes
--
see: https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit#heading=h.4s8odjf16mf1

Refer to upgrade.adoc as needed
--

[.pane__frames.cols-3]
== Related Content

.How-to ...

* include how-to links as relevant,
* include how-to links as relevant,

.Learn more ...

* {empty}
+
--
include::partial$_related-content.adoc[tags=icr]
--

.Dive Deeper ...

* Reference content
** {xref-sgw-pg-config-properties}
include::partial$_related-content.adoc[tags=community]

