= Inter-sync-gateway Replication
:page-layout: article
:page-partials:
:page-partial:
:page-status:
:page-edition:
:page-role: conceptual
:description: Couchbase inter-sync-gateway replication -- resilient, secure, scalable bidirectional synchronization of data between cloud and edge data centers.

include::partial$_std-hdr-sgw.adoc[]

:topic-group: {tg-rep-icr}
:param-related: {xref-sgw-pg-config-properties} | {xref-sgw-pg-rest-api-admin}
:param-abstract: This content provides an introduction to, and overview of, Couchbase Sync Gateway's inter-sync-gateway replication feature
include::partial$block-abstract.adoc[]

// Footnotes
:fn-sgr1: footnote:sgr1[Inter-sync-gateway Replication (v1) only]
:fn-sgr2: footnote:sgr2[Inter-sync-gateway Replication (v2) only]
:fn-arch: footnote:arch[This architecture is also known as _ship-to-shore_ or _hub-and-spoke_.]
:fn-icr: footnote:icr[As of Sync Gateway version 2.8]
:fnref-icr: footnote:icr[]
:fnref-arch: footnote:arch[]
:fnref-sgr1: footnote:sgr1[]
:fnref-sgr2: footnote:sgr2[]

include::partial$block-caveats.adoc[tags=sgr2-only]


== Introduction
// tag::intro-full[]
// tag::intro[]
Couchbase Sync Gateway's _{glos-term-inter-sync-gateway-replication}_{fn-icr} feature supports _{glos-term-cloud-to-edge} synchronization_ use cases, where data changes must be synchronized between a centralized cloud cluster and a large number of edge clusters whilst still enforcing fine grained access control.
This is an increasingly important enterprise-level requirement.

// end::intro[]
In the architecture diagram (<<icr-architecture>>), the replicator on the active Sync Gateway node ensures that any database changes made to documents in either {glos-term-sync-gateway-database} instance are replicated to the other Sync Gateway instance, in accordance with the replication's configuration -- see {xref-sgw-pg-config-properties-db-replications} for configuration details.

// tag::intro-img[]

[[icr-architecture]]
.Inter-sync-gateway replication architecture
image::icr-replication-overview.svg[]

// end::intro-img[]
// end::intro-full[]

== Use Cases

// tag::use-cases[]

Cloud-to-edge synchronization::
+
--
In this multi-cloud deployment mode large numbers of multiple edge clusters sync with one or more clusters in cloud data centers. Each edge can operate autonomously without network connectivity to the cloud data centers {fn-arch}.

A typical architecture for this use cases is shown in <<icr-cloud-to-edge>>

[[icr-cloud-to-edge]]
.Cloud-to-edge synchronization
image::icr-cloud-to-edge200712.svg[,600]
--

Active-to-active Mobile Synchronization::
+
--
Here active mobile clusters at the edge are replicated between geographically separate cloud-based Sync Gateway deployments.

A typical architecture for this use cases is shown in <<icr-active-mobile>>

[[icr-active-mobile]]
.Active-active mobile synchronization
image::icr-active-mobile-sync200713.svg[,600]

--

// end::use-cases[]

== Replication Characteristics
_In this section_:  <<context>>  |  <<protocol>>  |  <<types-of-replication>>  |  <<delta-sync>>  |  <<directionality>>  |  <<security>>

=== Context
Sync Gateway supports the ability to run replications between Sync Gateway clusters using Inter-sync-gateway Replication (v2), with the {glos-term-active-replicator} {glos-term-synchronizing} changes between two {glos-term-sync-gateway-databases}.

All replications are based on a {glos-term-replication-definition} provided either to the Admin REST API or in Sync Gateway's configuration file (JSON).

Replications always involve at least one local database.
Sync Gateway does not enable replication between two _remote_ nodes, because replications are defined at database level and so at least one database will be local.

All replications take place at the document level (but see also, <<delta-sync>>).

Sync Gateway nodes can opt-out of participating in the replication process using the database-level parameter {xref-sgw-pg-config-properties-databases-sgr-enabled}.

_Related configuration elements_:  {xref-sgw-pg-config-properties-databases}  |  {xref-sgw-pg-config-properties-db-replications}  |  {xref-sgw-pg-config-properties-db-rep-remote} |  {xref-sgw-pg-config-properties-databases-sgr-enabled}

=== Protocol

Inter-sync-gateway Replication (v2), are websocket-based.

NOTE: For users on releases prior to 2.8 only HTTP-based replication is possible. See the appropriate documentation here -- {xref-sgw-pg-icr-sgreplicate-sgr1}.

The bi-directional, persistent, nature of websocket connections is ideal for applications such as a _continuous_ Sync Gateway replication, which is constantly waiting-for and synchronizing change events.

// === General Characteristics

=== Types of Replication

Replications are either: {glos-term-adhoc-replication} (REST API only) or {glos-term-persistent-replication}.
They can also be configured to run in one of two-modes:
{glos-term-continuous} or {glos-term-oneshot}.

* Persistent
+
--
Persistent replications survive Sync Gateway node restarts and continue running automatically unless configured not to.
They can be configured to run in either {glos-term-continuous} or {glos-term-oneshot} mode.
--
* Ad hoc
+
--
Ad hoc replications are transient, existing only for the period of the replication.
They provide a convenient way to:

* Run one off replications (for example, when troubleshooting)
* Run on-demand replications after Sync Gateway is started.
For instance a replication that needs to be to be run only periodically can be configured as an ad hoc replication by an automated script scheduled to run when needed.
--

_Related configuration elements_:  {xref-sgw-pg-config-properties-db-replications}  |  {xref-sgw-pg-config-properties-db-rep-continuous} |  {xref-sgw-pg-config-properties-db-rep-adhoc}

=== Delta Sync
include::partial$block-caveats.adoc[tag=ee-only-feature]

With delta-sync enabled on the replication and both databases involved, only the changed data items are transferred.

You can configure replications to use delta-sync by:

* Setting `"enable_delta_sync": true` in the _replication definition_
* Setting `"delta-sync": { "enabled": true}` on both databases in their respective _database definitions_.

NOTE: Push replications to pre-2.8 targets do not use Delta Sync

_Related configuration elements_:  {xref-sgw-pg-config-properties-databases}  |  {xref-sgw-pg-config-properties-db-replications}  |
{xref-sgw-pg-config-properties-databases-delta-sync}  |  {xref-sgw-pg-config-properties-db-rep-delta}

=== Directionality

Replications are bi-directional.
You can _push_, _pull_ or _push and pull_ between the two database endpoints.

_Related configuration elements_:  {xref-sgw-pg-config-properties-db-replications}  |  {xref-sgw-pg-config-properties-db-rep-direction}


=== Security
// tag::security[]
Transport level security is provided by HTTPS or WSS (for websockets{fnref-sgr2}).

// end::security[]

==== Authentication
// tag::authentication[]
Support for Basic Authentication using username and password credentials is provided (optional TLS Certificate authentications is also available {fnref-sgr2}).

// end::authentication[]

==== Access Control
// tag::access-control[]
// tag::access-control-full[]
Data access control is provided by Sync Gateway's {glos-term-sync-function} and the username/password credentials.
All replicated documents pass through this function ensuring that access permissions are adhered to.

// end::access-control[]
_Related configuration elements_:  {xref-sgw-pg-config-properties-databases}  |  {xref-sgw-pg-config-properties-databases-sync} +
_Related how-to_: {xref-sgw-pg-def-sync-function}  |  {xref-sgw-pg-adv-sgw-cfg-sync-function}
// end::access-control-full[]


== Network Resilience
// tag::network-resilience[]
Persistent inter-sync-gateway replications will automatically attempt to restart whenever the node does.

Network resiliency is built-in for _continuous_ replications.
They respond to network issues such as lost connections, by applying a {glos-term-persistent-exponential-backoff} policy to attempt reconnection.

The {xref-sgw-pg-config-properties-db-rep-backoff} determines the maximum wait time between retries.
When the limit is reached retries are made every `max_backoff_time` minutes.
Set `"max_backoff_time": 0` to prevent indefinite retries. Exponential backoff retries will be attempted for up to 5 minutes and then stop if the connection has not been re-established

.AD HOC Replications
[NOTE]
====
No automatic reconnection attempts are made following network failures for ad hoc replications.
The controlling user or application should apply the appropriate corrective action.
====
// end::network-resilience[]

{empty} +
_Related replication definition elements_:  {xref-sgw-pg-config-properties-db-rep-backoff}


== High Availability

include::partial$incpg-icr-availability.adoc[leveloffset=+1]

== Conflict Resolution

include::partial$incpg-icr-conflict.adoc[leveloffset=+1]

==  Replication Initialization

include::partial$incpg-icr-initialization.adoc[leveloffset=+1]

== Replication Management

include::partial$incpg-icr-admin.adoc[leveloffset=+1]

== Replication Monitoring

include::partial$incpg-icr-monitoring.adoc[leveloffset=+1, tags=!overview]


include::partial$block-related-content-icr.adoc[]