// Save the previous example-caption value
:this-caption: {example-caption}
:example-caption: FAQ#
//
// DO NOT REMOVE OR CHANGE ABOVE THIS LINE

<<I>>

== I

=== Inter-sync-gateway replication

.How do I cancel an existing replication?
====
Send a `PUT` request to the `_replication` endpoint, with a JSON object containing the replication definition and the additional `"cancel": true` parameter +
See: {xref-sgw-sgreplicate-sgr2}
// #canceling-a-replication
====

.How do I change an existing replication definition?
====
Send a `PUT` request to the `_replication` endpoint.
Specify just the changed items in the JSON body. +
See: {xref-sgw-sgreplicate-sgr2}
// #updating-a-replication
====

.How do I remove a persistent replication completely?
====
Send a `DELETE` request to the `replication` endpoint specifying the replication_id to remove +
See: {xref-sgw-sgreplicate-sgr2}
// #remove-a-replication
====



.How do I start a 'stopped' replication?
====
Send a `POST` request to the `_replicationStatus` endpoint with `action=start` +
See: {xref-sgw-sgreplicate-sgr2}
// #starting-a-replication
====

// DO NOT REMOVE OR CHANGE BELOW THIS LINE
// Reset the previous example-caption value
:example-caption: {this-caption}