= _qlossary_terms.adoc -- for inclusion only

// tag::glos-cfg-rep-adhoc-def[]
Use the Admin REST API's `adhoc` parameter to specify that a replication is ad hoc rather than persistent.
// end::glos-cfg-rep-adhoc-def[]

// tag::glos-cfg-rep-batch-size-def[]
Use `batch_size` to specify the number of changes to be included in a single batch during replication.
// end::glos-cfg-rep-batch-size-def[]

// tag::glos-cfg-rep-cancel-def[]
Use the Admin REST API's `cancel` parameter only when you want to want to cancel an existing active replication.
// end::glos-cfg-rep-cancel-def[]

// tag::glos-cfg-rep-conflict-def[]
Use `conflict_resolution_type` to specify how Sync Gateway should resolve conflicts. By default the automatic conflict
// end::glos-cfg-rep-conflict-def[]

// tag::glos-cfg-rep-continuous-def[]
Use `continuous` to specify whether this replication will run continuously, or be one-shot.
// end::glos-cfg-rep-continuous-def[]

// tag::glos-cfg-rep-resolver-def[]
Use `custom_conflict_resolver` to provide the Javascript function used to resolve conflicts if `"conflict_resolution_type": "custom"`.
// end::glos-cfg-rep-resolver-def[]

// tag::glos-cfg-rep-direction-def[]
Use `direction` to specify the replication is *push*, *pull* or *pushAndPull* relative to this node.
// end::glos-cfg-rep-direction-def[]

// tag::glos-cfg-rep-delta-def[]
Use `enable_delta_sync` to specify use of delta sync for a replication.
// end::glos-cfg-rep-delta-def[]

// tag::glos-cfg-rep-filter-def[]
Use `filter` to specify the name of the function to be used to filter documents.
// end::glos-cfg-rep-filter-def[]

// tag::glos-cfg-rep-backoff-def[]
Use `max_backoff_time` to specify the number of minutes Sync Gateway will spend trying to reconnect lost or unreachable `remote` targets.
// end::glos-cfg-rep-backoff-def[]

// tag::glos-cfg-rep-purge-def[]
Use `purge_on_removal` to specify (per replication) whether removing a `channel` should trigger a purge.
// end::glos-cfg-rep-purge-def[]

// tag::glos-cfg-rep-query-def[]
Use `query_params` to specify the key/value pairs to be passed to the filter named in `filter`.
// end::glos-cfg-rep-query-def[]

// tag::glos-cfg-rep-remote-def[]
Use `remote` to specify the database endpoint on the remote Sync Gateway custer.
// end::glos-cfg-rep-remote-def[]

// tag::glos-cfg-rep-rep-id-def[]
Use `replication_id` to specify an identifying name for the replication.
// end::glos-cfg-rep-rep-id-def[]

// tag::glos-cfg-rep-state-def[]
Use `state` to specify the state in which to launch the replication.
// end::glos-cfg-rep-state-def[]