// BEGIN inclusion -- block-links-cbl -- Renders line of links to CBL pointing to required anchor )pre-2.8
// Require: param-page == page name
// Optional: param-path == library(ies) containing page
// Optional: param-bookmark == section within page

// :xref-cbl-pg-replication: {xref-pfx-cbl}{xref-cbl-module}/learn/{xref-cbl-lang}-replication.adoc

:this-path: {empty}
:this-bookmark: {empty}
:this-version: {version}
:pre-2x8: false
:xref-pfx: xref:{this-version}@couchbase-lite:

ifdef::param-page[]
// Then do the following
ifdef::param-path[:this-path: {param-path}/]
ifdef::param-bookmark[:this-bookmark: #{param-bookmark}]
ifdef::{param-version}[:this-version: {param-version}]


====
.Related Couchbase Lite content

ifeval::[{this-version}>=2.8 ]
{xref-pfx}android:{this-path}java-android-{param-page}.adoc{this-bookmark}[Android] |
{xref-pfx}csharp:{this-path}csharp-{param-page}.adoc{this-bookmark}[C#] |
{xref-pfx}java:{this-path}java-{param-page}.adoc{this-bookmark}[Java] |
{xref-pfx}objc:{this-path}objc-{param-page}.adoc{this-bookmark}[Objective-C] |
{xref-pfx}swift:{this-path}swift-{param-page}.adoc{this-bookmark}[Swift] |
// endif for ifdef::this-version >=2.8
endif::[]

ifeval::[{this-version}<2.8 ]
{xref-pfx}ROOT:java-platform.adoc#{param-bookmark}[Java] |
{xref-pfx}ROOT:java-android.adoc#{param-bookmark}[Android] |
{xref-pfx}ROOT:csharp.adoc#{param-bookmark}[C#] |
{xref-pfx}ROOT:objc.adoc#{param-bookmark}[Objective-C] |
{xref-pfx}ROOT:swift.adoc#{param-bookmark}[Swift]
// endif for ifdef::this-version <2.8
endif::[]

====

// endif for ifdef::param-page
endif::[]
:param-path!:
:param-page!:
:param-bookmark!:

// END inclusion -- block-links-cbl -- Renders line of links to CBL pointing to required anchor )pre-2.8


