// inclusion directing user to SGR1 content
// tag::icr-sgr1-redirect[]
For information on replications run using older versions of Inter-Sync-Gateway Replication -- see {xref-sgw-pg-icr-sgreplicate-sgr1}.
// end::icr-sgr1-redirect[]

// tag::icr-community-redirect[]
Unless otherwise stated this content relates only to replications run using the Inter-sync-gateway Replication (v2) protocol in {enterprise} deployments.
For information on replications run in {community} deployments -- see {xref-sgw-pg-icr-sgreplicate1}.
// end::icr-community-redirect[]

// tag::enterprise-only[]
NOTE: Unless otherwise stated this content relates only to {enterprise}
// end::enterprise-only[]


// tag::sgr2-only[]
NOTE: This content relates only to replications run using the latest version of Inter-sync-gateway Replication (i.e. v2).
// end::sgr2-only[]


// tag::community-only-rep-same-node[]

''''
{community} Only::
Replications always run on the node on which they are configured.
Users can only access replications on the node from which they make the request.

''''
// end::community-only-rep-same-node[]


// tag::community-only[]
NOTE: Unless otherwise stated this content relates only to {community}
// end::community-only[]

// tag::ee-only[]
ifndef::param-msg[]
:param-msg: This content relates only to the {enterprise}
endif::[]

[NOTE]
.ENTERPRISE EDITION ONLY
====
{param-msg}
====
:param-msg!:
// end::ee-only[]

// tag::ce-only[]
ifndef::param-msg[]
:param-msg: This content relates only to the {community}
endif::[]

[NOTE]
.COMMUNITY EDITION ONLY
====
{param-msg}
====
:param-msg!:
// end::ce-only[]
