

// tag::icr-community-redirect[]
Unless otherwise stated this content relates only to Inter-Sync Gateway replications in {enterprise} deployments.
For information on replications run in {community} deployments -- see {xref-sgw-pg-icr-sgreplicate1}.
// end::icr-community-redirect[]

// tag::ee-only-feature[]
// tag::ee-only-content[]

IMPORTANT: This content relates only to {enterprise}

// end::ee-only-content[]
// end::ee-only-feature[]

// tag::enterprise-only[]
// tag::ee-only[]
// NOTE: This feature is available only in {enterprise}
:param-edition: {enterprise}
:param-intro: Except where otherwise stated, this feature relates only to {enterprise}
include::partial$block-highlight.adoc[]

// end::ee-only[]
// end::enterprise-only[]


// Relating to inter-Sync Gateway replications in pre-2.8 (aka SG Replicate)
// tag::sgr1-only[]

.Context Clarification
[CAUTION]
--
This content relates to inter-Sync Gateway replication in pre-2.8 versions of Sync Gateway, also known as SG Replicate.
// tag::icr-sgr2-redirect[]
For documentation on inter-Sync{nbsp}Gateway replication in Sync Gateway 2.8+ see {xref-sgw-pg-icr-sgreplicate}
// end::icr-sgr2-redirect[]
--

// end::sgr1-only[]

// Relating only to inter-Sync Gateway replications in 2.8+
// tag::sgr2-only[]

.Context Clarification
[CAUTION]
--
This content relates only to inter-Sync Gateway replication in Sync Gateway 2.8+.
// tag::icr-sgr1-redirect[]
For documentation on pre-2.8 inter-Sync Gateway replication (also known as SG Replicate) -- see {xref-sgw-pg-icr-sgreplicate-sgr1}
// end::icr-sgr1-redirect[]

--

// end::sgr2-only[]


// tag::community-only-rep-same-node[]
:param-edition: {community}
:param-body: Replications always run on the node on which they are configured. Users can only access replications on the node from which they make the request.
include::partial$block-highlight.adoc[]

// end::community-only-rep-same-node[]


// tag::ce-only[]
// tag::community-only[]
:param-edition: {community}
:param-body: Unless otherwise stated this content relates only to {community}
include::partial$block-highlight.adoc[]

// end::community-only[]
// end::ce-only[]


// tag::ce-only[]
ifndef::param-msg[]
:param-msg: This content relates only to the {community}
endif::[]

[NOTE]
.COMMUNITY EDITION ONLY
====
{param-msg}
====
:param-msg!:
// end::ce-only[]


// tag::deprecated-feature[]
NOTE: This feature is deprecated.

// end::deprecated-feature[]

// tag::developer-preview[]
.Developer Preview
[CAUTION]
--
This is a Developer Preview feature, intended for development purposes only; the API is uncommitted.
Do not use this feature in production.
No Enterprise Support is provided for Developer Preview features.

Refer to xref:server:developer-preview:preview-mode.adoc[Developer Preview Mode] for more information.
--
// end::developer-preview[]

// tag::ephemeral-buckets[]

.Couchbase Server Bucket Types
[NOTE]
Use only *Couchbase* bucket types in _Couchbase for Mobile and Edge_.
We do not support the use of Couchbase Server's *Ephemeral* or *Memcached* bucket types -- for more on bucket types see:  Couchbase Server xref:server:learn:buckets-memory-and-storage/buckets.adoc[bucket types].

// end::ephemeral-buckets[]