// BEGIN -- inclusion -- cfg-ext-javascript.adoc
//  Begin -- Inclusion Definition
//    Params -- None
//    Used-by --
//      configuration-properties.adoc
//      sync-function.adoc
//    Requires -- partial$_page-index.adoc attributes
//  End -- Inclusion Definition
//  Begin -- Inclusion Content
:fn-3x0: footnote:fn30[Commencing with release 3.0]
:fnref-3x0: footnote:fn30:[]

== Introduction
// tag::intro[]
Sync Gateway supports the use of Javascript functions to customize the sync process.
These functions are referenced from with the {legacy-configuration-properties--xref} file and may be provided either as:

* An inline Javascript function
* An external Javascript file or HTTP/HTTPS endpoint
 footnote:[Sync Gateway 3.0 or later].

// end::intro[]

== Operation
During database setup, Sync Gateway inspects the config file to identify and provision:

* Any inline JavaScript defined against any of the eligible configuration options
* Any external file or HTTP/S endpoint specified against any of the eligible configuration options that resolves to a Javascript function.

== Eligible Options
Inline or external Javascript functions can be provided for any or all of the following configurable options:

* Sync Function
* Import Filter
* Custom Conflict Resolver
* Webhook Filter

== Configuration
// tag::config-full[]
Configuration of Javascript functions, whether inline or external, is done within the configuration file -- see: <<ex-jsfunc-opts>>

* Inline Javascript functions provided within the Configuration file must be enclosed by a backtick pair (``).

* {empty}
+
--
To use an external Javascript function for any of the eligible options, you need to specify the absolute path to the Javascript.
The format and content of the external Javascript is the same as that provided inline.

NOTE: You must register a CA certificate for the appropriate server if external Javascript functions are hosted on HTTPS endpoints.
--

// tag::config-example[]
[#ex-jsfunc-opts]
.Configuring a Javascript Sync Function
====
This example shows the different ways you might provide a Javascript Sync Function.
Although the example uses the Sync Function, the same approach applies wherever a Javascript function is valid (including with Import Filter, Webhook and Custom Conflict Resolver).
[source, json]
----
{
   "databases": {
      "db1": { // <.>
         "bucket": "bucket1",
         "server": "couchbase://localhost1",
         "sync": "/opt/couchbase-sync-gateway/sync.js"
      },
      "db2": { // <.>
         "bucket": "bucket2",
         "server": "couchbase://localhost2",
         "sync": "https://localhost/sync/func2"
      },
      "db3": { // <.>
         "bucket": "bucket3",
         "server": "couchbase://localhost3",
         "sync": `function(doc,oldDoc){ if (doc.published) { channel("public");} }`
      }
   }
}
----
<.> Here we specify an external file `sync.js` as containing the external function to be provisioned
<.> Here we specify a HTTPS endpoint as resolving to a Javascript function to be provisioned
<.> Here we specify inline Javascript (surrounded by a pair of backticks (``) as the function to be provisioned

====
// end::config-example[]
// end::config-full[]

//  End -- Inclusion Content
// END -- inclusion -- cfg-ext-javascript.adoc