// BEGIN -- inclusion -- cfg-ext-javascript.adoc
//  Begin -- Inclusion Definition
//    Params -- None
//    Used-by --
//      rest-api-admin-database.adoc
//      configuration-properties-legacy.adoc
//      sync-function.adoc
//    Requires -- partial$_page-index.adoc attributes
//  End -- Inclusion Definition
//  Begin -- Inclusion Content
:fn-3x0: footnote:fn30[Commencing with release 3.0 BETA]
:fnref-3x0: footnote:fn30:[]

== Introduction
// tag::intro[]
Sync Gateway supports the use of Javascript functions to customize the sync process.
These functions are referenced from within the Sync Gateway Configuration and may be provided either as:

* An inline Javascript function
* An external Javascript file
* An external HTTP/HTTPS endpoint serving a JS function
 footnote:[Sync Gateway 3.x].

// end::intro[]

== Operation
During database setup, Sync Gateway inspects the database configuration to identify and provision:

* Any inline JavaScript defined against any of the eligible configuration options
* Any external file or HTTP/S endpoint specified against any of the eligible configuration options that resolves to a Javascript function.


== Eligible Options
Inline or external Javascript functions can be provided for any or all of the following configurable options:

* Sync Function
* Import Filter
* Custom Conflict Resolver
* Webhook Filter


== Configuration
// tag::config-full[]
NOTE: {sgw-s} 3.+ configuration of Javascript functions is done using the {rest-api-admin--xref}; specifically the {rest-api-admin--xref--access-control} and {rest-api-admin--xref--import-filter} endpoints.

Before 3.0 BETA, configuration was done within the database configuration -- see: <<ex-jsfunc-opts>>

* Inline Javascript functions provided within the database configuration must be enclosed by a backtick pair (``).

* {empty}
+
--
To use an external Javascript function for any of the eligible options, you need to specify the absolute path to the Javascript.
The format and content of the external Javascript is the same as that provided inline.

NOTE: You must register a CA certificate for the appropriate server if external Javascript functions are hosted on HTTPS endpoints.

TIP: For testing purposes you may use the unsupported configuration option `{configuration-schema-database--xref--unsupp-remote-config-tls-skip-verify}`.
Setting this `true` will side-step essential security checks.
Do not use in Production deployments.
--

// tag::config-example[]
[#ex-jsfunc-opts]
.Configuring a Javascript Sync Function
====
This example shows the different ways you might provide a Javascript Sync Function.
Although the example uses the Sync Function, the same approach applies wherever a Javascript function is valid (including with Import Filter, Webhook and Custom Conflict Resolver).

[source, json]
----

curl -X PUT 'http://localhost:4985/db1/_config' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data-raw '{
         "sync": "/opt/couchbase-sync-gateway/sync.js" // <.>
      },
    }
}'


  curl -X PUT 'http://localhost:4985/db2/_config' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data-raw '{
         "sync": "https://localhost/sync/func2" // <.>
      }
   }
}


curl -X PUT 'http://localhost:4985/db3/_config' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data-raw '{
         "sync": `function(doc,oldDoc, meta){ if (doc.published) { channel("public");} }`
      } // <.>
   }
}
----
<.> Here we specify an external file `sync.js` as containing the external function to be provisioned
<.> Here we specify a HTTPS endpoint as resolving to a Javascript function to be provisioned
<.> Here we specify inline Javascript (surrounded by a pair of backticks (``) as the function to be provisioned

====
// end::config-example[]
// end::config-full[]

//  End -- Inclusion Content
// END -- inclusion -- cfg-ext-javascript.adoc