// BEGIN -- INCLUSION DEFINITION -- modules/ROOT/pages/_partials/common-releasenotes.adoc
//  Purpose:
//    Provide release note body content for use in the release-notes and other topics as required
//  Parameters:
//    None
//  INCLUSION USAGE --
//    This module uses attributes from:
//    - /modules/ROOT/pages/_partials
//    - /modules/ROOT/pages/_partials/_page-index.adoc -- {xref-xxx} attributes used as links to pother pages
// INCLUSION USAGE
// END -- INCLUSION DEFINITION -- modules/ROOT/pages/_partials/common-releasenotes.adoc

// BEGIN DO NOT REMOVE
:root-partials: partial$
:root-commons: partial$
:module-partials: partial$

:xref-sgw-bmk-cfg-dbsvr: xref:{configuration-properties--page}#databases-this_db-server[Couchbase Server Connection String]
:xref-sgw-bmk-cfg-hideprodvn: xref:{configuration-properties--page}#hide_product_version[Hide Product Version in Headers]

// END DO NOT REMOVE


[#lbl-rel300]
== Release {version-full} {version-date}
====
<<new-features-300>> *|* <<improvements-300>> *|* <<issues-and-resolutions-300>> *|* <<support-notices-300>> *|* <<Related Content>>
====

// tag::feature-highlights-300[]
// tag::new-300-all[]

[#new-features-300]
=== New Features

// tag::features-300[]

==== Centralized Persistent Modular Configuration
// tag::new-300-centralized-cfg[]
// tag::new-300-centralized-cfg-full[]
_Centralized Persistent Modular Configuration is a core enhancement that makes it simpler for administrators to configure and manage the Sync Gateway._

This enhancement removes reliance on monolithic JSON configuration files whilst providing a modular and _cluster-aware_ approach to Sync Gateway node configuration.

Basic startup configuration settings bootstrap your Sync Gateway nodes and securely connect them to a Couchbase Server.
Configuration of cluster-wide Sync Gateway databases, access control policies and inter-Sync Gateway replications is then provided using the Admin REST API.

Persistent configuration changes made to any node in a {sgw} cluster are automatically propagated throughout the cluster or -- by using {sgw-s} groups -- a defined cluster subset.
These changes persist across {sgw} restarts.

Your existing JSON configurations can be automatically converted to the new centralized persistent modular configuration format on start-up; there is an opt-out for user wishing to temporarily continue working in pre-3.0 mode.
// end::new-300-centralized-cfg[]
Additional Detail::

// tag::new-300-centralized-cfg-extended[]
* Ad Hoc database config changes made via REST API are persisted in corresponding server bucket and are not lost during sync gateway restarts - either crashes or deliberate restarts).
* The ability to centrally update the database config in large clusters simplifies manageability and administration. Database changes made to a node are automatically applied to all nodes in a cluster or  can be scoped to a subset of nodes.
* The ability to securely administer the Sync Gateway cluster using the admin REST endpoint enables programmatic control and simplifies remote administration in cloud deployments without relying on options like SSH-tunneling.
* Maintaining a monolithic file is difficult especially if the configuration is complex. Multiple sync gateway databases may be defined in a single config file. This has potentially undesirable consequences in multi-tenant applications where database changes made for one tenant would require a restart of the node impacting all tenants.
* A simple migration path ensures that existing JSON configurations are automatically converted to the new persistent modular cpnfiguration format on start-up.
Users can opt-out of this should they wish to continue working in pre-3.x mode.
// end::new-300-centralized-cfg-extended[]
// tag::new-300-centralized-cfg[]

More::
  {configuration-overview--xref}
// end::new-300-centralized-cfg[]
// end::new-300-centralized-cfg-full[]

==== TLS Encryption Enabled by Default
// tag::new-300-tls-full[]
// tag::new-300-tls[]
_The default enabling of secure TLS connections for all Couchbase Server, Client and REST API communication ensures that all communication is encrypted; enforcing and encouraging security best practices._

Sync Gateway supports v1.3 of TLS by default.
No un-encrypted access using non-TLS schemes (for example, `couchbase://` or `http://`) is permitted for client side network traffic through Couchbase Lite replications, the REST API endpoints, nor Couchbase Server.

While we strongly recommend always having TLS enabled, we recognize that users may want to disable it for development and testing environments; there is an opt-out option to do this.
// end::new-300-tls[]
// tag::new-300-tls-extended[]

// end::new-300-tls-extended[]
// tag::new-300-tls[]

More::
  {secure-sgw-access--xref}

// end::new-300-tls[]
// end::new-300-tls-full[]


==== Secure Remote Administration
// tag::new-300-secure-admin-full[]
// tag::new-300-secure-admin[]
_This major enhancement complements the introduction of the centralized persistent configuration by introducing secure administration of a cluster through the Admin REST API._

The Admin REST API now enforces authentication and role-based access control by default.

All Admin API traffic must be conducted using existing, valid, Couchbase Server RBAC user credentials.
These users must be set-up with specific sync gateway roles.

A similar approach is also adopted for users of the Metrics API.
Public API users are not impacted by the change.
// end::new-300-secure-admin[]
// tag::new-300-secure-admin-extended[]
With authentication support, the admin API can be securely accessed from external clients without the need for network infrastructure based access control mechanisms such as SSH tunneling or firewall rules to restrict access to certain subnets or machine(s). Remote administration is particularly important in distributed cloud deployments.Remote administration is essential in many cases. Backend server applications such as identity servers may require programmatic access to the admin REST API for configuring sync gateway users. With the new release, database administration and sync function updates can be securely handled via the REST endpoint.
User-level access restrictions offer more flexibility than network-level firewalls. For instance, administrators may require temporary access to the Sync Gateway’s admin APIs from a network that is not in the allow-list per firewall policies.
Different applications have different purposes and different users. With this enhancement, only users with a specific Sync Gateway role will be able to administer the Sync Gateway through the admin REST endpoint. Future releases of Couchbase Server will include support for finer grained Sync Gateway roles that would allow more granular control over the admin functionality. So stay tuned!
// end::new-300-secure-admin-extended[]
// tag::new-300-secure-admin[]

More::
  {rest-api-access--xref}

// end::new-300-secure-admin[]
// end::new-300-secure-admin-full[]


==== User Defined Extended Attributes(XAttrs) for Defining Access Grant Data

// tag::new-300-xattrs-full[]
// tag::new-300-xattrs[]
_Use extended attributes (metadata) to avoid the need to embed sensitive access grant information such as channels and roles within document bodies._

This key architectural enhancement enforces separation of concerns by providing you the option to use Extended Attributes (XATTRs) to specify channel access grants outside of your document bodies.

In addition to addressing privacy concerns, this feature can result in bandwidth savings as it ensures that changes to access grants do not impact document body content and so are no longer propagated to clients.

// end::new-300-xattrs[]

// tag::new-300-xattrs-extended[]
The separation of access grant metadata from document body is logical and offers several benefits:

* Embedding access grant metadata within the document body implies that changes to the access grants associated with a document will result in a corresponding update to the document body.
The document update in turn will trigger a document replication to the clients.
Access grant changes are irrelevant to clients resulting in “noise”.
More importantly, if the channel list is large, then the document replications could result in significant bandwidth usage.
* Embedding channel access grants within the document body will make that information accessible to all users who are syncing that document. This may raise certain privacy concerns.
For example, if channel names correspond to user IDs, then a user replicating a document would have knowledge of other users who have access to the document.
* The data model of existing documents do not have to be modified in order to retrofit access grant data with a dedicated property.
So existing processes and applications do not have to be modified to use Sync Gateway for data sync.

Of course, we recognize that there are instances where deriving the channel or access grant information based on contents of the document body is the best option.
So that option will continue to be supported.
// end::new-300-xattrs-extended[]
// tag::new-300-xattrs[]

More::
  {access-control-how-use-xattrs-for-access-grants--xref}


// end::new-300-xattrs[]
// end::new-300-xattrs-full[]




// tag::new-300-auto-purge-full[]
// tag::new-300-auto-purge[]
// tag::new-300-auto-purge-extended[]
_This enhancement to inter-Sync Gateway replication technology helps with the enforcement of data privacy and governance in complex workflows._

{sgw-s} nodes can replicate data with each other using
{sgw--xref}{sync-inter-syncgateway-overview--page}[inter-Sync Gateway replication] technology.

When a user loses access to a channel (and therefore the documents in it) you can opt to enable the initiating {sgw} cluster to auto-purge those documents in the revoked channel.

// end::new-300-auto-purge[]
// tag::new-300-auto-purge-extended[]

// end::new-300-auto-purge-extended[]
// tag::new-300-auto-purge[]
More::
  {auto-purge-channel-access-revocation--xref}

// end::new-300-auto-purge[]
// end::new-300-auto-purge-full[]

// end::feature1-300[]

// tag::feature1-300[]

// end::feature1-300[]


// end::features-300[]
// end::new-300-all[]
// end::feature-highlights-300[]

[#improvements-300]
=== Other Enhancements
// tag::enhancements-300[]

==== Configuration Changes

// tag::enhancement-highlights-300[]

===== Centralization
// tag::centralization-300[]

// end::centralization-300[]

===== Environment Variables
// tag::env-vars-300[]
// tag::new-300-environment-vars[]
Sync Gateway configuration is extended to allow the use of defined _environment variables_ as substitution values inside the configuration file.
This allows users to determine, pick-up and substitute appropriate values during Sync Gateway start-up.

More::
  {configuration-environment-variables--xref}
// end::new-300-environment-vars[]
// end::env-vars-300[]

==== External Javascript Functions in Config File
// tag::new-300-external-javascript[]
Introduce and describe the key changes and benefits
// end::new-300-external-javascript[]


===== External Javascript
// tag::extjs-300[]

// end::extjs-300[]

// end::enhancement-highlights-300[]

==== Other Enhancements

[,cols="^2,8"]
|===
h|Issue|Summary

|===

// end::enhancements-300[]


[#issues-and-resolutions-300]
=== Issues and Resolutions

==== Known Issues

// tag::known-300[]
// .List of issues outstanding at this release
{empty}

[#tbl-known,cols="^2,8"]
|===
h|Issue Ref.
h|Summary

|===

// end::known-300[]

==== Fixed Issues

{empty}
// tag::fixed-300[]
// .List of issues resolved by this release
[#tbl-fixed,cols="^2,8"]

|===
h|Issue Ref.
h|Summary


|===
// end::fixed-300[]

// tag::api-changed-300[]
// tbd
// end::api-changed-300[]

// tag::cfg-changed-300[]
// tbd
// end::cfg-changed-300[]

// tag::enhancements-300[]

// end::enhancements-300[]

==== API Changes
// – identify any REST API changes
// tag::api-changes-300[]
// tag::all-changed-300-api[]
This release introduces new persistent API changes.


See: {rest-api-admin--xref}

// end::all-changed-300-api[]

// end::api-changes-300[]

[#support-notices-300]
=== Support Notices
This section documents any support-related notes, constraints and changes

==== Deprecation Notices
Items (features and-or functionality) are marked as deprecated when a more current, and usually enhanced, alternative is available.

Whilst the deprecated item will remain usable, it is no longer supported, and will be removed in a future release.
You should plan to move to an alternative, supported, solution as soon as practical.

// tag::deprecated-300[]
// tag::dnsgw-30[] all deprecations for the release
// tag::dnsgw-30-001-note[]
// tag::dnsgw-30-001-notetitle[]
=====  note title
// tag::dnsgw-30-001-noteannounce[]

// end::dnsgw-30-001-noteannounce[]

// tag::dnsgw-30-001-noteimpact[]
The functionality of SG{nbsp}Replicate remains unchanged, unless explicitly stated in these release notes and-or in the appropriate documentation section.
Refer to {xref-sgw-pg-upgrade} for more information on upgrading from SG Replicate to Inter-Sync Gateway replication.
// end::dnsgw-30-001-noteimpact[]
// end::dnsgw-30-001-note[]

===== Configuration deprecations
// tag::dnsgw-30-001-cfg[]

// tag::dnsgw-30-001-cfg1[]
// end::dnsgw-30-001-cfg1[]

// end::dnsgw-30-001-cfg[]

===== REST API Deprecations
// tag::dnsgw-30-001-api[]

// tag::dnsgw-30-001-api1[]
// end::dnsgw-30-001-api1[]

// end::dnsgw-30-001-api[]

===== Operating Systems
Support for Microsoft Windows 2012 (64-bit) is deprecated

// end::dnsgw-30[]
// end::deprecated-300[]
// ===== Ongoing
// include::{root-partials}block-deprecations.adoc[tag=any-platform-ongoing]
// include::{root-partials}block-deprecations.adoc[tag={param-platform}-ongoing]

// === End of Life
// include::{root-partials}block-deprecations.adoc[tag=any-platform-eol]
// include::{root-partials}block-deprecations.adoc[tag={param-platform}-eol]

// === End of Support
// {ns-this}

==== Other Notices

===== Support is added for:


=== Upgrading

// tag::upgrading[]

// end::upgrading[]

For more on upgrading -- see: {xref-sgw-pg-upgrade}

// END -- INCLUSION --