// include::partial$icr-repl-props-table-sgr2[]

[[replication-properties]]
.Replication Definition
=====

[{tabs}]
====

Summary of Parameters::
+
--
This table summarize all the available configurable items. It includes a link to a detailed description of each.

[#replication-definiton-summary,cols="3,7"]
!===
|Name and Link |Summary

a| xref:{configuration-schema-isgr--page}#replication-adhoc
a| REST API ONLY +
include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-adhoc-def]

a| xref:{configuration-schema-isgr--page}#replication-batch_size[batch_size]
a| include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-batch-size-def]

a| xref:{configuration-schema-isgr--page}#replication-cancel[cancel]
a| REST API ONLY +
include::partial$block_related_content_menulists.adoc[tags=glos-cfg-rep-cancel-def]

a| xref:{configuration-schema-isgr--page}#replication-conflict_resolution_type[conflict_resolution_type]
a| include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-conflict-def]

a| xref:{configuration-schema-isgr--page}#replication-continuous[continuous]
a| include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-continuous-def]

a| xref:{configuration-schema-isgr--page}#replication-custom_conflict_resolver[custom_conflict_resolver]
a| include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-resolver-def]

a| xref:{configuration-schema-isgr--page}#replication-direction[direction]
a| include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-direction-def]

a| xref:{configuration-schema-isgr--page}#replication-enable_delta_sync[delta_sync]
a| include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-delta-def]

a| xref:{configuration-schema-isgr--page}#replication-filter[filter]
a| include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-filter-def]

a| xref:{configuration-schema-isgr--page}#replication-max_backoff_time[max_backoff_time]
a| include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-backoff-def]

a| xref:{configuration-schema-isgr--page}#replication-purge_on_removal[purge_on_removal]
a| include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-purge-def]

a| xref:{configuration-schema-isgr--page}#replication-query_params[query_params]
a| include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-query-def]

a| xref:{configuration-schema-isgr--page}#replication-remote[remote]
a| include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-remote-def]

a| xref:{configuration-schema-isgr--page}#replication-replication_id[replication_id]
a| include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-rep-id-def]

a| xref:{configuration-schema-isgr--page}#replication-initial_state[initial_state]
a| include::partial$block_glossary_terms.adoc[tags=glos-cfg-rep-initial_state-def]

!===
--

Configured Example::
+
--
This is an example of a replication definition. Its purpose is to illustrate all configurable items in use and so should not be considered a working example.

It creates a replication with the replication_ID of `db1-rep-id1-pull-oneshot` on a local database `db1-local_`, pulling data from a remote database `db1-remote`.

[source, json]
----
include::{example-cfg}[tag=icr-rep-sample-create-pull, indent=0]
----

include::{example-cfg}[tag=icr-rep-sample-create-pull-callouts-full, indent=0]

--

REST API Example::
+
--
This is an example of a replication definition as you might submit it to the Admin REST API.using `curl`.
Its purpose is to illustrate all configurable items in use and so should not be considered a working example.

It creates a replication with the replication_ID of `db1-rep-id1-pull-oneshot` on a local database `db1-local_`, pulling data from a remote database `db1-remote`.
[source, json]
----
include::{example-restapi}[tag=icr-rep-sample-create-pull, indent=0]
----

include::{example-restapi}[tag=icr-rep-sample-create-pull-callouts, indent=0]
--

====
=====
