// include::partial$icr-repl-props-table-sgr2[]

[[replication-properties]]
.Replication Definition
=====

[{tabs}]
====

Summary of Parameters::
+
--
This table summarize all the available configurable items. It includes a link to a detailed description of each.

[#replication-definiton-summary,cols="3,7"]
!===
|Name and Link |Summary

a| {legacy-configuration-properties--xref--db-rep-adhoc}
a| REST API ONLY +
include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-adhoc-def]

a| {legacy-configuration-properties--xref--db-rep-batch}
a| include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-batch-size-def]

a| {legacy-configuration-properties--xref--db-rep-cancel}
a| REST API ONLY +
include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-cancel-def]

a| {legacy-configuration-properties--xref--db-rep-conflict}
a| include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-conflict-def]

a| {legacy-configuration-properties--xref--db-rep-continuous}
a| include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-continuous-def]

a| {legacy-configuration-properties--xref--db-rep-resolver}
a| include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-resolver-def]

a| {legacy-configuration-properties--xref--db-rep-direction}
a| include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-direction-def]

a| {legacy-configuration-properties--xref--db-rep-delta}
a| include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-delta-def]

a| {legacy-configuration-properties--xref--db-rep-filter}
a| include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-filter-def]

a| {legacy-configuration-properties--xref--db-rep-backoff}
a| include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-backoff-def]

a| {legacy-configuration-properties--xref--db-rep-purge}
a| include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-purge-def]

a| {legacy-configuration-properties--xref--db-rep-query}
a| include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-query-def]

a| {legacy-configuration-properties--xref--db-rep-remote}
a| include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-remote-def]

a| {legacy-configuration-properties--xref--db-rep-id}
a| include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-rep-id-def]

a| {legacy-configuration-properties--xref--db-rep-initial_state}
a| include::partial$_glossary-terms.adoc[tags=glos-cfg-rep-initial_state-def]

!===
--

Configured Example::
+
--
This is an example of a replication definition. Its purpose is to illustrate all configurable items in use and so should not be considered a working example.

It creates a replication with the replication_ID of `db1-rep-id1-pull-oneshot` on a local database `db1-local_`, pulling data from a remote database `db1-remote`.

[source, json]
----
include::{example-cfg}[tag=icr-rep-sample-create-pull, indent=0]
----

include::{example-cfg}[tag=icr-rep-sample-create-pull-callouts-full, indent=0]

--

REST API Example::
+
--
This is an example of a replication definition as you might submit it to the Admin REST API.using `curl`.
Its purpose is to illustrate all configurable items in use and so should not be considered a working example.

It creates a replication with the replication_ID of `db1-rep-id1-pull-oneshot` on a local database `db1-local_`, pulling data from a remote database `db1-remote`.
[source, json]
----
include::{example-restapi}[tag=icr-rep-sample-create-pull, indent=0]
----

include::{example-restapi}[tag=icr-rep-sample-create-pull-callouts, indent=0]
--

====
=====
