// = Replication Monitoring and Statistics
include::partial$_stats-item-names.adoc[]
// tag::in-this-section[]
ifndef::is_deep_toc[*_In this Section_*: <<retrieving-replication-status-data>>  |  <<retrieving-sync-gateway-statistics>>]
// end::in-this-section[]

// tag::overview[]
== Overview

// tag::overview-status[]
=== Status Information
Sync Gateway provides a replication status Admin REST API endpoint to enable effective monitoring of replications.

Use the {xref-sgw-ep-admin-api-replication-repstatus} endpoint to check the status of individual replications and-or the {xref-sgw-ep-admin-api-replication-repstatus-query} endpoint to get status information on all replications, filtered by the querystring criteria.

// end::overview-status[]
// tag::overview-stats[]

=== Sync Gateway Statistics
Sync Gateway maintains a comprehensive set of statistics, including a replication-specific subset.

You can access these statistics using the `_expvars`  endpoint.

// end::overview-stats[]
// end::overview[]

== Retrieving Replication Status Data
// <<retrieving-status-data-for-a-specific-replication>>  | <<retrieving-status-data-for-all-replications>>

include::partial$icr-replicationStatus-GET.adoc[tags=overview]


=== Retrieving Status Data for a Specific Replication

include::partial$icr-replicationStatus-GET.adoc[tags=rep-status-specific]

=== Retrieving Status Data for All Replications

include::partial$icr-replicationStatus-GET.adoc[tags=rep-status-all]


== Retrieving Sync Gateway Statistics

Sync Gateway maintains a comprehensive set of metrics covering performance and resource utilization.

The statistics schema includes replication metrics collected on a per-replication basis.
These can be especially useful in monitoring the health of Sync Gateway nodes. An increasingly important activity as deployments scale to support cloud-to-edge use cases.

Access to this data is provided through the Admin REST API endpoint `/_expvars`.

See: {xref-sgw-pg-stats-monitoring} for a full description of the available metrics.
