// = Conflict Resolution in Inter-Sync Gateway Replication
:fn-no-op-text: footnote:fn-1[No-op update -- refers to a change to the document body that has no impact on the app logic but will trigger an import by the Sync Gateway. One option could be to include a property used specifically for this purpose (i.e. a counter that can be incremented in response to conflict resolver errors).]
:fnref-no-op: footnote:fn-1[]
// tag::in-this-section[]
*_In this Section_*: <<automatic-conflict-resolution>>  |  <<how-resolution-works>>  |  <<configuring-conflict-resolution>>  |  <<build-a-conflict-resolution-policy-ee>>
// end::in-this-section[]

== Automatic Conflict Resolution
// tag::overview[]
Inter-Sync Gateway Replication supports automatic conflict resolution to resolve conflicting document changes.

It delivers this by applying one of its built-in {glos-term-conflict-resolver-policies}, which can be easily included in your own replications -- see <<configuring-a-policy-to-use>>

include::{concepts}rep-auto-conflict-resolution.adoc[]

:param-body: A <<custom-conflict-resolution-ee, Custom Conflict Resolver>> policy is available, providing additional flexibility by allowing users to provide their own confict resolution logic.
include::partial$block-caveats.adoc[tags=ee-only]

// end::overview[]

// See: <<resolver-policies, conflict resolver policies>>

Conflict Response on Active Replicator::
As soon as the _active_ Sync Gateway database detects a conflict in a replicated document revision, it initiates its configured _conflict resolver policy_ to determine a _winning_ revision.
This policy assesses the conflicting revisions and either determines the winning revision or returns an error if it fails while doing so.

Conflict Response by Passive Replicator::
When a passive Sync Gateway database detects a conflict it responds to the active with a `409` response and rejects the revision.
It is expected that the active Sync Gateway will pull the conflicting revision from the passive, resolve it on the active, and then subsequently push the resolved conflict back up.
// === Automatic Resolution Policy

// * Deletes always win.


//  even when the no-conflicts mode is enabled (that is where {xref-sgw-pfx-config-properties}#databases-this_db-allow_conflicts["allow_conflicts": false]).

// When running two Sync Gateway clusters with the no-conflicts mode enabled, cross-cluster document conflicts will result in that document no longer being replicated. To avoid this, the application must ensure that concurrent cross-cluster updates are not made to a given document.

// Deployments  must implement a custom conflict resolver in an external app as specified in {xref-sgw-pg-resolving-conflicts}.

// == Conflict Resolver Policies

// Conflict resolution is configurable, in that you can choose to apply one of the out-of-the-box (predefined) conflict resolver policies.

// [#predefined-resolver-policies]
// .Predefined resolver policies
// The following automatic conflict resolution policies are available when configuring a replication:

// Default::
// Applies the default policy described in <<automatic-conflict-resolution>>

// Local Wins::
// * Always considers the local change the winner.
// * Configured using: `"conflict_resolution_type": "localWins"`

// Remote Wins::
// Always considers the remote change the winner.
// * Configured using: `"conflict_resolution_type": "remoteWins"`

== How Resolution Works

Pull Replications::
+
--
For _Pull_ replications the _active_ Sync Gateway is responsible for detecting and resolving conflicts based on the configured _conflict_resolution_type_ (see configuration item: {xref-sgw-pg-config-properties-db-rep-conflict}.

This is also how conflicts are handled when Couchbase Lite clients pull down documents to Sync Gateway.

*Note:* Resolved conflicts are only transferred from active to passive Sync Gateways if a replication is setup between them.
--

Push Replications::
+
--
Passive Sync Gateway::
The _passive_ Sync Gateway will automatically detect and reject conflicting revisions being _pushed_ to it.
+
Note that conflicts are not resolved.
The revision is rejected and the document returned -- with a `409 Conflict` -- response to the active Sync Gateway.

Active Sync Gateway::
It is  the responsibility of the active sync Gateway to address rejected revisions in accordance with its specified _conflict_resolution_type_.
--
+
This approach is the same as that adopted when Couchbase Lite clients push documents to Sync Gateway.

== Configure Conflict Resolution
Invoke automatic conflict resolution by specifying the required _conflict resolver policy_ in the {glos-term-replication-definition}.
The specified policy is applied whenever a conflict is detected.

.Using automatic conflict resolution
=====
[{tabs}]
====

default::
+
--
[source, json]
----
"databases:"
  // other config as necessary
  "this_db:"
    // other config as necessary
    "sgreplicate_enabled": "true",
    "replications": [
        {
          "replication_id": "replication1",
          "direction": "push_and_pull",
          "continuous": true,
          "filter": "sync_gateway/bychannel",
          "query_params": [
              "channel1",
              "channel2"
          ],
          "conflict_resolution_type": "default",
          // other config as necessary
        }
    ]
// other config as necessary
----
--

localWins::
+
--
[source, json]
----
"databases:"
  // other config as necessary
  "this_db:"
    // other config as necessary
    "sgreplicate_enabled": "true",
    "replications": [
        {
          "replication_id": "replication1",
          "direction": "push_and_pull",
          "continuous": true,
          "filter": "sync_gateway/bychannel",
          "query_params": [
              "channel1",
              "channel2"
          ],
          "conflict_resolution_type": "localWins",
          // other config as necessary
        }
    ]
// other config as necessary
----
--

remoteWins::
+
--
[source, json]
----
"databases:"
  // other config as necessary
  "this_db:"
    // other config as necessary
    "sgreplicate_enabled": "true",
    "replications": [
        {
          "replication_id": "replication1",
          "direction": "push_and_pull",
          "continuous": true,
          "filter": "sync_gateway/bychannel",
          "query_params": [
              "channel1",
              "channel2"
          ],
          "conflict_resolution_type": "remoteWins",
          // other config as necessary
        }
    ]
// other config as necessary
----

--


====
=====
// Inter-Sync Gateway Replication supports automatic conflict resolution to resolve conflicting document revisions.

// The automatic conflict resolution policy is the same as that adopted in Couchbase Lite 2.x between Couchbase Lite and Sync Gateway.
// The basic rules being:

// include::couchbase-lite:ROOT:partial$handling-conflicts.adoc[tags=auto-conflict-resolution]

== Build a Conflict Resolution Policy [EE]
// _In this section_: <<conflict-resolution-approaches>>  |  <<approaches-to-error-handling>>  |  <<conflict-resolver-structure>>

include::partial$incpg-icr-conflict-build-custom.adoc[]

