// = Conflict Resolution in Inter-Sync Gateway Replication
:fn-no-op-text: footnote:fn-1[No-op update -- refers to a change to the document body that has no impact on the app logic but will trigger an import by the Sync Gateway. One option could be to include a property used specifically for this purpose (i.e. a counter that can be incremented in response to conflict resolver errors).]
:fnref-no-op: footnote:fn-1[]


// *_In this Section_*: <<automatic-conflict-resolution>>  |  <<how-resolution-works>>  |  <<configure-conflict-resolution>>  |  <<custom-conflict-resolution-ee>>

== Automatic Conflict Resolution

// tag::overview-full[]
// tag::overview[]

Inter-Sync Gateway replication supports automatic conflict resolution to resolve conflicting document changes.
It delivers this by applying one of its built-in {glos-term-conflict-resolver-policies}, which can be easily included in your own replications.

include::{concepts}rep-auto-conflict-resolution.adoc[]

// end::overview[]

For {enterprise}, a custom conflict resolver policy is available, providing additional flexibility by allowing users to provide their own conflict resolution logic -- see: {xref-sgw-pg-icr-conflict-resolution-custom}.

== How Resolution Works

Conflict Response on Active Replicator::
As soon as the _active_ Sync Gateway database detects a conflict in a replicated document revision, it initiates its configured _conflict resolver policy_ to determine a _winning_ revision.
This policy assesses the conflicting revisions and either determines the winning revision or returns an error if it fails while doing so.

Conflict Response by Passive Replicator::
When a passive Sync Gateway database detects a conflict it responds to the active with a `409` response and rejects the revision.
It is expected that the active Sync Gateway will pull the conflicting revision from the passive, resolve it on the active, and then subsequently push the resolved conflict back up.

Pull Replications::
+
--
For _Pull_ replications the _active_ Sync Gateway is responsible for detecting and resolving conflicts based on the configured _conflict_resolution_type_  -- see configuration item: {legacy-configuration-properties--xref--db-rep-conflict}.

This is also how conflicts are handled when Couchbase Lite clients pull down documents to Sync Gateway.

*Note:* Resolved conflicts are only transferred from active to passive Sync Gateways if a replication is setup between them.
--

Push Replications::
+
--
Passive Sync Gateway::
The _passive_ Sync Gateway will automatically detect and reject conflicting revisions being _pushed_ to it.
+
Note that conflicts are not resolved.
The revision is rejected and the document returned -- with a `409 Conflict` -- response to the active Sync Gateway.

Active Sync Gateway::
It is  the responsibility of the active sync Gateway to address rejected revisions in accordance with its specified _conflict_resolution_type_.
--
+
This approach is the same as that adopted when Couchbase Lite clients push documents to Sync Gateway.

// end::overview-full[]

[#configure-conflict-resolution]
== Configure Conflict Resolution
Invoke automatic conflict resolution by specifying the required _conflict resolver policy_ in the {glos-term-replication-definition}.
The specified policy is applied whenever a conflict is detected.

.Using automatic conflict resolution
=====
[{tabs}]
====

default::
+
--
[source, json]
----
"databases:"
  // other config as necessary
  "this_db:"
    // other config as necessary
    "sgreplicate_enabled": "true",
    "replications": [
        {
          "replication_id": "replication1",
          "direction": "push_and_pull",
          "continuous": true,
          "filter": "sync_gateway/bychannel",
          "query_params": [
              "channel1",
              "channel2"
          ],
          "conflict_resolution_type": "default",
          // other config as necessary
        }
    ]
// other config as necessary
----
--

localWins::
+
--
[source, json]
----
"databases:"
  // other config as necessary
  "this_db:"
    // other config as necessary
    "sgreplicate_enabled": "true",
    "replications": [
        {
          "replication_id": "replication1",
          "direction": "push_and_pull",
          "continuous": true,
          "filter": "sync_gateway/bychannel",
          "query_params": [
              "channel1",
              "channel2"
          ],
          "conflict_resolution_type": "localWins",
          // other config as necessary
        }
    ]
// other config as necessary
----
--

remoteWins::
+
--
[source, json]
----
"databases:"
  // other config as necessary
  "this_db:"
    // other config as necessary
    "sgreplicate_enabled": "true",
    "replications": [
        {
          "replication_id": "replication1",
          "direction": "push_and_pull",
          "continuous": true,
          "filter": "sync_gateway/bychannel",
          "query_params": [
              "channel1",
              "channel2"
          ],
          "conflict_resolution_type": "remoteWins",
          // other config as necessary
        }
    ]
// other config as necessary
----

--

====
=====

[#custom-conflict-resolution-ee]
== Build a Conflict Resolution Policy [EE]
// _In this section_: <<conflict-resolution-approaches>>  |  <<approaches-to-error-handling>>  |  <<conflict-resolver-structure>>

// Build a Conflict Resolution Strategy
// tag::in-this-section[]
_In this section_: <<conflict-resolution-approaches>>  |  <<approaches-to-error-handling>>  |  <<conflict-resolver-structure>>  |  <<sample-conflict-resolvers, Example Conflict Resolvers>>

include::partial$block-caveats.adoc[tags=ee-only-feature]

// end::in-this-section[]

Custom conflict resolution is handled by the _active_ Sync Gateway using a user-provided {glos-term-custom-conflict-resolver}. This Javascript function is embedded in the replication configuration.

The predefined conflict resolver policies are also available as Javascript functions that you can call from within that _custom_conflict_resolver_ function
This is useful when you want to apply greater selectivity to the automatic conflict resolution process. For example, you want to apply a 'remote wins' policy only for a specific type of document - see the 'Use Policies' tab in <<simple-conflict-resolvers>>.

=== Conflict Resolution Approaches

There are two ways to handle conflicts in your custom_conflict_resolver, you can either:

* Choose a _winning_ revision from among the conflicting revisions (see <<simple-conflict-resolvers>>), or
* Merge conflicting revision to create a new _winning_ revision; losing revisions are tomb-stoned.
+
NOTE: When creating a new revision, do not provide a `_rev` property.
A new revision ID will be generated.
Use `delete mergedDoc._rev` to invalidate the property.
+
However, users should avoid overly-complex resolver logic that may impact performance.

=== Approaches to Error Handling

// tag::overview-error-handling[]
Your custom conflict resolver function should not terminate the replication when it encounters exceptions or errors.
Instead, you should log sufficient information to aid troubleshooting and recovery.

For example, your custom conflict resolver function should:

* Skip the document causing the issue
* Log a suitable warning level message.
Include at least the skipped document's Id and the sequence Id of the revision in error.
// end::overview-error-handling[]

Refer to log files when troubleshooting conflict resolution errors, to identify the document id and revision sequence in error.

.Some Error Scenarios and Recommended Resolutions
====
Unexpected data in the remote document::
You should update the remote document to fix the issue.
Doing so will cause replication of the update.

Unexpected data in the local document::
You should update the local document to fix the issue.
This will not trigger a pull-replication.
Do a no-op-update {fn-no-op-text} of the remote document, which will trigger replication and conflict resolution.

Fault in conflict resolution javascript function::
+
--
Fix the Javascript logic and then either:

* Do a _no op update_ {fnref-no-op} of the remote document.
This triggers a pull replication and subsequent conflict resolution.

* Reset the replication (using `_replicationstatus/reset` endpoint). Not recommended as it introduces significant duplicate processing in resyncing previously synced documents.

--
====

=== Conflict Resolver Structure

include::partial$common-cfg-ext-javascript.adoc[tag=intro]

You can provide your conflict resolver as either an inline or external Javascript function.
You can learn more about the ($db.custom_conflict_resolver) property in the Configuration Schema Reference -- see: {legacy-configuration-properties--xref--db-rep-resolver}.

include::partial$common-cfg-ext-javascript.adoc[tag=config-full]

The following example shows the basic structure of the conflict resolver function as it would be defined in the configuration file.

.Conflict resolver structure
====
[source, javascript]
----
include::{example-cfg}[tags=icr-conflict-resolver-structure, indent=0]
----

include::{example-cfg}[tags=icr-conflict-resolver-structure-callouts, indent=0]
====

=== Sample Conflict Resolvers

[#simple-conflict-resolvers]
.Simple conflict resolvers
=====
[{tabs}]
====
[#use-policies]
Use Built-in Policies::
+
--
This example uses the built-in resolver functions to resolve the conflict based-on the document type.

So, documents of type `a-doc-type-1` are always resolved in favor of the remote revision. All other document types are resolved in accordance with the default resolver policy.

[source,json]
----
include::{example-cfg}[tags=icr-simple-conflict-resolver, indent=0]
----
--

Nominate a Winner::
+
--
This example selects a winner based on relative priorities and builds a return response of its own rather than using either the localWins or remoteWins policy, although it does rely on the default resolver policy as a backstop.

[source,json]
----
include::{example-cfg}[tags=icr-simple-own-winner-conflict-resolver, indent=0]
----
--
Merge a Winner::
+
--
This example creates a winner by merging changes from the local and remote documents to create a new document object, which is returned as the winner.

If both document.types are non-null and the local document.type is `usedefault`, the merge path is overridden and the default resolver policy is applied.

//   - If an nil Body is returned, the conflict should be resolved as a deletion/tombstone.

[source,json]
----
include::{example-cfg}[tags=icr-simple-merge-conflict-resolver, indent=0]
----
<.> Invalidate the `_rev` property.
A new revision ID will be generated.
<.> Transcribe properties from source to target.
+

NOTE: The `IF` block is temporary. It circumvents the known_issue https://issues.couchbase.com/browse/CBG-1335[CBG-1335], which results in a revision ID mismatch.
--
====
=====
