// BEGIN -- inclusion -- prometheus-activation.adoc
//
The Metrics REST API is enabled by default on port 4986.
To change this you need to edit the `api.metricsInterface` setting in your {sgw--xref}{configuration-schema-bootstrap--page}[bootstrap configuration file] and define the Sync Gateway URL and the port you want the API served on (for example: 4986) -- see: <<ex-activate>>.

Alternatively::
  If you are using 2.x file-based configuration then edit the `metricsInterface` setting in the `sync-gateway-config.json` configuration file -- see: {configuration-properties-legacy--xref}

[#ex-activate]
.Setting metrics interface endpoint
====
[{tabs}]
=====
Persistent Configuration::
+
--
Within the bootstrap configuration file:

[source,json]
----
"api.metricsInterface": "127.0.0.1:4986" // <.>
----
--

2.x File-based Configuration::
+
--
Within the sync gateway configuration file:

[source,json]
----
"metricsInterface": "127.0.0.1:4986" // <.>
----
--

=====
<.> Here we define the Sync Gateway URL and the port (4986 in this instance) that we require the Metrics REST API to be served on.

====

// END -- inclusion -- prometheus-activation.adoc