= Inter-Sync Gateway Replication
// :page-aliases: icr-architecture.adoc
:page-layout: article
:page-status:
:page-edition:
:page-role:
:description: inter-Sync Gateway replication concepts and operations provide for effective cloud-to-edge data synchronization.
// :sectanchors:

include::partial$_std-hdr-sgw.adoc[]
// include::partial$block-authors-notes.adoc[tag=wip]

:topic-group: {tg-rep-icr}
:param-related: {legacy-configuration-properties--xref} | {rest-api-admin--xref}
:param-abstract: This content introduces Inter-Sync Gateway Replication's concepts and how you can use them to configure and run effective data-sync between clusters of edge devices and central data centre resources.
include::partial$block-abstract.adoc[]

// Footnotes
:fn-icr: footnote:icr[As of Sync Gateway version 2.8]
:fn-sgr1: footnote:sgr1[SG{nbsp}Replicate only]
:fn-sgr2: footnote:sgr2[Inter-Sync Gateway Replication only]
:fn-arch: footnote:arch[This architecture is also known as _ship-to-shore_ or _hub-and-spoke_.]
:fnref-icr: footnote:icr[]
:fnref-arch: footnote:arch[]
:fnref-sgr1: footnote:sgr1[]
:fnref-sgr2: footnote:sgr2[]

// ONLY FORInter-Sync Gateway replication - Includes redirect for SGR1 consumers
include::partial$block-caveats.adoc[indent=0,tags=sgr2-only]
include::partial$block-caveats.adoc[indent=0,tags=icr-sgr1-redirect]

== Cloud-to-Edge Synchronization

// tag::intro-full[]
// tag::intro[]

Couchbase Sync Gateway's _{glos-term-inter-sync-gateway-replication}_ {fn-icr} supports _{glos-term-cloud-to-edge} synchronization_ use cases, which demand changes be synchronized between a centralized cloud cluster and large numbers of edge clusters, whilst still enforcing fine grained access control.

// end::intro[]


// tag::use-cases[]
.Use Cases
=====
[{tabs}]
====

Cloud-to-edge synchronization::
+
--
In this multi-cloud deployment mode large numbers of multiple edge clusters sync with one or more clusters in cloud data centers. Each edge can operate autonomously without network connectivity to the cloud data centers {fn-arch}.

// inter-Sync Gateway replication delivers bi-directional sync, which:

// - is scalable
// - has high availability
// - features automatic and customizable conflict resolution options
// - has end-to-end security with fine grained access control.

// All very important considerations in this use case.

A typical architecture for this use cases is shown in <<icr-cloud-to-edge>>

[[icr-cloud-to-edge]]
.Cloud-to-edge synchronization
image::icr-cloud-to-edge200712.svg[,600]
--

Active-to-active Mobile Synchronization::
+
--
Here active mobile clusters at the edge are replicated between geographically separate cloud-based Sync Gateway deployments.

A typical architecture for this use cases is shown in <<icr-active-mobile>>

[[icr-active-mobile]]
.Active-active mobile synchronization
image::icr-active-mobile-sync200713.svg[,600]

--
====
// end::use-cases[]
=====

== Replication Approach
// tag::intro-img[]
=== Context
Inter-Sync Gateway Replication provides the functionality to act as the {glos-term-active-replicator} supporting the {glos-term-synchronization} of changes between two {glos-term-sync-gateway-databases}.

// === Architecture
In the architecture diagram (<<icr-architecture>>), the _active replicator_  runs on a Sync Gateway node (in cluster A) and uses a bi-directional sync -- with a {glos-term-active-replicator} running on a node in Cluster B -- to ensure that changes made to either database instance are replicated to the other, in accordance with its {glos-term-replication-definition} -- see {legacy-configuration-properties--xref--db-replications} for configuration details.

[[icr-architecture]]
.Inter-Sync Gateway Replication
image::Inter-Sync Gateway-replication-2.svg[Cloud-to-edge replication architecture,{img-max}]

// end::intro-img[]
// end::intro-full[]
== Replication Characteristics
_In this section_:  <<general-characteristics>> |<<protocol>>  |  <<types-of-replication>>  |  <<delta-sync>>  |  <<directionality>>  |  <<security>>

=== General Characteristics

Inter-Sync Gateway Replication acts as the {glos-term-active-replicator} {glos-term-synchronizing} changes between two {glos-term-sync-gateway-databases}.

All replications are based on a {glos-term-replication-definition} provided either to the Admin REST API or in Sync Gateway's configuration file (JSON).
//  -- see: <<replication-definitions>>.

All replications have a unique identifier (`replication_id`) assigned in their replication definition.
Sync Gateway generates a random UUID if no `replication_id` is defined.

All replications take place at the document level.

Replications always involve at least one local database.
Replication between two _remote_ nodes is not possible, since replications are defined at database level and so at least one database will be local.

Sync Gateway nodes can opt-out of participating in the replication process using the database-level parameter {legacy-configuration-properties--xref--databases-sgr-enabled}.

_Related configuration elements_:  {legacy-configuration-properties--xref--databases}  |  {legacy-configuration-properties--xref--db-replications}  |  {legacy-configuration-properties--xref--db-rep-remote} |  {legacy-configuration-properties--xref--databases-sgr-enabled}

=== Protocol
// tag::isgwr-concept-protocol[]
Inter-Sync Gateway Replication uses a proprietary Couchbase protocol, which delivers secure, network resilient replication using basic authentication over a Websocket connection{fn-sgr2}).

The bi-directional, persistent, nature of websocket connections is ideal for applications such as a _continuous_ Sync Gateway replication, which is constantly waiting-for and synchronizing change events.
// end::isgwr-concept-protocol[]

Unlike xref:server:manage:manage-xdcr/xdcr-management-overview.adoc[XDCR] (the API for replication between Server clusters), _Inter-Sync Gateway Replication_ is designed specifically for _{cbm}_ deployments.
It *must* be used for replication between mobile clusters.

=== Types of Replication
// tag::replication-types[]

Replications are either: {glos-term-persistent-replication} or {glos-term-adhoc-replication} (REST API only).
They can also be configured to run in one of two-modes:
{glos-term-continuous} or {glos-term-oneshot}.


* Persistent
+
--
Persistent replications survive Sync Gateway node restarts and continue running automatically unless configured not to.
They can be defined either in the configuration file or by the REST API and can be configured to run in either {glos-term-continuous} or {glos-term-oneshot} mode.
--

* Ad hoc
+
--
Ad hoc replications are transient. You must define these using the REST API.
They run in one-shot mode, exist only for the period of the replication and are removed when the replication is complete.
They provide a convenient way to:

* Run one off replications (for example, when troubleshooting)
* Run on-demand replications after Sync Gateway is started.
For instance a replication that needs to be to be run only periodically can be configured as an ad hoc replication by an automated script scheduled to run when needed.
//  They are initialized and run using {rest-api-admin--xref} requests.
// Once created they start in the 'running' state. When they enter 'stopped', or 'error', state they are automatically removed.
--

_Related configuration elements_:  {legacy-configuration-properties--xref--db-replications}  |  {legacy-configuration-properties--xref--db-rep-continuous} |  {legacy-configuration-properties--xref--db-rep-adhoc}
// They are initialized by configuring them in the _sync-gateway-config.json file_.

//  Inter-Sync Gateway Only You can also create persistent replications by using the {rest-api-admin--xref}.

// end::replication-types[]

=== Directionality

Replications are bi-directional.

The _active replicator_ can push, pull or pushandpull between the two database endpoints.

_Related configuration elements_:  {legacy-configuration-properties--xref--db-replications}  |  {legacy-configuration-properties--xref--db-rep-direction}


=== Security
// tag::security[]

Transport level security is provided by WSS.



==== Authentication
// tag::authentication[]

Support for Basic Authentication using username and password credentials is provided
// (optional TLS Certificate authentications is also available {fnref-sgr2}).
.

// end::authentication[]

==== Access Control.
// tag::access-control[]

Data access control is provided by Sync Gateway's {glos-term-sync-function} and the username/password credentials.
All replicated documents pass through this function ensuring that access permissions are consistently applied and adhered to.

_Related configuration elements_:  {legacy-configuration-properties--xref--databases}  |  {legacy-configuration-properties--xref--databases-sync} +
_Related how-to_: {xref-sgw-pg-sync-function}  |  {xref-sgw-pg-adv-sgw-cfg-sync-function}
// end::access-control[]

// end::security[]

== Delta Sync

NOTE: Delta-sync is available only with the {enterprise}.

With delta-sync enabled on the replication and on both databases involved, only the changed data items are transferred.

You can configure replications to use delta-sync by:

* Setting `"enable_delta_sync": true` in the _replication definition_
* Setting `"delta-sync": { "enabled": true}` on both databases in their respective _database definitions_.

_Related configuration elements_:  {legacy-configuration-properties--xref--databases}  |  {legacy-configuration-properties--xref--db-replications}  |
{legacy-configuration-properties--xref--databases-delta-sync}  |  {legacy-configuration-properties--xref--db-rep-delta}

== Network Resilience

Persistent inter-Sync Gateway replications will automatically attempt to restart whenever the node does.

Network resiliency is built-in for _continuous_ replications.
They respond to network issues such as lost connections, by applying a {glos-term-persistent-exponential-backoff} policy to attempt reconnection.

The {legacy-configuration-properties--xref--db-rep-backoff} determines the maximum wait time between retries.
When the limit is reached retries are made every `max_backoff_time` minutes.
Set `"max_backoff_time": 0` to prevent indefinite retries. Exponential backoff retries will be attempted for up to 5 minutes and then stop if the connection has not been re-established

[NOTE]
.AD HOC Replications
====
No automatic reconnection attempts are made following network failures for ad hoc replications. +
The controlling user or application should apply the appropriate corrective action.
====

{empty} +
_Related replication definition elements_:  {legacy-configuration-properties--xref--db-rep-backoff}

== High Availability

include::partial$incpg-icr-availability.adoc[leveloffset=+1]


== Conflict Resolution

include::partial$incpg-icr-conflict.adoc[leveloffset=+1]


== Initialization

include::partial$incpg-icr-initialization.adoc[leveloffset=+1]








Sync Gateway supports the concurrent running of multiple inter-Sync Gateway replications.

Sync Gateway itself does not store anything persistently.
Because it is stateless it can be interrupted and-or restarted at anytime without negative side effects.

You can use the filers to selectively process specific channels and provide fine-grained routing capabilities.


* Replications can be configured to purge documents when channel access is revoked (a removal notification is received).

* {enterprise} only:
** Replications can use delta-sync mode, whereby only the changed data-items are replicated.




// Running highlights::
// +
// --
// * Multiple identical replicators can be initiated on a Sync Gateway node provided each has a unique `replication_Id`.
// * You can run inter-Sync Gateway replication of different versions on the same node, but you must ensure that they each have a different `replication_id`.
// * The user under which replication is being run must have read and write access to the data being replicated.
// * Exponential backoff when connection lost, doesn't apply to `adhoc`.
// * Inter-Sync Gateway will continue trying to connect for 30 minutes following authentication failure (including user-invalid/doesn't exist).
// * Running replications can be stopped. Stopped replications can be (re)Started.* On disconnected replications, replication will it will do exponential backoff upto reconnect-interval and then attempt to reconnect indefinitely based on this value. If 0, it will do exponential backoff upto 5 min before stopping the replication.

// * If ALL the Sync Gateway nodes in a source or target Sync Gateway cluster go down in the middle of continuous replication, by default, the system should pick up from the last document that was successfully processed by both sides when the replication/cluster is restarted

// * REST ONLY
// ** POST databases/{tkn-db}/_replication creates a replication using the {rep-id} specified in the body or if none specified, a unique UUID.
// ** PUT databases/{tkn-db}/_replication/{rep-id} upserts replication {rep-id}.

// * {enterprise} only:
// ** Replications are distributed even across all available Sync Gateway nodes and so are not guaranteed to run on their originating node.
// ** If a multi-node Sync Gateway cluster loses a subset of sync gateway nodes, the remaining nodes continue replication uninterrupted IF they have been configured to handle the replication (continuous and one-shot replications).
// --

// * Persistent continuous replications can be:
// ** Reset -- checkpoint back to starting value ?? check
// ** Updated -- only the parameter values provided in the PUT request body will be updated

// * Persistent and ad hoc replications can be:
// ** Removed -- only the replication_id is needed to delete ongoing continuous or one-shot replications.




== Monitoring and Administration

// tag::statistics[]
Sync Gateway provides a comprehensive set of replication-related statistics using the `_expvars` REST API endpoint.
// end::statistics[]

// tag::monitor[]
Admin REST API endpoints support the monitoring inter-Sync Gateway replication tasks (for example, get replication definitions, get replication status information).
// end::monitor[]

// tag::admin[]
Admin REST API endpoints support the management and administration of replications (for example: to cancel or start a stopped task; or to update a replication definition).
// end::admin[]

For more on management and administration see: {legacy-sg-replicate--xref}  |  {xref-sgw-pg-icr-sgreplicate-sgr2}
For more on monitoring and statistics see: {legacy-sg-replicate--xref}  |  {xref-sgw-pg-icr-sgreplicate-sgr2}

include::partial$block-related-content-icr.adoc[]