// BEGIN -- Inclusion-- sync-function.adoc
// BEGIN PAGE DEFINITION
//  LOCATION modules/ROOT/_partials/sync-api/
//  PURPOSE:
//    This is a standard content presentations page.
//    Its name/title identify the content/topic
//  PARAMETERS:
//    None
// END PAGE DEFINITION

Function:: access(username, channelname)

== Purpose

Use the `access()` function to grant a user access to a channel.


== Arguments

include::ROOT:partial$sync-api/syncargs.adoc[tags=args;args-user;args-channel]


NOTE: As a convenience, the resolved value of either argument may be `null` or `undefined`, in which case nothing happens.


== Context

You can invoke this function multiple times from within your Sync Function.

TIP: Prefix the `username` argument value with `role:` to apply this function to a role rather than a user.
This grants access to the specified channel(s) for all users assigned that role.

The effects of all access calls by all active documents are effectively combined in a union, so if any document grants a user access to a channel, that user has access to the channel.

The `access()` function grants access to users or roles that do not yet exist.
When you create new users or define roles later, the previous granted access permissions apply to them.

NOTE: The sync function `access()` call does not support the wildcard ('***') for granting access to all channels.
To grant a user access to all channels, use the REST API channel grant endpoint.

== Use

.access(username, channel)
====
This example shows some valid ways to call `access()`:

[source,javascript]
----
access ("jchris", "mtv"); // <.>
access ("jchris", ["mtv", "mtv2", "vh1"]); // <.>
access (["snej", "jchris", "role:admin"], "vh1"); // <.>
access (["snej", "jchris"], ["mtv", "mtv2", "vh1"]); // <.>
access (null, "hbo");  // <.>
access ("snej", null);
----
<.> Allow access of single channel to single user
<.> Allow access of multiple channels to single user
<.> Allow access of single channel to multiple users
<.> Allow access of multiple channels to multiple users
<.> The null arguments mean these are treated as no-ops
====

WARNING: If you invoke the `access()` function multiple times to grant the same user access to the same channel, you could see negative performance effects, such as large fetches or request timeouts.

// END