= Prepare to Install Sync Gateway
:page-aliases: ROOT:start/get-started-prepare.adoc, ROOT:getting-started.adoc
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:description: pass:q[Prerequisites for installing _Sync Gateway_; to synchronize your data from cloud to edge.]


include::ROOT:partial$_set_page_context.adoc[]


// BEGIN -- Page Attributes
:xref--pfx: {sgw--xref}:
:sg_download_link: {url-package-downloads}/\{version-full}/
:sg_package_name: couchbase-sync-gateway-community_{version-full}_x86_64
:sg_package_name_ee: couchbase-sync-gateway-enterprise_{version-full}_x86_64
:sg_accel_package_name: couchbase-sync-gateway-enterprise_{version-full}_x86_64
:btn-pfx: Select btn:
// END -- Page Attributes


// BEGIN -- Page Heading
:topic-group: Start Here!
:param-abstract: pass:q[This is *Step 2* in the _Start Here!_ topic group. It introduces the prerequisites for the installation of _Sync Gateway_]

include::ROOT:partial$_show_page_header_block.adoc[]
// END -- Page Heading

:param-page: {page-relative-src-path}
include::ROOT:partial$topic-group-get-started.adoc[]

== What You Need

Here's what you need in order to install Sync Gateway:

* To know whether your set-up meets the <<lbl-req-minim>> and <<lbl-req-compat>> for running Sync Gateway
* To have access to a working Couchbase Server deployment configured for Sync Gateway, or alternatively, to know how to {server-install-get-started--xref}
* To <<configure-server>>, including creating an appropriate set of RBAC users, ready for use in Sync Gateway and in the REST API
* Have appropriate network credentials and <<lbl-set-netw-access, Network Access>>

Once you have all that covered ... go {get-started-install--xref} {sgw-t}.

[#lbl-req-minim, reftext=Minimum Requirements]
== Couchbase Server Requirements

To use Sync Gateway you need an operational Couchbase Server installation.
Ensure that you use compatible versions of Couchbase Server and Sync Gateway -- see: <<lbl-req-compat>>.

TIP: You can get Couchbase Server from our {url-downloads}[Downloads, window=_blank] page

You will then need to configure Couchbase Server by adding a Bucket and an RBAC User for Sync Gateway -- see: <<configure-server>>.

include::ROOT:partial$block-caveats.adoc[tags="cbs6.0ke-xattrs"]

== Network Port Requirements

include::ROOT:partial$sgw-network-port-reqs.adoc[]


== Couchbase Server Host Ports

include::ROOT:partial$sgw-svr-ports.adoc[]

[#sgw-and-couchbase-server]


[#lbl-req-compat, reftext=Compatibility Requirements]
== Compatibility with Couchbase Server
include::ROOT:partial$sgw-svr-compatibility.adoc[]


== Compatibility with Couchbase Lite

include::ROOT:partial$compatibility-cbl-sgw.adoc[]


== Supported Operating Systems

include::ROOT:partial$sgw-supported-os.adoc[tags=sup-os-dev-test-prod]

include::ROOT:partial$sgw-supported-os.adoc[tags=sup-os-dev-test]

[#cloud-support]

include::ROOT:partial$sgw-supported-os.adoc[tags=sup-os-cloud]

== Cluster Configuration for Sync Gateway

Create a new cluster on a fresh Couchbase Server installation.

. Access the Admin Console at `+http://localhost:8091+`
+
. Select btn:[Setup New Cluster]
. Fill in the details for the new cluster on the `New Cluster` screen:
+
. Then press btn:[Next: Accept Terms]
. On the `Terms and Conditions` screen, accept the terms and conditions,
then Select btn:[Configure Disk, Memory, Services] to configure the cluster.
+
. Verify that you have selected `Data`, `Query`, and `Index` before selecting btn:[Save {amp} Finish]

[#configure-server]
== Configure Server for Sync Gateway


=== Step {counter: step} -- Create a Bucket

Use this bucket to test the deployment of Sync Gateway, later in the Getting Started section.

. Login to Couchbase Server's Admin Console
[upperroman]
.. Go to `+http://localhost:8091+`
.. Enter your administrator credentials.

. Within the Admin Console's toolbar,
[upperroman]
.. Select the *Buckets* tab
.. Select btn:[Add Bucket] to continue
.. In the pop-up window, enter *get-started-bucket* for the *name* and select *Add Bucket*.
You can leave the other options to their defaults.
+
include::ROOT:partial$block-caveats.adoc[tags="ephemeral-buckets"]


=== Step {counter: step} -- Create RBAC User

// tag::create-rbac-user[]

You'll need to create at least one RBAC user in Couchbase Server as {sgw} requires RBAC user credentials to authenticate and authorize access not only to Couchbase Server buckets, but also to its Admin and Metrics API.
If you plan to use these API then create at least one user for each of:

* Couchbase Server Access +
Add an RBAC user that Sync Gateway uses to authenticate and authorize access to Couchbase Server.
Use the _sync_gateway_ role.
* Admin API +
Add an RBAC user that administrators can use to authenticate and authorize access to the {sgw} Admin REST API
Use the _Full Admin_ role.
* Metrics API +
Add an RBAC user that devops can use to authenticate and authorize access to the {sgw} Metrics REST API
Use the _Read-Only Admin_ or _Application Access_ roles.

Enterprise edition users can exert a finer-grained control using additional roles appropriate to the capabilities required for the specific user.

NOTE: For more on creating Couchbase Server users see: {server-manage-security-users-and-roles--xref}.

// end::create-rbac-user[]


[#lbl-set-netw-access]
=== Step {counter: step} -- Set-up Network Access

When installing Couchbase Server on the cloud, ensure that network permissions (or firewall settings) allow incoming connections to Couchbase Server ports.

include::ROOT:partial$sgw-svr-ports.adoc[]

If this is not done, the Couchbase Server node can experience difficulty joining a cluster.

You can refer to the {xref--pfx-svr}install:install-ports.adoc[Couchbase Server Ports] guide to see the full list of available ports and their associated services.

// BEGIN -- Page Footer
include::ROOT:partial$block-related-content-deploy.adoc[]
// END -- Page Footer
