apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sync-gateway
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sync-gateway
    spec:
      containers:
        - name: sync-gateway
          image: couchbase/sync-gateway:2.1.2-enterprise
          args: ["/sync-gateway-config/sgw-config.json"]
          volumeMounts:
            - name: sgw-config-volume
              mountPath: /sync-gateway-config
              readOnly: true
          env:
            - name: GOMAXPROCS
              value: "2"
          resources:
            requests:
              cpu: "2"
            limits:
              cpu: "2"
      volumes:
        - name: sgw-config-volume
          secret:
            secretName: sgw-config