= Use Import Filters
:page-type: procedural
include::partial$_attributes-local.adoc[]
:xref-pfx: {xref-pfx-sgw}:

[abstract]
Provides an example configuration suitable for beginning to use Import Filters

For clusters with a large amount of data, the initial import process can take considerable time to complete.
Therefore, to get started with a cluster which contains a large number of pre-existing documents, we recommend to use an `import_filter` to reduce the initial import processing time.

[source,javascript]
----
include::example$getting-started/sync-gateway-config-import-filter.json[]
----

Configuration properties:

<1> The user's username that you created on the Couchbase Server Admin Console.
<2> The user's password that you created on the Couchbase Server Admin Console.
<3> The {xref-pfx}shared-bucket-access.adoc[shared bucket access] feature allows Couchbase Server SDKs to also perform operations on this bucket.
<4> `num_index_replicas` is the number of index replicas stored in Couchbase Server, introduced with {xref-pfx}indexing.adoc[GSI/N1QL indexing].
If you're running a single Couchbase Server node for development purposes the `num_index_replicas` must be set to `0`.
<5> Only import documents which have a `type` property equal to `mobile`.


