= Work With Sync Functions
:page-type: procedural
include::partial$_attributes-local.adoc[]
:xref-pfx: {xref-pfx-sgw}:

[abstract]
Provides an example configuration suitable for beginning to use sync functions

== Sync Function Basics
include::partial$sync-function-ovw.adoc[]

== Configuration

Add the `sync` function defined below into your `sync-gateway-config.json`:

[source,json]
----
include::example$configuration/sync-gateway-config.json[tag="sync-function-config"]
----
Configuration properties:

<1> The user's username that you created on the Couchbase Server Admin Console.
<2> The user's password that you created on the Couchbase Server Admin Console.
<3> The {xref-pfx}shared-bucket-access.adoc[shared bucket access] feature allows Couchbase Server SDKs to also perform operations on this bucket.
<4> `num_index_replicas` is the number of index replicas stored in Couchbase Server, introduced with {xref-pfx}indexing.adoc[GSI/N1QL indexing].
If you're running a single Couchbase Server node for development purposes the `num_index_replicas` must be set to `0`.
<5> The sync function -- a javascript function enclosed in backticks, which is actioned every time a new document, document revision or deletion is made to a data base (see: xref:config-properties.adoc#databases-foo_db-sync[databases.$db.sync] property).
)

== Related Information

.Next Steps
* See: {xref-pfx}sync-function.adoc[Sync Function Definition]

.Learn more:
* {xref-pfx}shared-bucket-access.adoc[Sync Mobile to Server]
* {xref-pfx}conf-properties.adoc[Config Schema Reference]

.Do more:
* _Import Filters_: To use Sync Gateway on clusters with a large amount of data you can configure an _import filter_ (see: {xref-pfx}ad-sgw-cfg-import-filter.adoc[Configure import filter]).

.Dive Deeper
See our blog, including https://blog.couchbase.com/using-channels-in-sync-gateway/[Using Sync Gateway Channels, windows=_blank]
