= How do I use Sync Functions?
:page-type: procedural
include::partial$_attributes-local.adoc[]
:page-layout: article
:page-status: {release-status-sgw} -- {release-comments-sgw}
:page-edition:
:page-role:
:description: Introducing sync functions and how to use them
:idprefix:
:idseparator: -
// End of page attributes


:xref-pfx: {xref-pfx-sgw}:

include::partial$_std-hdr-sgw.adoc[]

:topic-group: {tg-sgw-config}
:param-related: {xref-sgw-pg-config-properties}  |  {xref-sgw-pg-rest-api-admin} |    {xref-sgw-pg-config-properties-databases}  |  {xref-sgw-pg-config-properties-databases-sync}
:param-abstract: This content introduces the sync function, provides a simple example configuration suitable for those getting started using sync functions.
include::partial$block-abstract.adoc[]

== Sync Function Basics
include::partial$sync-function-ovw.adoc[]

== Configuration

Add the `sync` function defined below into your `sync-gateway-config.json`:

[source,json]
----
include::{example-cfg}[tag="sync-function-config"]
----
Configuration properties:

<1> The user's username that you created on the Couchbase Server Admin Console.
<2> The user's password that you created on the Couchbase Server Admin Console.
<3> The {xref-pfx}shared-bucket-access.adoc[shared bucket access] feature allows Couchbase Server SDKs to also perform operations on this bucket.
<4> `num_index_replicas` is the number of index replicas stored in Couchbase Server, introduced with {xref-pfx}indexing.adoc[GSI/N1QL indexing].
If you're running a single Couchbase Server node for development purposes the `num_index_replicas` must be set to `0`.
<5> The sync function -- a javascript function enclosed in backticks, which is actioned every time a new document, document revision or deletion is made to a data base (see: xref:config-properties.adoc#databases-foo_db-sync[databases.$db.sync] property).
)


include::partial$block-related-content-sync.adoc[]

