// BEGIN -- Inclusion-- sync-function.adoc
// BEGIN PAGE DEFINITION
//  LOCATION modules/ROOT/_partials/sync-api/
//  PURPOSE:
//    This is a standard content presentations page.
//    Its name/title identify the content/topic
//  PARAMETERS:
//    None
// END PAGE DEFINITION

== Function Call
channel(channelname)


== Purpose
Use the `channel()` function to route the document to the named channel(s).

== Arguments

include::partial$sync-api/syncargs.adoc[tags=args;args-channel]

// [args,cols="^1m,4",options="header"]
// |===

// |Argument
// |Description

// |channelname
// |The function accepts one argument which must be a string identifying a channel name, or an array of such strings.

// |===


== Context

The channel function can be called zero or more times from the sync function, for any document.

NOTE: Channels don't have to be predefined. +
A channel implicitly comes into existence when a document is routed to it.

Routing changes have no effect until the document is actually saved in the database, so if the sync function first calls `channel()` or `access()`, but then rejects the update, the channel and access changes will not occur.

TIP: As a convenience, it is legal to call `channel` with a `null` or `undefined` argument; it simply does nothing. +
This allows you to do something like `channel(doc.channels)` without having to first check whether `doc.channels` exists.


== Use

.channel(channelname)
====
This example routes all "published" documents to the "public" channel:

[source,javascript]
----
function (doc, oldDoc, meta) {
   if (doc.published) {
      channel("public");
   }
}
----

====
