// BEGIN -- Inclusion-- sync-function.adoc
// BEGIN PAGE DEFINITION
//  LOCATION modules/ROOT/_partials/sync-api/
//  PURPOSE:
//    This is a standard content presentations page.
//    Its name/title identify the content/topic
//  PARAMETERS:
//    None
// END PAGE DEFINITION

== Function Call
channel(channelname)


== Purpose
Use the `channel()` function to route the document to the named channel(s).

== Arguments

include::partial$sync-api/syncargs.adoc[tags=args;args-channel]

// [args,cols="^1m,4",options="header"]
// |===

// |Argument
// |Description

// |channelname
// |The function accepts one argument which must be a string identifying a channel name, or an array of such strings.

// |===

[#ex-sync-function-API-channel]
== Sync Function Examples

Couchbase Sync Gateway defines a Sync Function at the `collection` level. 
Defining at this level helps simplify data management and improve data reliability. 
Each collection in the system allows for only one Sync Function, which enables the specification of Access Control rules.

.Default Sync Function
====

=====
--

[source, javascript]
----
function (doc, oldDoc, meta) { 
   channel(CollectionName); 

}
----
Here the function then calls the `channel` and passes in the name of the collection `(CollectionsName)` as an argument.

By default, every document in the collection is automatically assigned to a channel with the same name as the collection. This system automatically creates a channel with the collection's name. The assignment of all documents to the collection channel is functionally similar to assigning them to the xref:2.7@sync-gateway-channels.adoc#star-channel[Star Channel].

To override this, use a custom sync function or a Specified Default Sync Function.


=====

====

.Specified Default Sync Function
====

=====
--

[source, javascript]
----
function (doc, oldDoc, meta) {
channel(doc.channels);

} 
----
Here is the default Sync Function when the default `scope` and default `collection` is clearly specified.

=====

====

.Upgraded Default Sync Function
====

=====
--

[source, javascript]
----
function (doc, oldDoc, meta) {
channel(doc.channels);

} 
----
Here is the default Sync Function when you have upgraded; it remains the same as the previous version.

=====

====

== Context

The channel function can be called zero or more times from the sync function, for any document.

NOTE: Channels don't have to be predefined. +
A channel implicitly comes into existence when a document is routed to it.

Routing changes have no effect until the document is actually saved in the database, so if the sync function first calls `channel()` or `access()`, but then rejects the update, the channel and access changes will not occur.

TIP: As a convenience, it is legal to call `channel` with a `null` or `undefined` argument; it simply does nothing. +
This allows you to do something like `channel(doc.channels)` without having to first check whether `doc.channels` exists.


== Use

.channel(channelname)
====
This example routes all "published" documents to the "public" channel:

[source,javascript]
----
function (doc, oldDoc, meta) {
   if (doc.published) {
      channel("public");
   }
}
----

====
