= Configure Sync Gateway
:page-layout: article
:page-role: panes
:page-status: {releaseStatus} -- {releaseComments}
:page-content: conceptual
include::partial$_attributesLocal.adoc[]


ifeval::["{releaseStatus}" == "beta"]
[.pane__frame--orange]
.Author's Notes
--
Document the configuration process.

Include Network Ports section and link to Configuration reference page xref:sync-gateway::config-properties.adoc[Configuration Schema])

--
endif::[]

[abstract]
Cover the configuration process and properties

== Overview

Reprehenderit pariatur magna eiusmod tempor est commodo aliqua elit proident irure. Velit cupidatat eiusmod sit enim pariatur exercitation tempor anim veniam ad in incididunt. Exercitation enim quis dolor irure irure nulla excepteur nisi duis nulla proident tempor.

Ea nulla occaecat sit nostrud cillum. Eiusmod fugiat adipisicing magna nisi eiusmod ad exercitation laboris sunt. Nostrud cupidatat pariatur non velit in sit ea magna. Cillum irure amet elit pariatur fugiat officia id voluptate irure. Tempor aute mollit in aliqua.


== Related Content

[.pane__frames]

* *How-to*
+
--
xref:sync-gateway::gs-install-sgw.adoc[Install & Sync]

xref:sync-gateway::gs-before.adoc[Before You Start]
--

* *Learn more*
+
--
xref:sync-gateway::shared-bucket-access.adoc[Introducing Data Sync]

include tutorial links as relevant

include blog links as relevant
--

* *Reference material*
+
--
xref:sync-gateway::config-properties.adoc[Configuration Schema]

(eg config file or api)
--
