= Install and Sync
:page-status: {release-status-sgw} -- {release-comments}
:page-edition: Under development
:page-layout: article
:page-content-type: procedural
:page-roles:
:page-aliases:
:description: Sync Gateway Installation Document
:keywords: edge nosql api synchronization replication
// End of Page Definition Statements

include::shared-mobile::partial$_attributes-shared.adoc[]
include::ROOT:partial$_attributes-local.adoc[]
include::ROOT:partial$_page-index.adoc[]

// BEGIN:: SET LOCAL ENVIRONMENT ATTRIBUTES
:packageNm: {component-sgw}

// END:: SET LOCAL ENVIRONMENT ATTRIBUTES

ifeval::["{releaseStatus}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--
Document the installation and synchroization process

Provide a better way of linking the CBL and SGW  (for instance link to getting started or replicator config section on CBL" .

Provide a Further Reading block to "REST API" reference since the tests discuss that
--
endif::[]

[abstract]
Cover the configuration process and properties

== Overview

Reprehenderit pariatur magna eiusmod tempor est commodo aliqua elit proident irure. Velit cupidatat eiusmod sit enim pariatur exercitation tempor anim veniam ad in incididunt. Exercitation enim quis dolor irure irure nulla excepteur nisi duis nulla proident tempor.

Ea nulla occaecat sit nostrud cillum. Eiusmod fugiat adipisicing magna nisi eiusmod ad exercitation laboris sunt. Nostrud cupidatat pariatur non velit in sit ea magna. Cillum irure amet elit pariatur fugiat officia id voluptate irure. Tempor aute mollit in aliqua.


== Related Content

[.pane__frames]

* *How-to*
+
--
{xref-sgw-pg-gs-sgw-api-access}
{xref-sgw-pg-gs-sgw-config}
//{xref-sgw-pg-gs-sgw-install}
{xref-sgw-pg-gs-sgw-prereqs}
{xref-sgw-pg-gs-sgw-svr-cfg}
--

* *Learn more*
+
--
{xref-sgw-pg-shared-bucket-access}
{xref-sgw-pg-rest-api-client}
include tutorial links as relevant
include blog links as relevant
--

* *Reference material*
+
--
{xref-sgw-pgconfig-properties}

(eg config file or api)
--
