= Configure Sync Gateway
:page-type: procedural

include::partial$_std-hdr-sgw.adoc[]
:xref-pfx: {xref-pfx-sgw}:

:param-abstract: Provides an example configuration suitable for the Getting Started activity
include::partial$block-abstract.adoc[]

The following steps explain how to configure Sync Gateway to connect to a Couchbase Server instance.

. Create a new file called *sync-gateway-config.json* with the following content:
+
--
[source,json]
----
include::{example-cfg}[tag="getting-started-config"]
----

.Configuration Properties:

<1> The user's username that you created on the Couchbase Server Admin Console.
<2> The user's password that you created on the Couchbase Server Admin Console.
<3> The {xref-sgw-pg-shared-bucket-access} feature allows Couchbase Server SDKs to also perform operations on this bucket.
<4> `num_index_replicas` is the number of index replicas stored in Couchbase Server, introduced with GSI/N1QL indexing -- see {xref-sgw-pg-indexing}.
If you're running a single Couchbase Server node for development purposes the `num_index_replicas` must be set to `0`.

--

. Start Sync Gateway
+
--
Start Sync Gateway from the command line, or if Sync Gateway is running in a service replace the configuration file and restart the service.

[source,bash]
----
~/Downloads/couchbase-sync-gateway/bin/sync_gateway ~/path/to/sync-gateway-config.json
----

Run the application where Couchbase Lite is installed.
--
. To verify that documents have been replicated, you can:
** Monitor the Sync Gateway sequence number returned by the database endpoint (xref:{sgw-pg-rest-api}#/database/get\__db__[`+GET /{tkn-db}/+`]).
The sequence number increments for every change that happens on the Sync Gateway database.
** Query a document by ID on the Sync Gateway REST API (xref:{sgw-pg-rest-api}#/document/get\__db___doc_[`+GET /{tkn-db}/{id}+`]).
** Query a document from the Query Workbench on the Couchbase Server Console.


include::partial$block-related-content-deploy.adoc[]

