= Test the Installation
:page-type: procedural
include::partial$_attributes-local.adoc[]
:xref-pfx: {xref-pfx-sgw}:

[abstract]
Shows how to access Sync Gateway APIs

Sync Gateway APIs are accessed on different TCP ports. This makes it easy to expose the Public REST API (port 4984) to endpoints while keeping the Admin REST API (port 4985) secure behind your firewall.

If you want to change the ports, you can do that in the configuration file, so:

* To change the Public REST API port, set the `interface` property in the configuration file.
* To change the Admin REST API port, set the `adminInterface` property in the configuration file.

The value of the property is a string consisting of a colon followed by a port number (for example, `:4985`).
You can also prepend a host name or numeric IP address before the colon to bind only to the network interface with that address.

As a useful special case, the IP address 127.0.0.1 binds to the loopback interface, making the port unreachable from any other host.
This is the default setting for the admin interface.

.Network Port Requirements
include::partial$sgw-network-port-reqs.adoc[]

== Related Information

.Next Steps
* {xref-pfx}gs-sgw-api-access.adoc[Access the API]

.Learn more:
* {xref-pfx}admin-rest-api.adoc[About the Admin API]
* {xref-pfx}rest-api.adoc[About the Public API]

.Do more:
** _Rest API Client_: {xref-pfx}rest-api-client.adoc[Build a simple api client]
