= REST API Access
:page-layout: article
:page-content: Reference
:description: Sync Gateway REST API Access

include::partial$_std-hdr-sgw.adoc[]

:param-abstract: Shows how to access Sync Gateway APIs
:param-related: {xref-sgw-pg-rest-api}  |  {xref-sgw-pg-rest-api-admin}  |  {xref-sgw-pg-rest-api-metrics}  |  {xref-sgw-pg-adv-rest-api-client}
:topic-group: REST API
include::partial$block-abstract.adoc[]

:xref-pfx: {xref-pfx-sgw}:

Sync Gateway REST APIs are accessed on different TCP ports.
This makes it easy to expose the Public REST API (port 4984) and Metrics REST API (port 4986) to endpoints while keeping the Admin REST API (port 4985) secure behind your firewall.

If you want to change the ports, you can do that in the configuration file, so:

* To change the Public REST API port, set the `interface` property in the configuration file.
* To change the Metric REST API port, set the `metricsInterface` property in the configuration file.
* To change the Admin REST API port, set the `adminInterface` property in the configuration file.

The value of the property is a string consisting of a colon followed by a port number (for example, `:4985`).
You can also prepend a host name or numeric IP address before the colon to bind only to the network interface with that address.

As a useful special case, the IP address 127.0.0.1 binds to the loopback interface, making the port unreachable from any other host.
This is the default setting for the admin interface.

.Network Port Requirements
include::partial$sgw-network-port-reqs.adoc[]

include::partial$block-related-content-api.adoc[]