// -- concept -- Roles
// include::partial$topic-group-access-control-concepts.adoc[]

== Concept
// tag::full[]
// tag::summary[]

Roles are named collections of {channels--xref}.
They enable the grouping together of {users--xref} with similar characteristics, which makes the management of large user populations easier.

// end::summary[]
// tag::body[]

A Role and a user assigned to a Role is granted access to a channel, a part of collections. 
The user can then access all documents assigned to that channel. 
When granting user access to admin channels statically, the user must specify the collection and corresponding channel.

As an entity, roles comprise a name and a list of channels.

Any user associated with a role inherits the right to access any of the channels in the role’s list. This provides a convenient way to associate multiple channels with multiple users.

TIP: Roles have a separate namespace from users, so it’s possible to have a user and a role with the same name.


// end::body[]
// end::full[]