// -- concept -- Users

== Concept

// tag::full[]
// tag::summary[]
Users are one of the cornerstone concepts of access control.
You can restrict document access to specific users and-or to users with specific roles.

// end::summary[]
// tag::body[]
As an entity a _user_ comprises a name, password, list of {roles--xref} and a list of {channels--xref}.

[#lbl-sgw-users]
== Sync Gateway Users

// tag::sgwuser[]
Sync Gateway users and roles have no relationship to <<lbl-rbac-users,Couchbase Server's _RBAC (Role-based Access Control) users_>>.
They are created and operate solely within the {sgw} ecosphere to govern access to replication data and to the Public API.

Users granted access to a {channel--xref} can access all documents assigned to that channel.

Users can also be assigned to zero or more {roles--xref}.
A user inherits the channel access of all roles it belongs to.
This is very much like Unix groups, except that roles do not form a hierarchy.

Sync Gateway user credentials can be used to authenticate access to the Public API; RBAC users are required for access to other API.
// end::sgwuser[]

[#lbl-rbac-users]
== RBAC Users
// tag::rbac[]
Couchbase Server _RBAC user_ credentials are required to authenticate and authorize access to the Admin and Metrics API.
You will need to create these users on Couchbase server in order to enable access -- see: {get-started-prepare--xref--create-rbac-users} for how to and {server-security-auth-overview--xref} for more on RBAC user authentication.

// end::rbac[]
// end::body[]
// end::full[]