
[[_bucket_configuration_model]]
=== bucket_configuration_model


// tag::content[]

Defines the Couchbase Server bucket to which this Sync Gateway database is associated.

_Note:_ ReadOnly data in this object is drawn from the Bootstrap Configuration and cannot be changed using the REST API.


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**server** +
__required__ +
__read-only__|Read-only item inherited from the bootstrap configuration file; cannot be changed using the REST API.

Defines the Couchbase Server connection string.|string
|**bucket** +
__required__|The `bucket` property defines the Couchbase Server bucket name for this database.

If not specified, then the database `name` is used as the `bucket` name. +
**Default** : `"database name"`|string
|**username** +
__required__ +
__read-only__|The item defines the RBAC user's username for authenticating to Couchbase Server.

There is no default.|string
|**password** +
__required__ +
__read-only__|The item defines the RBAC user's password for authenticating to Couchbase Server.

There is no default.|string
|**certpath** +
__optional__ +
__read-only__|Absolute or relative path on the filesystem to the TLS certificate file to be used to connect to the Couchbase Server.

Relative paths are relative to the directory that contains the Sync Gateway executable.|string
|**keypath** +
__optional__ +
__read-only__|Absolute or relative path on the filesystem to the TLS private key file to be used to connect to the Couchbase Server.

Relative paths are relative to the directory that contains the Sync Gateway executable.|string
|**cacertpath** +
__optional__ +
__read-only__|Absolute or relative path on the filesystem to the root CA certificate to verify the certificate chain and hostname of the Couchbase Server cluster.

Required for X509 Authentication.

Relative paths are relative to the directory that contains the Sync Gateway executable.|string
|**kv_tls_port** +
__optional__ +
__read-only__|Unused item|string
|===



// end::content[]



