
[[_user_configuration_model]]
=== user_configuration_model


// tag::content[]

Definition of a Sync Gateway user

Change initiates database restart


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**name** +
__required__|The user name (the same name used in the URL path).

The valid characters for a user name are alphanumeric ASCII characters and the underscore character.

The name property is required in a POST request.

You don’t need to include it in a PUT request because the user name is specified in the URL.|string
|**password** +
__optional__|Password of the user.

Mandatory, unless `allow_empty_password=true`.|string
|**admin_channels** +
__optional__|The channels that the user is able to access.|< string > array
|**admin_roles** +
__optional__|An array of the roles this user is associated with.|< string > array
|**all_channels** +
__optional__ +
__read-only__|Shows the channels the user can access, as granted by the sync function.

This is a read-only property.
Changes to it are ignored.|< string > array
|**email** +
__optional__|Email address of the user.|string
|**disabled** +
__optional__|This property is usually not included.

If the value is `true`, access for the account is disabled and the user will not be able to login.|boolean
|**roles** +
__optional__ +
__read-only__|Shows the roles this user is associated with by the Sync function.

This is a read-only property.
Changes to it are ignored.|< string > array
|===



// end::content[]



