= Configuration File
= Page title
:page-layout: article
:page-role: panes
:page-status: {releaseStatus} -- {releaseComments}
:page-content: reference
include::partial$_attributesLocal.adoc[]

ifndef::releaseStatus[:releaseStatus!:]
ifeval::["{releaseStatus}" == "beta"]
[.pane__frame--orange]
.Author's Notes
--
Incorporate configuration changes in sg.yaml

https://issues.couchbase.com/browse/DOC-6464
https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e77c903#heading=h.k07058a23ez5#

Move replicator settings under `Database' and deprecate 'preH2' settings
--
endif::[]

[abstract]
Sync Gateway's configuration schema

== About the Schema

Sync Gateway uses a JSON-like configuration file to define its runtime behavior.
The file's contents include, for example:

* Details of the connected Couchbase databases
* How replications are conducted
* What security is to be used
* What logging options are to be applied, and
* Any customization of import filtering and synchronization.

The majority of the configuration is achieved using standard JSON syntax -- see <<Configuration Reference>> for more.

[NOTE]
====
The `sync-gateway-config.json` file relies on the use of one _relaxed_ JSON feature; the use of back ticks  (`++`++`).
Text between back ticks is treated as a string.
It can span multiple lines and contain double-quotes.
Those features make it ideal for the JavaScript used in `sync` and `import_filter` functions.
====

Use the following command to run Sync Gateway with a configuration file:

[source, bashrc]

----
sync_gateway sync-gateway-config.json
----

== Configuration Reference

json_config_ui::{attachmentsdir}/sg.yaml[]



== Related Content

[.pane__frames]

* *How-to*
+
--
include how-to links as relevant,

include how-to links as relevant,
--

* *Learn more*
+
--
include any related concept links

include tutorial links as relevant

include blog links as relevant
--

* *Reference material*
+
--
include any reference docs

(eg config file or api)
--
