= Configuration File
:page-layout: article
:page-status:
:page-content: reference
:description: This content describes Sync Gateway's configuration schema providing parameter explanations and examples of use
// :param-abstract: This content describes Sync Gateway's configuration schema providing parameter explanations and examples of use
:keywords:

include::partial$_std-hdr-sgw.adoc[]

:topic-group: Sync Gateway Configuration
:param-related: {xref-sgw-pg-gs-sgw-config} | {xref-sgw-pg-rest-api-admin} | {xref-sgw-pg-rest-api} | {xref-sgw-pg-adv-rest-api-client}
include::partial$block-abstract.adoc[]

== About the Schema

Sync Gateway uses a JSON-like configuration file to define its runtime behavior.
The file's contents include, for example:

* Details of the connected Couchbase databases
* How replications are conducted
* What security is to be used
* What logging options are to be applied, and
* Any customization of import filtering and synchronization.

The majority of the configuration is achieved using standard JSON syntax -- see <<Configuration Reference>> for more.

[NOTE]
====
The `sync-gateway-config.json` file relies on the use of one _relaxed_ JSON feature; the use of back ticks  (`++`++`).
Text between back ticks is treated as a string.
It can span multiple lines and contain double-quotes.
Those features make it ideal for the JavaScript used in `sync` and `import_filter` functions.
====

Use the following command to run Sync Gateway with a configuration file:

[source, bashrc]
----
sync_gateway sync-gateway-config.json
----

== Configuration Reference


.Configuration Schema
// ====

json_config_ui::{attachmentsdir}/sg.yaml[]

// ====

== Example Sync Gateway Configuration

[source, json]
----
include::{example-cfg}[tags=icr-sample-sync-gateway-config, indent=0]
----

include::partial$block-related-content-api.adoc[]
